// Auto-generated French descriptions for atomic beginner exercises.
// Do not edit manually; run scripts/generate_atomic_beginner.mjs.

export const ATOMIC_BEGINNER_EXERCISES_FR: Record<number, string> = {
  "2081": "Écrivez un programme Python qui affiche le texte \"Hello\".",
  "2082": "Écrivez un programme Python qui affiche le texte \"Python\".",
  "2083": "Écrivez un programme Python qui affiche le texte \"Code\".",
  "2084": "Écrivez un programme Python qui affiche le texte \"Ready\".",
  "2085": "Écrivez un programme Python qui affiche le texte \"Start\".",
  "2086": "Écrivez un programme Python qui affiche le texte \"Learn\".",
  "2087": "Écrivez un programme Python qui affiche le texte \"Practice\".",
  "2088": "Écrivez un programme Python qui affiche le texte \"Debug\".",
  "2089": "Écrivez un programme Python qui affiche le texte \"Run\".",
  "2090": "Écrivez un programme Python qui affiche le texte \"Output\".",
  "2091": "Écrivez un programme Python qui affiche le texte \"Input\".",
  "2092": "Écrivez un programme Python qui affiche le texte \"Variable\".",
  "2093": "Écrivez un programme Python qui affiche le texte \"String\".",
  "2094": "Écrivez un programme Python qui affiche le texte \"Number\".",
  "2095": "Écrivez un programme Python qui affiche le texte \"List\".",
  "2096": "Écrivez un programme Python qui affiche le texte \"True\".",
  "2097": "Écrivez un programme Python qui affiche le texte \"False\".",
  "2098": "Écrivez un programme Python qui affiche le texte \"Good job\".",
  "2099": "Écrivez un programme Python qui affiche le texte \"Keep going\".",
  "2100": "Écrivez un programme Python qui affiche le texte \"Done\".",
  "2101": "Écrivez un programme Python qui affiche le nombre 0.",
  "2102": "Écrivez un programme Python qui affiche le nombre 1.",
  "2103": "Écrivez un programme Python qui affiche le nombre 2.",
  "2104": "Écrivez un programme Python qui affiche le nombre 3.",
  "2105": "Écrivez un programme Python qui affiche le nombre 4.",
  "2106": "Écrivez un programme Python qui affiche le nombre 5.",
  "2107": "Écrivez un programme Python qui affiche le nombre 7.",
  "2108": "Écrivez un programme Python qui affiche le nombre 9.",
  "2109": "Écrivez un programme Python qui affiche le nombre 10.",
  "2110": "Écrivez un programme Python qui affiche le nombre 12.",
  "2111": "Écrivez un programme Python qui affiche le nombre 15.",
  "2112": "Écrivez un programme Python qui affiche le nombre 20.",
  "2113": "Écrivez un programme Python qui affiche le nombre 25.",
  "2114": "Écrivez un programme Python qui affiche le nombre 30.",
  "2115": "Écrivez un programme Python qui affiche le nombre 42.",
  "2116": "Créez une variable appelée `name` et stockez-y la chaîne \"Noll\". Ensuite, affichez la variable.",
  "2117": "Créez une variable appelée `city` et stockez-y la chaîne \"Paris\". Ensuite, affichez la variable.",
  "2118": "Créez une variable appelée `pet` et stockez-y la chaîne \"cat\". Ensuite, affichez la variable.",
  "2119": "Créez une variable appelée `food` et stockez-y la chaîne \"rice\". Ensuite, affichez la variable.",
  "2120": "Créez une variable appelée `color` et stockez-y la chaîne \"blue\". Ensuite, affichez la variable.",
  "2121": "Créez une variable appelée `language` et stockez-y la chaîne \"Python\". Ensuite, affichez la variable.",
  "2122": "Créez une variable appelée `word` et stockez-y la chaîne \"hello\". Ensuite, affichez la variable.",
  "2123": "Créez une variable appelée `day` et stockez-y la chaîne \"Monday\". Ensuite, affichez la variable.",
  "2124": "Créez une variable appelée `tool` et stockez-y la chaîne \"keyboard\". Ensuite, affichez la variable.",
  "2125": "Créez une variable appelée `fruit` et stockez-y la chaîne \"apple\". Ensuite, affichez la variable.",
  "2126": "Créez une variable appelée `animal` et stockez-y la chaîne \"dog\". Ensuite, affichez la variable.",
  "2127": "Créez une variable appelée `school` et stockez-y la chaîne \"code\". Ensuite, affichez la variable.",
  "2128": "Créez une variable appelée `planet` et stockez-y la chaîne \"Mars\". Ensuite, affichez la variable.",
  "2129": "Créez une variable appelée `drink` et stockez-y la chaîne \"water\". Ensuite, affichez la variable.",
  "2130": "Créez une variable appelée `shape` et stockez-y la chaîne \"circle\". Ensuite, affichez la variable.",
  "2131": "Créez une variable appelée `age` et stockez-y le nombre 10. Ensuite, affichez la variable.",
  "2132": "Créez une variable appelée `score` et stockez-y le nombre 5. Ensuite, affichez la variable.",
  "2133": "Créez une variable appelée `level` et stockez-y le nombre 1. Ensuite, affichez la variable.",
  "2134": "Créez une variable appelée `year` et stockez-y le nombre 2026. Ensuite, affichez la variable.",
  "2135": "Créez une variable appelée `count` et stockez-y le nombre 3. Ensuite, affichez la variable.",
  "2136": "Créez une variable appelée `price` et stockez-y le nombre 8. Ensuite, affichez la variable.",
  "2137": "Créez une variable appelée `height` et stockez-y le nombre 12. Ensuite, affichez la variable.",
  "2138": "Créez une variable appelée `speed` et stockez-y le nombre 6. Ensuite, affichez la variable.",
  "2139": "Créez une variable appelée `points` et stockez-y le nombre 15. Ensuite, affichez la variable.",
  "2140": "Créez une variable appelée `size` et stockez-y le nombre 4. Ensuite, affichez la variable.",
  "2141": "Créez une variable appelée `total` et stockez-y le nombre 20. Ensuite, affichez la variable.",
  "2142": "Créez une variable appelée `number` et stockez-y le nombre 7. Ensuite, affichez la variable.",
  "2143": "Créez une variable appelée `rank` et stockez-y le nombre 2. Ensuite, affichez la variable.",
  "2144": "Créez une variable appelée `steps` et stockez-y le nombre 9. Ensuite, affichez la variable.",
  "2145": "Créez une variable appelée `coins` et stockez-y le nombre 11. Ensuite, affichez la variable.",
  "2146": "Écrivez un programme Python qui additionne 1 et 2, puis affiche le résultat.",
  "2147": "Écrivez un programme Python qui additionne 2 et 3, puis affiche le résultat.",
  "2148": "Écrivez un programme Python qui additionne 4 et 5, puis affiche le résultat.",
  "2149": "Écrivez un programme Python qui additionne 10 et 5, puis affiche le résultat.",
  "2150": "Écrivez un programme Python qui additionne 7 et 8, puis affiche le résultat.",
  "2151": "Écrivez un programme Python qui additionne 6 et 9, puis affiche le résultat.",
  "2152": "Écrivez un programme Python qui additionne 11 et 4, puis affiche le résultat.",
  "2153": "Écrivez un programme Python qui additionne 12 et 13, puis affiche le résultat.",
  "2154": "Écrivez un programme Python qui additionne 20 et 1, puis affiche le résultat.",
  "2155": "Écrivez un programme Python qui additionne 30 et 12, puis affiche le résultat.",
  "2156": "Écrivez un programme Python qui additionne 3 et 14, puis affiche le résultat.",
  "2157": "Écrivez un programme Python qui additionne 15 et 15, puis affiche le résultat.",
  "2158": "Écrivez un programme Python qui additionne 18 et 2, puis affiche le résultat.",
  "2159": "Écrivez un programme Python qui additionne 21 et 6, puis affiche le résultat.",
  "2160": "Écrivez un programme Python qui additionne 100 et 25, puis affiche le résultat.",
  "2161": "Écrivez un programme Python qui soustrait 5 et 2, puis affiche le résultat.",
  "2162": "Écrivez un programme Python qui soustrait 9 et 4, puis affiche le résultat.",
  "2163": "Écrivez un programme Python qui soustrait 10 et 3, puis affiche le résultat.",
  "2164": "Écrivez un programme Python qui soustrait 20 et 5, puis affiche le résultat.",
  "2165": "Écrivez un programme Python qui soustrait 30 et 10, puis affiche le résultat.",
  "2166": "Écrivez un programme Python qui soustrait 12 et 7, puis affiche le résultat.",
  "2167": "Écrivez un programme Python qui soustrait 15 et 6, puis affiche le résultat.",
  "2168": "Écrivez un programme Python qui soustrait 40 et 8, puis affiche le résultat.",
  "2169": "Écrivez un programme Python qui soustrait 18 et 9, puis affiche le résultat.",
  "2170": "Écrivez un programme Python qui soustrait 100 et 1, puis affiche le résultat.",
  "2171": "Écrivez un programme Python qui soustrait 50 et 25, puis affiche le résultat.",
  "2172": "Écrivez un programme Python qui soustrait 14 et 11, puis affiche le résultat.",
  "2173": "Écrivez un programme Python qui soustrait 22 et 2, puis affiche le résultat.",
  "2174": "Écrivez un programme Python qui soustrait 8 et 3, puis affiche le résultat.",
  "2175": "Écrivez un programme Python qui soustrait 70 et 30, puis affiche le résultat.",
  "2176": "Écrivez un programme Python qui multiplie 2 et 3, puis affiche le résultat.",
  "2177": "Écrivez un programme Python qui multiplie 4 et 5, puis affiche le résultat.",
  "2178": "Écrivez un programme Python qui multiplie 6 et 2, puis affiche le résultat.",
  "2179": "Écrivez un programme Python qui multiplie 7 et 3, puis affiche le résultat.",
  "2180": "Écrivez un programme Python qui multiplie 8 et 4, puis affiche le résultat.",
  "2181": "Écrivez un programme Python qui multiplie 9 et 5, puis affiche le résultat.",
  "2182": "Écrivez un programme Python qui multiplie 10 et 10, puis affiche le résultat.",
  "2183": "Écrivez un programme Python qui multiplie 3 et 11, puis affiche le résultat.",
  "2184": "Écrivez un programme Python qui multiplie 12 et 2, puis affiche le résultat.",
  "2185": "Écrivez un programme Python qui multiplie 5 et 5, puis affiche le résultat.",
  "2186": "Écrivez un programme Python qui multiplie 13 et 2, puis affiche le résultat.",
  "2187": "Écrivez un programme Python qui multiplie 15 et 3, puis affiche le résultat.",
  "2188": "Écrivez un programme Python qui multiplie 20 et 4, puis affiche le résultat.",
  "2189": "Écrivez un programme Python qui multiplie 25 et 2, puis affiche le résultat.",
  "2190": "Écrivez un programme Python qui multiplie 30 et 3, puis affiche le résultat.",
  "2191": "Écrivez un programme Python qui divise 10 et 2, puis affiche le résultat.",
  "2192": "Écrivez un programme Python qui divise 12 et 3, puis affiche le résultat.",
  "2193": "Écrivez un programme Python qui divise 20 et 4, puis affiche le résultat.",
  "2194": "Écrivez un programme Python qui divise 30 et 5, puis affiche le résultat.",
  "2195": "Écrivez un programme Python qui divise 42 et 6, puis affiche le résultat.",
  "2196": "Écrivez un programme Python qui divise 18 et 2, puis affiche le résultat.",
  "2197": "Écrivez un programme Python qui divise 100 et 10, puis affiche le résultat.",
  "2198": "Écrivez un programme Python qui divise 9 et 3, puis affiche le résultat.",
  "2199": "Écrivez un programme Python qui divise 16 et 4, puis affiche le résultat.",
  "2200": "Écrivez un programme Python qui divise 25 et 5, puis affiche le résultat.",
  "2201": "Écrivez un programme Python qui divise 36 et 6, puis affiche le résultat.",
  "2202": "Écrivez un programme Python qui divise 49 et 7, puis affiche le résultat.",
  "2203": "Écrivez un programme Python qui divise 64 et 8, puis affiche le résultat.",
  "2204": "Écrivez un programme Python qui divise 81 et 9, puis affiche le résultat.",
  "2205": "Écrivez un programme Python qui divise 8 et 2, puis affiche le résultat.",
  "2206": "Écrivez un programme Python qui affiche la longueur de la chaîne \"cat\", puis affiche le résultat.",
  "2207": "Écrivez un programme Python qui affiche la longueur de la chaîne \"dog\", puis affiche le résultat.",
  "2208": "Écrivez un programme Python qui affiche la longueur de la chaîne \"Python\", puis affiche le résultat.",
  "2209": "Écrivez un programme Python qui transforme la chaîne \"hello\" en majuscules, puis affiche le résultat.",
  "2210": "Écrivez un programme Python qui transforme la chaîne \"code\" en majuscules, puis affiche le résultat.",
  "2211": "Écrivez un programme Python qui transforme la chaîne \"WORLD\" en minuscules, puis affiche le résultat.",
  "2212": "Écrivez un programme Python qui transforme la chaîne \"APPLE\" en minuscules, puis affiche le résultat.",
  "2213": "Écrivez un programme Python qui met la première lettre de la chaîne \"python\" en majuscule, puis affiche le résultat.",
  "2214": "Écrivez un programme Python qui met la première lettre de la chaîne \"banana\" en majuscule, puis affiche le résultat.",
  "2215": "Écrivez un programme Python qui supprime les espaces au début et à la fin de la chaîne \"  hi  \", puis affiche le résultat.",
  "2216": "Écrivez un programme Python qui supprime les espaces au début et à la fin de la chaîne \"  cat\", puis affiche le résultat.",
  "2217": "Écrivez un programme Python qui met chaque mot de la chaîne \"blue car\" en forme titre, puis affiche le résultat.",
  "2218": "Écrivez un programme Python qui met chaque mot de la chaîne \"red ball\" en forme titre, puis affiche le résultat.",
  "2219": "Stockez la chaîne \"hello\". Remplacez chaque \"l\" par \"L\", puis affichez le résultat.",
  "2220": "Stockez la chaîne \"mississippi\". Comptez combien de fois \"s\" apparaît, puis affichez le nombre.",
  "2221": "Créez une liste contenant 1, 2, 3. Ensuite, affichez la liste.",
  "2222": "Créez une liste contenant 4, 5, 6. Ensuite, affichez la liste.",
  "2223": "Créez une liste contenant \"a\", \"b\", \"c\". Ensuite, affichez la liste.",
  "2224": "Créez une liste contenant \"red\", \"blue\". Ensuite, affichez la liste.",
  "2225": "Créez une liste contenant 10, 20. Ensuite, affichez la liste.",
  "2226": "Créez une liste contenant \"cat\", \"dog\". Ensuite, affichez la liste.",
  "2227": "Créez une liste contenant 0, 1. Ensuite, affichez la liste.",
  "2228": "Créez une liste contenant \"yes\", \"no\". Ensuite, affichez la liste.",
  "2229": "Créez une liste contenant 7, 8, 9. Ensuite, affichez la liste.",
  "2230": "Créez une liste contenant \"x\", \"y\", \"z\". Ensuite, affichez la liste.",
  "2231": "Créez une liste contenant 100, 200. Ensuite, affichez la liste.",
  "2232": "Créez une liste contenant \"sun\", \"moon\". Ensuite, affichez la liste.",
  "2233": "Créez une liste contenant 3, 1, 4. Ensuite, affichez la liste.",
  "2234": "Créez une liste contenant \"pen\", \"book\". Ensuite, affichez la liste.",
  "2235": "Créez une liste contenant 5, 10, 15. Ensuite, affichez la liste.",
  "2236": "Créez la liste [\"apple\", \"banana\", \"cherry\"]. Ensuite, affichez le premier élément.",
  "2237": "Créez la liste [\"red\", \"blue\", \"green\"]. Ensuite, affichez le premier élément.",
  "2238": "Créez la liste [10, 20, 30]. Ensuite, affichez le premier élément.",
  "2239": "Créez la liste [\"cat\", \"dog\", \"bird\"]. Ensuite, affichez le deuxième élément.",
  "2240": "Créez la liste [\"small\", \"medium\", \"large\"]. Ensuite, affichez le deuxième élément.",
  "2241": "Créez la liste [5, 6, 7]. Ensuite, affichez le deuxième élément.",
  "2242": "Créez la liste [\"north\", \"south\", \"east\"]. Ensuite, affichez le troisième élément.",
  "2243": "Créez la liste [\"a\", \"b\", \"c\"]. Ensuite, affichez le troisième élément.",
  "2244": "Créez la liste [100, 200, 300]. Ensuite, affichez le troisième élément.",
  "2245": "Créez la liste [\"one\", \"two\", \"three\"]. Ensuite, affichez le dernier élément.",
  "2246": "Créez la liste [\"morning\", \"noon\", \"night\"]. Ensuite, affichez le dernier élément.",
  "2247": "Créez la liste [2, 4, 6]. Ensuite, affichez le dernier élément.",
  "2248": "Créez la liste [\"zero\", \"one\"]. Ensuite, affichez le premier élément.",
  "2249": "Créez la liste [\"left\", \"right\"]. Ensuite, affichez le dernier élément.",
  "2250": "Créez la liste [9, 8]. Ensuite, affichez le dernier élément.",
  "2251": "Créez la liste [1, 2, 3]. Ensuite, affichez combien d’éléments elle contient.",
  "2252": "Créez la liste [\"a\", \"b\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2253": "Créez la liste [\"cat\", \"dog\", \"bird\", \"fish\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2254": "Créez la liste [10]. Ensuite, affichez combien d’éléments elle contient.",
  "2255": "Créez la liste []. Ensuite, affichez combien d’éléments elle contient.",
  "2256": "Créez la liste [\"red\", \"blue\", \"green\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2257": "Créez la liste [5, 6]. Ensuite, affichez combien d’éléments elle contient.",
  "2258": "Créez la liste [\"one\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2259": "Créez la liste [0, 1, 2, 3]. Ensuite, affichez combien d’éléments elle contient.",
  "2260": "Créez la liste [\"x\", \"y\", \"z\", \"w\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2261": "Créez la liste [100, 200, 300]. Ensuite, affichez combien d’éléments elle contient.",
  "2262": "Créez la liste [\"sun\", \"moon\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2263": "Créez la liste [7, 8, 9, 10, 11]. Ensuite, affichez combien d’éléments elle contient.",
  "2264": "Créez la liste [\"pen\", \"book\", \"bag\"]. Ensuite, affichez combien d’éléments elle contient.",
  "2265": "Créez la liste [42]. Ensuite, affichez combien d’éléments elle contient.",
  "2266": "Créez une comparaison qui vérifie si 5 > 3. Affichez le résultat booléen.",
  "2267": "Créez une comparaison qui vérifie si 2 < 1. Affichez le résultat booléen.",
  "2268": "Créez une comparaison qui vérifie si 10 == 10. Affichez le résultat booléen.",
  "2269": "Créez une comparaison qui vérifie si 7 != 8. Affichez le résultat booléen.",
  "2270": "Créez une comparaison qui vérifie si 4 >= 5. Affichez le résultat booléen.",
  "2271": "Créez une comparaison qui vérifie si 6 <= 6. Affichez le résultat booléen.",
  "2272": "Créez une comparaison qui vérifie si 9 > 12. Affichez le résultat booléen.",
  "2273": "Créez une comparaison qui vérifie si 1 < 4. Affichez le résultat booléen.",
  "2274": "Créez une comparaison qui vérifie si 3 == 4. Affichez le résultat booléen.",
  "2275": "Créez une comparaison qui vérifie si 8 != 8. Affichez le résultat booléen.",
  "2276": "Créez une comparaison qui vérifie si 15 >= 10. Affichez le résultat booléen.",
  "2277": "Créez une comparaison qui vérifie si 11 <= 2. Affichez le résultat booléen.",
  "2278": "Créez une comparaison qui vérifie si 0 == 0. Affichez le résultat booléen.",
  "2279": "Créez une comparaison qui vérifie si 20 > 19. Affichez le résultat booléen.",
  "2280": "Créez une comparaison qui vérifie si 30 < 10. Affichez le résultat booléen.",
  "2281": "Créez une variable appelée `age` avec la valeur 18. Si `age` >= 18, affichez \"adult\".",
  "2282": "Créez une variable appelée `score` avec la valeur 90. Si `score` >= 50, affichez \"pass\".",
  "2283": "Créez une variable appelée `temperature` avec la valeur 30. Si `temperature` > 25, affichez \"hot\".",
  "2284": "Créez une variable appelée `count` avec la valeur 0. Si `count` == 0, affichez \"empty\".",
  "2285": "Créez une variable appelée `name` avec la valeur \"Noll\". Si `name` == \"Noll\", affichez \"match\".",
  "2286": "Créez une variable appelée `speed` avec la valeur 5. Si `speed` < 10, affichez \"slow\".",
  "2287": "Créez une variable appelée `coins` avec la valeur 3. Si `coins` != 0, affichez \"has coins\".",
  "2288": "Créez une variable appelée `level` avec la valeur 1. Si `level` <= 1, affichez \"start\".",
  "2289": "Créez une variable appelée `points` avec la valeur 100. Si `points` >= 100, affichez \"max\".",
  "2290": "Créez une variable appelée `word` avec la valeur \"cat\". Si `word` != \"dog\", affichez \"different\".",
  "2291": "Créez une variable appelée `size` avec la valeur 4. Si `size` > 2, affichez \"big\".",
  "2292": "Créez une variable appelée `tries` avec la valeur 1. Si `tries` < 3, affichez \"try again\".",
  "2293": "Créez une variable appelée `light` avec la valeur \"green\". Si `light` == \"green\", affichez \"go\".",
  "2294": "Créez une variable appelée `number` avec la valeur 12. Si `number` >= 10, affichez \"two digits\".",
  "2295": "Créez une variable appelée `answer` avec la valeur \"yes\". Si `answer` == \"yes\", affichez \"confirmed\".",
  "2296": "Convertissez \"5\" avec `int()`, puis affichez le résultat.",
  "2297": "Convertissez \"12\" avec `int()`, puis affichez le résultat.",
  "2298": "Convertissez \"0\" avec `int()`, puis affichez le résultat.",
  "2299": "Convertissez 7 avec `str()`, puis affichez le résultat.",
  "2300": "Convertissez 42 avec `str()`, puis affichez le résultat.",
  "2301": "Convertissez 3.5 avec `str()`, puis affichez le résultat.",
  "2302": "Convertissez \"2.5\" avec `float()`, puis affichez le résultat.",
  "2303": "Convertissez \"10\" avec `float()`, puis affichez le résultat.",
  "2304": "Convertissez 1 avec `bool()`, puis affichez le résultat.",
  "2305": "Convertissez 0 avec `bool()`, puis affichez le résultat.",
  "2306": "Convertissez \"\" avec `bool()`, puis affichez le résultat.",
  "2307": "Convertissez \"hello\" avec `bool()`, puis affichez le résultat.",
  "2308": "Convertissez [1, 2] avec `tuple()`, puis affichez le résultat.",
  "2309": "Convertissez \"abc\" avec `list()`, puis affichez le résultat.",
  "2310": "Convertissez [\"a\", \"b\"] avec `tuple()`, puis affichez le résultat.",
  "2311": "Créez `name = \"Noll\"` et `age = 10`. Affichez la phrase \"Noll is 10\" avec une f-string.",
  "2312": "Créez `name = \"Ada\"` et `age = 12`. Affichez la phrase \"Ada is 12\" avec une f-string.",
  "2313": "Créez `name = \"Bo\"` et `age = 8`. Affichez la phrase \"Bo is 8\" avec une f-string.",
  "2314": "Créez `name = \"Mia\"` et `age = 7`. Affichez la phrase \"Mia is 7\" avec une f-string.",
  "2315": "Créez `name = \"Leo\"` et `age = 9`. Affichez la phrase \"Leo is 9\" avec une f-string.",
  "2316": "Créez `name = \"Zoe\"` et `age = 11`. Affichez la phrase \"Zoe is 11\" avec une f-string.",
  "2317": "Créez `name = \"Kai\"` et `age = 6`. Affichez la phrase \"Kai is 6\" avec une f-string.",
  "2318": "Créez `name = \"Ivy\"` et `age = 13`. Affichez la phrase \"Ivy is 13\" avec une f-string.",
  "2319": "Créez `name = \"Omar\"` et `age = 14`. Affichez la phrase \"Omar is 14\" avec une f-string.",
  "2320": "Créez `name = \"Lina\"` et `age = 15`. Affichez la phrase \"Lina is 15\" avec une f-string.",
  "2321": "Créez `name = \"Noah\"` et `age = 16`. Affichez la phrase \"Noah is 16\" avec une f-string.",
  "2322": "Créez `name = \"Emma\"` et `age = 5`. Affichez la phrase \"Emma is 5\" avec une f-string.",
  "2323": "Créez `name = \"Ava\"` et `age = 17`. Affichez la phrase \"Ava is 17\" avec une f-string.",
  "2324": "Créez `name = \"Eli\"` et `age = 18`. Affichez la phrase \"Eli is 18\" avec une f-string.",
  "2325": "Créez `name = \"Sara\"` et `age = 19`. Affichez la phrase \"Sara is 19\" avec une f-string.",
  "2326": "Créez le dictionnaire {\"name\": \"Noll\", \"age\": 10}. Ensuite, affichez la valeur de la clé \"name\".",
  "2327": "Créez le dictionnaire {\"name\": \"Ada\", \"age\": 12}. Ensuite, affichez la valeur de la clé \"age\".",
  "2328": "Créez le dictionnaire {\"color\": \"blue\", \"size\": 4}. Ensuite, affichez la valeur de la clé \"color\".",
  "2329": "Créez le dictionnaire {\"pet\": \"cat\", \"sound\": \"meow\"}. Ensuite, affichez la valeur de la clé \"sound\".",
  "2330": "Créez le dictionnaire {\"fruit\": \"apple\", \"count\": 3}. Ensuite, affichez la valeur de la clé \"count\".",
  "2331": "Créez le dictionnaire {\"city\": \"Paris\", \"country\": \"France\"}. Ensuite, affichez la valeur de la clé \"city\".",
  "2332": "Créez le dictionnaire {\"day\": \"Monday\", \"number\": 1}. Ensuite, affichez la valeur de la clé \"number\".",
  "2333": "Créez le dictionnaire {\"language\": \"Python\", \"level\": \"beginner\"}. Ensuite, affichez la valeur de la clé \"language\".",
  "2334": "Créez le dictionnaire {\"book\": \"code\", \"pages\": 20}. Ensuite, affichez la valeur de la clé \"pages\".",
  "2335": "Créez le dictionnaire {\"team\": \"red\", \"score\": 5}. Ensuite, affichez la valeur de la clé \"score\".",
  "2336": "Créez le dictionnaire {\"x\": 1, \"y\": 2}. Ensuite, affichez la valeur de la clé \"x\".",
  "2337": "Créez le dictionnaire {\"first\": \"A\", \"second\": \"B\"}. Ensuite, affichez la valeur de la clé \"second\".",
  "2338": "Créez le dictionnaire {\"hot\": True, \"cold\": False}. Ensuite, affichez la valeur de la clé \"hot\".",
  "2339": "Créez le dictionnaire {\"open\": \"yes\", \"closed\": \"no\"}. Ensuite, affichez la valeur de la clé \"closed\".",
  "2340": "Créez le dictionnaire {\"start\": 0, \"end\": 10}. Ensuite, affichez la valeur de la clé \"end\".",
  "2341": "Créez le tuple (\"red\", \"green\", \"blue\"). Ensuite, affichez le premier élément.",
  "2342": "Créez le tuple (\"red\", \"green\", \"blue\"). Ensuite, affichez le deuxième élément.",
  "2343": "Créez le tuple (\"red\", \"green\", \"blue\"). Ensuite, affichez le troisième élément.",
  "2344": "Créez le tuple (1, 2, 3). Ensuite, affichez le premier élément.",
  "2345": "Créez le tuple (1, 2, 3). Ensuite, affichez le deuxième élément.",
  "2346": "Créez le tuple (1, 2, 3). Ensuite, affichez le dernier élément.",
  "2347": "Créez le tuple (\"cat\", \"dog\"). Ensuite, affichez le premier élément.",
  "2348": "Créez le tuple (\"cat\", \"dog\"). Ensuite, affichez le dernier élément.",
  "2349": "Créez le tuple (\"yes\", \"no\", \"maybe\"). Ensuite, affichez le dernier élément.",
  "2350": "Créez le tuple (10, 20, 30). Ensuite, affichez le dernier élément.",
  "2351": "Créez le tuple (\"north\", \"south\"). Ensuite, affichez le deuxième élément.",
  "2352": "Créez le tuple (\"left\", \"middle\", \"right\"). Ensuite, affichez le deuxième élément.",
  "2353": "Créez le tuple (\"small\", \"large\"). Ensuite, affichez le premier élément.",
  "2354": "Créez le tuple (\"day\", \"night\"). Ensuite, affichez le dernier élément.",
  "2355": "Créez le tuple (5, 10). Ensuite, affichez le deuxième élément.",
  "2356": "Écrivez un programme Python qui affiche le reste de 5 divisé par 2.",
  "2357": "Écrivez un programme Python qui affiche le reste de 7 divisé par 3.",
  "2358": "Écrivez un programme Python qui affiche le reste de 10 divisé par 4.",
  "2359": "Écrivez un programme Python qui affiche le reste de 12 divisé par 5.",
  "2360": "Écrivez un programme Python qui affiche le reste de 15 divisé par 6.",
  "2361": "Écrivez un programme Python qui affiche le reste de 20 divisé par 7.",
  "2362": "Écrivez un programme Python qui affiche le reste de 21 divisé par 10.",
  "2363": "Écrivez un programme Python qui affiche le reste de 30 divisé par 8.",
  "2364": "Écrivez un programme Python qui affiche le reste de 42 divisé par 5.",
  "2365": "Écrivez un programme Python qui affiche le reste de 99 divisé par 10.",
  "2366": "Écrivez un programme Python qui affiche le reste de 100 divisé par 9.",
  "2367": "Écrivez un programme Python qui affiche le reste de 17 divisé par 4.",
  "2368": "Écrivez un programme Python qui affiche le reste de 25 divisé par 6.",
  "2369": "Écrivez un programme Python qui affiche le reste de 64 divisé par 10.",
  "2370": "Écrivez un programme Python qui affiche le reste de 81 divisé par 7.",
  "2371": "Vérifiez si \"a\" se trouve dans [\"a\", \"b\", \"c\"]. Affichez le résultat booléen.",
  "2372": "Vérifiez si \"z\" se trouve dans [\"a\", \"b\", \"c\"]. Affichez le résultat booléen.",
  "2373": "Vérifiez si 2 se trouve dans [1, 2, 3]. Affichez le résultat booléen.",
  "2374": "Vérifiez si 5 se trouve dans [1, 2, 3]. Affichez le résultat booléen.",
  "2375": "Vérifiez si \"cat\" se trouve dans [\"cat\", \"dog\"]. Affichez le résultat booléen.",
  "2376": "Vérifiez si \"bird\" se trouve dans [\"cat\", \"dog\"]. Affichez le résultat booléen.",
  "2377": "Vérifiez si \"red\" se trouve dans [\"red\", \"blue\"]. Affichez le résultat booléen.",
  "2378": "Vérifiez si \"green\" se trouve dans [\"red\", \"blue\"]. Affichez le résultat booléen.",
  "2379": "Vérifiez si \"p\" se trouve dans \"python\". Affichez le résultat booléen.",
  "2380": "Vérifiez si \"z\" se trouve dans \"python\". Affichez le résultat booléen."
};
