#!/bin/bash

COMMAND=$1

if [ -z "$COMMAND" ]; then
    echo "Usage: explain_command.sh <command> [args]"
    echo "Example: explain_command.sh chmod -R 755"
    exit 1
fi

echo "═══════════════════════════════════════════════════════════════"
echo "                    📖 COMMAND EXPLANATION"
echo "═══════════════════════════════════════════════════════════════"
echo "Command: $COMMAND"
echo ""

case "$COMMAND" in
    chmod)
        echo "📌 Purpose: Change file permissions"
        echo ""
        echo "🔧 Common flags:"
        echo "  -R  Recursive (affect all files in directory)"
        echo "  -v  Verbose (show changes)"
        echo "  -c  Report only when changes made"
        echo ""
        echo "🔢 Permission codes:"
        echo "  4 = read (r)"
        echo "  2 = write (w)"
        echo "  1 = execute (x)"
        echo ""
        echo "📋 Common examples:"
        echo "  chmod 755 file   → Owner rwx, group/others rx"
        echo "  chmod 644 file   → Owner rw, group/others r"
        echo "  chmod +x file    → Add execute permission"
        echo ""
        echo "⚠️  WARNING: chmod -R 777 makes everything writable!"
        ;;
    chown)
        echo "📌 Purpose: Change file ownership"
        echo ""
        echo "🔧 Common flags:"
        echo "  -R  Recursive"
        echo "  -v  Verbose"
        echo "  -c  Report changes"
        echo ""
        echo "📋 Examples:"
        echo "  chown user:group file    Change owner and group"
        echo "  chown user file          Change owner only"
        echo ""
        echo "⚠️  WARNING: Requires sudo for others' files!"
        ;;
    rm)
        echo "📌 Purpose: Remove files or directories"
        echo ""
        echo "🔴 ⚠️ DESTRUCTIVE - USE WITH EXTREME CAUTION! 🔴 ⚠️"
        echo ""
        echo "🔧 Common flags:"
        echo "  -f  Force, ignore nonexistent files"
        echo "  -i  Prompt before every removal"
        echo "  -r  Recursive (delete directories)"
        echo "  -v  Explain what is being done"
        echo ""
        echo "🔴 DANGEROUS EXAMPLES:"
        echo "  rm -rf /     🔴🔴🔴 DELETE EVERYTHING ON SYSTEM!"
        echo "  rm -rf *     🔴🔴🔴 DELETE ALL IN CURRENT DIR!"
        echo "  rm -rf ./*   🔴🔴🔴 SAME AS ABOVE!"
        echo "  rm -rf .     🔴🔴🔴 DELETE CURRENT DIRECTORY!"
        echo ""
        echo "✅ Safe alternatives:"
        echo "  rm -i file    → Prompt before each deletion"
        echo "  ls first     → See what you're deleting"
        ;;
    ls)
        echo "📌 Purpose: List directory contents"
        echo ""
        echo "🔧 Common flags:"
        echo "  -l  Long format (details)"
        echo "  -a  Show hidden files"
        echo "  -h  Human readable sizes"
        echo "  -t  Sort by time modified"
        echo "  -S  Sort by size"
        echo "  -R  Recursive (subdirectories)"
        ;;
    find)
        echo "📌 Purpose: Search for files in directory tree"
        echo ""
        echo "🔧 Common flags:"
        echo "  -name pattern    Search by name"
        echo "  -type f/d       File or directory"
        echo "  -mtime +days    Modified days ago"
        echo "  -size +N        File size"
        echo "  -exec cmd       Run command on results"
        echo ""
        echo "📋 Examples:"
        echo "  find . -name '*.txt'"
        echo "  find . -type f -mtime -7"
        echo "  find . -type d -empty"
        ;;
    grep)
        echo "📌 Purpose: Search for patterns in files"
        echo ""
        echo "🔧 Common flags:"
        echo "  -i  Ignore case"
        echo "  -r  Recursive"
        echo "  -n  Show line numbers"
        echo "  -v  Invert match"
        echo "  -l  Show filenames only"
        echo "  -A n  Show n lines after match"
        echo "  -B n  Show n lines before match"
        ;;
    sudo)
        echo "📌 Purpose: Execute command as superuser"
        echo ""
        echo "🔴 ⚠️ GIVES ROOT ACCESS - USE WITH CAUTION! 🔴 ⚠️"
        echo ""
        echo "🔧 Common usage:"
        echo "  sudo apt update    Update packages (Debian/Ubuntu)"
        echo "  sudo yum update   Update packages (RHEL/CentOS)"
        echo "  sudo systemctl    Manage services"
        echo "  sudo su           Switch to root shell"
        echo ""
        echo "⚠️  WARNING: You can break system with sudo!"
        ;;
    curl)
        echo "📌 Purpose: Transfer data from/to server"
        echo ""
        echo "🔧 Common flags:"
        echo "  -O  Save output to file"
        echo "  -o  Specify output filename"
        echo "  -s  Silent mode"
        echo "  -L  Follow redirects"
        echo "  -X  Specify HTTP method"
        echo "  -H  Add header"
        echo "  -d  Send data (POST)"
        ;;
    ssh)
        echo "📌 Purpose: Secure remote login"
        echo ""
        echo "🔧 Common flags:"
        echo "  -p  Port (default 22)"
        echo "  -i  Identity file (private key)"
        echo "  -v  Verbose mode"
        echo "  -Y  Trusted X11 forwarding"
        echo ""
        echo "📋 Examples:"
        echo "  ssh user@hostname"
        echo "  ssh -p 2222 user@host"
        echo "  ssh -i ~/.ssh/key user@host"
        ;;
    tar)
        echo "📌 Purpose: Archive files"
        echo ""
        echo "🔧 Common flags:"
        echo "  -c  Create archive"
        echo "  -x  Extract archive"
        echo "  -v  Verbose"
        echo "  -f  File name"
        echo "  -z  gzip compression"
        echo "  -j  bzip2 compression"
        echo ""
        echo "📋 Examples:"
        echo "  tar -czvf archive.tar.gz dir/    Create"
        echo "  tar -xzvf archive.tar.gz         Extract"
        ;;
    systemctl)
        echo "📌 Purpose: Control systemd services (Linux)"
        echo ""
        echo "🔧 Common commands:"
        echo "  start    Start service"
        echo "  stop     Stop service"
        echo "  restart  Restart service"
        echo "  status   Show service status"
        echo "  enable   Start at boot"
        echo "  disable  Disable at boot"
        echo ""
        echo "⚠️  WARNING: Affects system services!"
        ;;
    dd)
        echo "📌 Purpose: Copy and convert data"
        echo ""
        echo "🔴 ⚠️ VERY DANGEROUS - CAN WIPE DRIVES! 🔴 ⚠️"
        echo ""
        echo "🔧 Common flags:"
        echo "  if=       Input file"
        echo "  of=       Output file"
        echo "  bs=       Block size"
        echo "  count=    Number of blocks"
        echo ""
        echo "🔴 DANGEROUS EXAMPLES:"
        echo "  dd if=/dev/zero of=/dev/sda    🔴🔴🔴 WIPES DRIVE!"
        echo "  dd if=/dev/urandom of=device   🔴🔴🔴 DESTROYS DEVICE!"
        echo ""
        echo "⚠️  ALWAYS double-check 'of=' parameter!"
        ;;
    *)
        echo "📌 No specific explanation available for: $COMMAND"
        echo ""
        echo "🔍 General advice:"
        echo "  - Use 'man $COMMAND' for manual"
        echo "  - Use '$COMMAND --help' for options"
        echo "  - Search online for specific usage"
        ;;
esac

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "⚠️  ALWAYS verify command effects before execution!"
echo "⚠️  NEVER run commands you don't understand!"
echo "⚠️  Ask for clarification if unsure!"
echo "═══════════════════════════════════════════════════════════════"