export type AiLanguage = 'en' | 'fr';

const FRENCH_QUERY_REPLACEMENTS: Array<[RegExp, string]> = [
    [/combien (?:y a[- ]t[- ]il|existe[- ]t[- ]il|existe|de)\s+(?:de |des )?m[eé]thodes?/gi, 'how many methods are there'],
    [/combien (?:y a[- ]t[- ]il|existe[- ]t[- ]il|existe|de)\s+(?:de |des )?fonctions? int[eé]gr[eé]es?/gi, 'how many built-in functions are there'],
    [/comment (?:est[- ]ce qu['’]on |puis[- ]je |peut[- ]on |faire pour )?(?:cr[eé]er|d[eé]finir|[eé]crire)\s+(?:une |la )?m[eé]thode/gi, 'how do you create a method'],
    [/comment (?:est[- ]ce qu['’]on |puis[- ]je |peut[- ]on |faire pour )?(?:cr[eé]er|commencer|faire|utiliser)\s+(?:la |un programme en )?(?:poo|programmation orient[eé]e objet)/gi, 'how do you create oop'],
    [/dans quelle version(?: de python)?\s+(.+?)\s+a[- ]t[- ](?:il|elle)\s+[eé]t[eé]\s+ajout[eé]e?/gi, 'what python version was $1 added'],
    [/quelle version(?: de python)?\s+a\s+ajout[eé]\s+(.+)/gi, 'what python version was $1 added'],
    [/qu['’]est[- ]ce que\s+(?:(?:une|un|les|des|le|la)\s+)?/gi, 'what is '],
    [/qu['’]est[- ]ce qu['’](?:une|un|les|des|le|la)?\s+liste\b/gi, 'what is a list data type'],
    [/qu['’]est[- ]ce qu['’](?:une|un|les|des|le|la)?\s+dictionnaire\b/gi, 'what is a dictionary data type'],
    [/qu['’]est[- ]ce qu['’](?:une|un|les|des|le|la)?\s+cha[iî]ne(?: de caract[eè]res)?\b/gi, 'what is a string data type'],
    [/qu['’]est[- ]ce qu['’](?:une|un|les|des|le|la)?\s+tuple\b/gi, 'what is a tuple data type'],
    [/qu['’]est[- ]ce qu['’](?:une|un|les|des|le|la)?\s+ensemble\b/gi, 'what is a set data type'],
    [/qu['’]est[- ]ce qu['’](?:(?:une|un|les|des|le|la)\s+)?/gi, 'what is '],
    [/c['’]est quoi\s+/gi, 'what is '],
    [/quelle est la diff[eé]rence entre\s+/gi, 'what is the difference between '],
    [/quelles sont les diff[eé]rences entre\s+/gi, 'what is the difference between '],
    [/peux[- ]tu m['’]expliquer\s+/gi, 'explain '],
    [/pouvez[- ]vous m['’]expliquer\s+/gi, 'explain '],
    [/explique[- ]moi\s+/gi, 'explain '],
    [/comment fonctionne(?:nt)?\s+/gi, 'how does '],
    [/comment utiliser\s+/gi, 'how to use '],
    [/pourquoi\s+/gi, 'why '],
    [/donne[- ]moi des exemples?(?: de| d['’])?\s*/gi, 'give examples of '],
    [/montre[- ]moi\s+/gi, 'show me '],
    [/(?:liste[- ]moi|lister) (?:toutes? |les )?/gi, 'list all '],
    [/fonction int[eé]gr[eé]e/gi, 'built-in function'],
    [/fonctions int[eé]gr[eé]es/gi, 'built-in functions'],
    [/m[eé]thodes?/gi, 'method'],
    [/cha[iî]nes? de caract[eè]res?/gi, 'string'],
    [/dictionnaires?/gi, 'dictionary'],
    [/ensembles?/gi, 'set'],
    [/listes?/gi, 'list'],
    [/tuples?/gi, 'tuple'],
    [/boucles? pour/gi, 'for loop'],
    [/boucles? tant que/gi, 'while loop'],
    [/compr[eé]hensions? de liste/gi, 'list comprehension'],
    [/gestion des exceptions/gi, 'exception handling'],
    [/programmation orient[eé]e objet/gi, 'object-oriented programming'],
    [/fermetures?/gi, 'closure'],
    [/g[eé]n[eé]rateurs?/gi, 'generator'],
    [/d[eé]corateurs?/gi, 'decorator'],
    [/arguments? nomm[eé]s?/gi, 'keyword argument'],
    [/valeur de retour/gi, 'return value'],
    [/renvoie(?:r|nt)?/gi, 'return'],
    [/affiche(?:r|nt)?/gi, 'print'],
    [/\bet\b/gi, 'and'],
];

export const normalizeAiQuestionForLookup = (question: string, language: AiLanguage): string => {
    if (language !== 'fr') return question;
    return FRENCH_QUERY_REPLACEMENTS.reduce(
        (value, [pattern, replacement]) => value.replace(pattern, replacement),
        question,
    );
};

const PHRASE_REPLACEMENTS: Array<[RegExp, string]> = [
    [/SyntaxError:\s*invalid syntax/gi, 'Erreur de syntaxe : syntaxe invalide'],
    [/IndentationError:\s*expected an indented block/gi, 'Erreur d\'indentation : un bloc indenté est attendu'],
    [/IndentationError:\s*unexpected indent/gi, 'Erreur d\'indentation : indentation inattendue'],
    [/NameError:\s*name ([A-Za-z_]\w*) is not defined/gi, 'Erreur de nom : le nom $1 n\'est pas défini'],
    [/TypeError:\s*/gi, 'Erreur de type : '],
    [/ValueError:\s*/gi, 'Erreur de valeur : '],
    [/IndexError:\s*list index out of range/gi, 'Erreur d\'index : index de liste hors limites'],
    [/KeyError:\s*/gi, 'Erreur de clé : '],
    [/ZeroDivisionError:\s*division by zero/gi, 'Erreur de division par zéro'],
    [/ModuleNotFoundError:\s*No module named/gi, 'Module introuvable : aucun module nommé'],
    [/FileNotFoundError:\s*/gi, 'Fichier introuvable : '],
    [/unexpected EOF while parsing/gi, 'fin de fichier inattendue pendant l\'analyse'],
    [/was never closed/gi, 'n\'a jamais été fermé'],
    [/is not callable/gi, 'n\'est pas appelable'],
    [/is not iterable/gi, 'n\'est pas itérable'],
    [/object is not subscriptable/gi, 'l\'objet ne peut pas être indexé'],
    [/takes (\d+) positional arguments? but (\d+) were given/gi, 'accepte $1 argument(s) positionnel(s), mais $2 ont été fournis'],
    [/All (\d+) tests passed as a script answer\./gi, 'Les $1 tests ont réussi avec une réponse sous forme de script.'],
    [/All (\d+) tests passed using ([A-Za-z_]\w*)\(\)\./gi, 'Les $1 tests ont réussi avec $2().'],
    [/All (\d+) script tests passed\./gi, 'Les $1 tests de script ont réussi.'],
    [/All tests passed\./gi, 'Tous les tests ont réussi.'],
    [/Missing function\. Expected one of:/gi, 'Fonction manquante. L’une de ces fonctions est attendue :'],
    [/A script answer is also accepted if it passes every visible and generated test\./gi, 'Une réponse sous forme de script est aussi acceptée si elle réussit tous les tests visibles et générés.'],
    [/Missing required function ([A-Za-z_]\w*)\(\)\./gi, 'Fonction obligatoire $1() manquante.'],
    [/Missing required input\(\):/gi, 'Appel obligatoire à input() manquant :'],
    [/Missing required random call:/gi, 'Appel aléatoire obligatoire manquant :'],
    [/Missing required source pattern:/gi, 'Structure de code obligatoire manquante :'],
    [/Missing required syntax:/gi, 'Syntaxe obligatoire manquante :'],
    [/Missing required class:/gi, 'Classe obligatoire manquante :'],
    [/Missing required inheritance:/gi, 'Héritage obligatoire manquant :'],
    [/Missing required boolean operator:/gi, 'Opérateur booléen obligatoire manquant :'],
    [/Missing required operator:/gi, 'Opérateur obligatoire manquant :'],
    [/Missing required unpacking:/gi, 'Décomposition obligatoire manquante :'],
    [/Hard-coded output detected:/gi, 'Sortie codée en dur détectée :'],
    [/Expected output ([^,\n]+), got /gi, 'Sortie attendue $1, résultat obtenu '],
    [/Expected ([^,\n]+), got /gi, 'Valeur attendue $1, résultat obtenu '],
    [/raised ([A-Za-z_]\w*):/gi, 'a déclenché $1 :'],
    [/Ask any Python question\./gi, 'Posez n\'importe quelle question sur Python.'],
    [/I can explain concepts, list methods and built-ins, compare ideas, or help you understand code\./gi, 'Je peux expliquer des concepts, lister des méthodes et des fonctions intégrées, comparer des notions ou vous aider à comprendre du code.'],
    [/I can follow up/gi, 'Je peux répondre à des questions de suivi'],
    [/try saying/gi, 'essayez de dire'],
    [/after an answer/gi, 'après une réponse'],
    [/If your question is unclear, I will ask a clarification instead of guessing\./gi, 'Si votre question n\'est pas claire, je demanderai une précision au lieu de deviner.'],
    [/Click Save to store the conversation or Clear to start fresh\./gi, 'Appuyez sur Sauvegarder pour conserver la conversation ou sur Effacer pour recommencer.'],
    [/Here are all Python methods/gi, 'Voici toutes les méthodes Python'],
    [/Methods vs built-in functions:\s*mutating rule/gi, 'Méthodes et fonctions intégrées : règle de modification'],
    [/Core rule/gi, 'Règle principale'],
    [/Methods that modify an existing mutable object usually return/gi, 'Les méthodes qui modifient un objet mutable existant renvoient généralement'],
    [/They change the original object instead of creating and returning a new one\./gi, 'Elles modifient l\'objet d\'origine au lieu de créer et de renvoyer un nouvel objet.'],
    [/Python does this to make mutation obvious\./gi, 'Python suit cette convention pour rendre la modification sur place explicite.'],
    [/Original changed\?/gi, 'Objet d\'origine modifié ?'],
    [/reverse iterator/gi, 'itérateur inversé'],
    [/new sorted list/gi, 'nouvelle liste triée'],
    [/changes the original list/gi, 'modifie la liste d\'origine'],
    [/leaves the original unchanged/gi, 'laisse l\'objet d\'origine inchangé'],
    [/What is an iterator\?/gi, 'Qu\'est-ce qu\'un itérateur ?'],
    [/An iterator produces one value at a time\./gi, 'Un itérateur produit une valeur à la fois.'],
    [/does not immediately make a full list/gi, 'ne crée pas immédiatement une liste complète'],
    [/if you want the full reversed list/gi, 'si vous voulez obtenir toute la liste inversée'],
    [/Kind/gi, 'Type'],
    [/Tool/gi, 'Outil'],
    [/list method/gi, 'méthode de liste'],
    [/Python concepts I can explain/gi, 'Concepts Python que je peux expliquer'],
    [/list data type/gi, 'type liste'],
    [/dictionary data type/gi, 'type dictionnaire'],
    [/string data type/gi, 'type chaîne'],
    [/tuple data type/gi, 'type tuple'],
    [/set data type/gi, 'type ensemble'],
    [/Python built-in functions/gi, 'Fonctions intégrées de Python'],
    [/Python keywords/gi, 'Mots-clés Python'],
    [/String methods/gi, 'Méthodes de chaîne'],
    [/List methods/gi, 'Méthodes de liste'],
    [/Dictionary methods/gi, 'Méthodes de dictionnaire'],
    [/Dict methods/gi, 'Méthodes de dictionnaire'],
    [/Set methods/gi, 'Méthodes d\'ensemble'],
    [/Tuple methods/gi, 'Méthodes de tuple'],
    [/Ask (?:me )?about any individual method for details!?/gi, 'Demandez des détails sur n\'importe quelle méthode.'],
    [/Ask about a specific method like/gi, 'Demandez des détails sur une méthode comme'],
    [/Ask about a specific built-in for details!?/gi, 'Demandez des détails sur une fonction intégrée précise.'],
    [/Ask (?:me )?to explain any of these!?/gi, 'Demandez-moi d\'expliquer l\'un de ces éléments.'],
    [/Built-in function/gi, 'Fonction intégrée'],
    [/Returns the length \(number of items\) of a sequence or collection\./gi, 'Renvoie la longueur (le nombre d\'éléments) d\'une séquence ou d\'une collection.'],
    [/No specific exception is guaranteed; invalid types or values may still raise an exception\./gi, 'Aucune exception précise n\'est garantie ; des types ou des valeurs invalides peuvent tout de même déclencher une exception.'],
    [/See the linked current Python 3 documentation for version-specific behavior\./gi, 'Consultez la documentation Python 3 liée pour connaître le comportement propre à chaque version.'],
    [/Verified API example/gi, 'Exemple d\'API vérifié'],
    [/Official Python built-in functions/gi, 'Documentation officielle des fonctions intégrées Python'],
    [/Official Python language reference/gi, 'Référence officielle du langage Python'],
    [/Official Python documentation/gi, 'Documentation officielle de Python'],
    [/Key point/gi, 'À retenir'],
    [/Focus first on what (.+?) does, then on its syntax\./gi, 'Concentrez-vous d\'abord sur le rôle de $1, puis sur sa syntaxe.'],
    [/Category context/gi, 'Contexte de la catégorie'],
    [/Deeper context/gi, 'Contexte approfondi'],
    [/Problem requirement/gi, 'Exigence du problème'],
    [/Line-by-line code inspection/gi, 'Vérification du code ligne par ligne'],
    [/Code inspection/gi, 'Vérification du code'],
    [/Output analysis/gi, 'Analyse de la sortie'],
    [/Code explanation/gi, 'Explication du code'],
    [/Expected solution workflow/gi, 'Déroulement attendu de la solution'],
    [/Solution workflow/gi, 'Déroulement de la solution'],
    [/Execution order/gi, 'Ordre d\'exécution'],
    [/Order of operation/gi, 'Ordre des opérations'],
    [/Suggested fix/gi, 'Correction suggérée'],
    [/Suggested direction/gi, 'Piste suggérée'],
    [/What to change/gi, 'Ce qu\'il faut modifier'],
    [/Incorrect\./gi, 'Incorrecte.'],
    [/Correct\./gi, 'Correcte.'],
    [/Not checked yet\./gi, 'Pas encore vérifiée.'],
    [/The grader accepted this answer\./gi, 'Le correcteur a accepté cette réponse.'],
    [/Specific issue:\s*output mismatch\./gi, 'Problème précis : la sortie ne correspond pas.'],
    [/Specific issue:\s*/gi, 'Problème précis : '],
    [/but (?:your|the) code produced/gi, 'mais votre code a produit'],
    [/defines the function the grader will call/gi, 'définit la fonction que le correcteur appellera'],
    [/prints output to the console/gi, 'affiche une sortie dans la console'],
    [/The code is close only if the approach is right, but the final value does not match what the problem requires\./gi, 'Le code est proche uniquement si l\'approche est correcte, mais la valeur finale ne correspond pas à ce que demande le problème.'],
    [/Fix the line that creates the final/gi, 'Corrigez la ligne qui produit la valeur finale'],
    [/or printed output/gi, 'ou la sortie affichée'],
    [/defines a function\./gi, 'définit une fonction.'],
    [/Python records the function first; the indented body runs later when the function is called\./gi, 'Python enregistre d\'abord la fonction ; son bloc indenté s\'exécute ensuite lorsque la fonction est appelée.'],
    [/displays text in the output panel\./gi, 'affiche du texte dans le panneau de sortie.'],
    [/It does not return that value to the grader unless the problem is output-based\./gi, 'Cette instruction ne renvoie pas cette valeur au correcteur, sauf si le problème vérifie directement la sortie.'],
    [/builds the function boundary and defines what the grader can call/gi, 'définit la fonction et ce que le correcteur peut appeler'],
    [/sends the final value back to the grader/gi, 'renvoie la valeur finale au correcteur'],
    [/Function workflow note:/gi, 'Remarque sur le déroulement de la fonction :'],
    [/execution starts outside the function, but the function body only runs when the grader or script calls it\./gi, 'l\'exécution commence hors de la fonction, mais son corps ne s\'exécute que lorsque le correcteur ou le script l\'appelle.'],
    [/Python loads imports first, records function definitions next, then runs the function body only when the grader or script calls it\./gi, 'Python charge d\'abord les imports, enregistre ensuite les définitions de fonctions, puis exécute le corps d\'une fonction uniquement lorsque le correcteur ou le script l\'appelle.'],
    [/Intermediate assignments prepare values; the final return\/output is what decides whether the answer passes\./gi, 'Les affectations intermédiaires préparent les valeurs ; le retour ou la sortie finale détermine si la réponse réussit.'],
    [/The grader expected/gi, 'Le correcteur attendait'],
    [/your code produced/gi, 'votre code a produit'],
    [/The function returned None, which usually means it ended without a return statement\./gi, 'La fonction a renvoyé None, ce qui signifie généralement qu\'elle s\'est terminée sans instruction return.'],
    [/Trace that exact case by hand and make the function return the expected value\./gi, 'Suivez ce cas précis étape par étape et faites renvoyer la valeur attendue par la fonction.'],
    [/Replace print-only logic with return, or add a return on every branch\./gi, 'Remplacez la logique qui utilise seulement print par return, ou ajoutez un return dans chaque branche.'],
    [/The answer did not satisfy the tests/gi, 'La réponse n\'a pas satisfait les tests'],
    [/The code did not produce a valid final answer because it crashed with/gi, 'Le code n\'a pas produit de réponse finale valide car il a échoué avec'],
    [/Press RUN first/gi, 'Appuyez d\'abord sur EXÉCUTER'],
    [/then rerun/gi, 'puis relancez le code'],
    [/User output/gi, 'Sortie utilisateur'],
    [/Grader message/gi, 'Message du correcteur'],
    [/expected/gi, 'attendu'],
    [/but the user output\/result was/gi, 'mais la sortie ou le résultat de l\'utilisateur était'],
    [/but the Sortie utilisateur\/result was/gi, 'mais la sortie ou le résultat de l\'utilisateur était'],
    [/This means the final/gi, 'Cela signifie que la valeur finale'],
    [/\bline (\d+)\b/gi, 'ligne $1'],
    [/\bstep (\d+)\b/gi, 'étape $1'],
    [/final `return` value/gi, 'valeur finale de `return`'],
    [/final value/gi, 'valeur finale'],
    [/matched the tests for this problem/gi, 'correspondait aux tests de ce problème'],
    [/Fix that runtime error first, then check the output again\./gi, 'Corrigez d\'abord cette erreur d\'exécution, puis vérifiez à nouveau la sortie.'],
    [/The editor is empty/gi, 'L\'éditeur est vide'],
    [/Write your Python code before pressing AI Review\./gi, 'Écrivez votre code Python avant d\'appuyer sur Révision IA.'],
    [/This code uses straightforward Python statements\./gi, 'Ce code utilise des instructions Python simples.'],
    [/Read it from top to bottom/gi, 'Lisez-le de haut en bas'],
    [/assignments prepare values/gi, 'les affectations préparent les valeurs'],
    [/expressions compute results/gi, 'les expressions calculent les résultats'],
    [/is what the app checks/gi, 'est ce que l\'application vérifie'],
    [/This problem/gi, 'Ce problème'],
    [/For this problem/gi, 'Pour ce problème'],
    [/For this task/gi, 'Pour cet exercice'],
    [/Task breakdown/gi, 'Décomposition de l\'exercice'],
    [/Important details/gi, 'Détails importants'],
    [/Method or syntax/gi, 'Méthode ou syntaxe'],
    [/Current output check/gi, 'Vérification de la sortie actuelle'],
    [/Your code context/gi, 'Contexte de votre code'],
    [/Simple next step/gi, 'Prochaine étape simple'],
    [/Variable names do not matter/gi, 'Les noms de variables n\'ont pas d\'importance'],
    [/Match the function parameter to the prompt/gi, 'Faites correspondre le paramètre de la fonction à l\'énoncé'],
    [/It depends/gi, 'Cela dépend'],
    [/Yes\b/gi, 'Oui'],
    [/No\b/gi, 'Non'],
    [/A list is an ordered, mutable collection of items\./gi, 'Une liste est une collection ordonnée et modifiable d\'éléments.'],
    [/Items can be any type\./gi, 'Les éléments peuvent être de n\'importe quel type.'],
    [/Lists use square brackets and support indexing, slicing, and methods like/gi, 'Les listes utilisent des crochets et prennent en charge l\'indexation, le découpage et des méthodes comme'],
    [/Creates a list from an iterable, or an empty list if no argument\./gi, 'Crée une liste à partir d\'un itérable, ou une liste vide si aucun argument n\'est fourni.'],
    [/A dictionary stores key-value pairs\./gi, 'Un dictionnaire stocke des paires clé-valeur.'],
    [/Keys are unique and must be immutable/gi, 'Les clés sont uniques et doivent être immuables'],
    [/Values can be anything\./gi, 'Les valeurs peuvent être de n\'importe quel type.'],
    [/Access values via/gi, 'Accédez aux valeurs avec'],
    [/Insertion-ordered since Python 3\.7\./gi, 'L\'ordre d\'insertion est conservé depuis Python 3.7.'],
    [/A tuple is an ordered, immutable sequence\./gi, 'Un tuple est une séquence ordonnée et immuable.'],
    [/Once created it cannot change\./gi, 'Une fois créé, il ne peut plus être modifié.'],
    [/Use for fixed data that should not be modified\./gi, 'Utilisez-le pour des données fixes qui ne doivent pas être modifiées.'],
    [/A set is an unordered collection of unique, immutable items\./gi, 'Un ensemble est une collection non ordonnée d\'éléments uniques et immuables.'],
    [/Duplicates are automatically removed\./gi, 'Les doublons sont supprimés automatiquement.'],
    [/Supports math operations/gi, 'Prend en charge les opérations ensemblistes'],
    [/A string is an immutable sequence of Unicode characters\./gi, 'Une chaîne est une séquence immuable de caractères Unicode.'],
    [/Can use single or double quotes\./gi, 'Elle peut utiliser des guillemets simples ou doubles.'],
    [/Supports methods like/gi, 'Prend en charge des méthodes comme'],
    [/Returns a copy/gi, 'Renvoie une copie'],
    [/returns/gi, 'renvoie'],
    [/is now/gi, 'vaut maintenant'],
    [/same as/gi, 'identique à'],
    [/last item/gi, 'dernier élément'],
    [/first item/gi, 'premier élément'],
    [/Returns True if/gi, 'Renvoie True si'],
    [/Returns False if/gi, 'Renvoie False si'],
    [/Returns the/gi, 'Renvoie le'],
    [/Returns/gi, 'Renvoie'],
    [/Modifies in place/gi, 'Modifie l\'objet sur place'],
    [/does not modify the original/gi, 'ne modifie pas l\'objet d\'origine'],
    [/original object/gi, 'objet d\'origine'],
    [/Common mistake/gi, 'Erreur fréquente'],
    [/Example/gi, 'Exemple'],
    [/Examples/gi, 'Exemples'],
    [/How it works/gi, 'Fonctionnement'],
    [/Practical rule/gi, 'Règle pratique'],
    [/Use the method when you want to change the original object\./gi, 'Utilisez la méthode lorsque vous voulez modifier l\'objet d\'origine.'],
    [/Use the built-in function when you want a new result and want to keep the original unchanged\./gi, 'Utilisez la fonction intégrée lorsque vous voulez un nouveau résultat sans modifier l\'objet d\'origine.'],
    [/The important rule/gi, 'La règle importante'],
    [/The core rule/gi, 'La règle principale'],
    [/returns None/gi, 'renvoie None'],
    [/return value/gi, 'valeur de retour'],
    [/one value at a time/gi, 'une valeur à la fois'],
    [/at the end of the list/gi, 'à la fin de la liste'],
    [/at the beginning/gi, 'au début'],
    [/at the end/gi, 'à la fin'],
    [/in the list/gi, 'dans la liste'],
    [/in the string/gi, 'dans la chaîne'],
    [/if it exists/gi, 'si elle existe'],
    [/if not found/gi, 'si elle est introuvable'],
    [/all items/gi, 'tous les éléments'],
    [/each item/gi, 'chaque élément'],
    [/the function/gi, 'la fonction'],
    [/the method/gi, 'la méthode'],
    [/the string/gi, 'la chaîne'],
    [/the list/gi, 'la liste'],
    [/the dictionary/gi, 'le dictionnaire'],
    [/the set/gi, 'l\'ensemble'],
    [/the tuple/gi, 'le tuple'],
    [/the value/gi, 'la valeur'],
    [/\bvalue\b/gi, 'valeur'],
    [/\bresult was\b/gi, 'le résultat était'],
    [/the result/gi, 'le résultat'],
    [/the output/gi, 'la sortie'],
    [/the code/gi, 'le code'],
    [/the problem/gi, 'le problème'],
    [/is used to/gi, 'sert à'],
    [/You call it on/gi, 'Vous l\'appelez sur'],
    [/You can use/gi, 'Vous pouvez utiliser'],
    [/Use /gi, 'Utilisez '],
];

const localizePlainFrench = (value: string) => PHRASE_REPLACEMENTS.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    value,
);

const findPythonCommentIndex = (line: string): number => {
    let quote = '';
    let escaped = false;
    for (let index = 0; index < line.length; index += 1) {
        const char = line[index];
        if (escaped) {
            escaped = false;
            continue;
        }
        if (char === '\\') {
            escaped = true;
            continue;
        }
        if (quote) {
            if (char === quote) quote = '';
            continue;
        }
        if (char === '"' || char === "'") {
            quote = char;
            continue;
        }
        if (char === '#') return index;
    }
    return -1;
};

export const localizeAiText = (text: string, language: AiLanguage): string => {
    if (language !== 'fr' || !text) return text;

    // Python snippets and identifiers must never be translated.
    return text
        .split(/(```[\s\S]*?```|`[^`\n]+`)/g)
        .map(part => {
            if (!part.startsWith('`')) return localizePlainFrench(part);
            if (!part.startsWith('```')) return part;
            return part.split('\n').map(line => {
                const commentIndex = findPythonCommentIndex(line);
                if (commentIndex < 0) return line;
                return `${line.slice(0, commentIndex + 1)}${localizePlainFrench(line.slice(commentIndex + 1))}`;
            }).join('\n');
        })
        .join('');
};

export const aiLanguageInstruction = (language: AiLanguage): string => language === 'fr'
    ? 'Réponds entièrement en français. Conserve uniquement le code Python, les identifiants, les mots-clés Python et les sorties littérales dans leur forme originale.'
    : 'Answer entirely in English.';
