#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specs = [];
const py = value => {
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (value === null) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(py).join(', ')}]`;
  if (typeof value === 'object') return `{${Object.entries(value).map(([key, item]) => `${py(key)}: ${py(item)}`).join(', ')}}`;
  return String(value);
};
const add = (name, params, en, fr, body, cases, level, focus) => specs.push({
  name, params, en, fr, body: body.trim(), cases, level, focus,
});

// Easy: counters, accumulators, digits, strings, and basic list traversal.
const sequenceTasks = [
  ['count_up', 'n', 'return the integers from 1 through `n`', 'retourne les entiers de 1 à `n`', 'value = 1\n    result = []\n    while value <= n:\n        result.append(value)\n        value += 1', [[[5], [1,2,3,4,5]], [[1], [1]], [[0], []]]],
  ['count_down', 'n', 'return the integers from `n` down to 0', 'retourne les entiers de `n` jusqu’à 0', 'result = []\n    while n >= 0:\n        result.append(n)\n        n -= 1', [[[3], [3,2,1,0]], [[0], [0]], [[5], [5,4,3,2,1,0]]]],
  ['even_numbers', 'limit', 'return all even integers from 0 through `limit`', 'retourne tous les entiers pairs de 0 à `limit`', 'value = 0\n    result = []\n    while value <= limit:\n        result.append(value)\n        value += 2', [[[7], [0,2,4,6]], [[0], [0]], [[10], [0,2,4,6,8,10]]]],
  ['odd_numbers', 'limit', 'return all odd integers from 1 through `limit`', 'retourne tous les entiers impairs de 1 à `limit`', 'value = 1\n    result = []\n    while value <= limit:\n        result.append(value)\n        value += 2', [[[8], [1,3,5,7]], [[1], [1]], [[0], []]]],
  ['multiples_up_to', 'number, limit', 'return positive multiples of `number` that do not exceed `limit`', 'retourne les multiples positifs de `number` qui ne dépassent pas `limit`', 'value = number\n    result = []\n    while value <= limit:\n        result.append(value)\n        value += number\n    return result', [[[3,10], [3,6,9]], [[5,5], [5]], [[4,3], []]]],
  ['squares_to_n', 'n', 'return the squares of the integers from 1 through `n`', 'retourne les carrés des entiers de 1 à `n`', 'value = 1\n    result = []\n    while value <= n:\n        result.append(value ** 2)\n        value += 1', [[[4], [1,4,9,16]], [[1], [1]], [[0], []]]],
  ['cubes_to_n', 'n', 'return the cubes of the integers from 1 through `n`', 'retourne les cubes des entiers de 1 à `n`', 'value = 1\n    result = []\n    while value <= n:\n        result.append(value ** 3)\n        value += 1', [[[3], [1,8,27]], [[1], [1]], [[0], []]]],
  ['powers_of_two', 'limit', 'return every power of two not greater than `limit`, starting at 1', 'retourne chaque puissance de deux ne dépassant pas `limit`, en commençant par 1', 'value = 1\n    result = []\n    while value <= limit:\n        result.append(value)\n        value *= 2', [[[10], [1,2,4,8]], [[1], [1]], [[0], []]]],
  ['arithmetic_sequence', 'start, step, count', 'return `count` terms of an arithmetic sequence', 'retourne `count` termes d’une suite arithmétique', 'result = []\n    while len(result) < count:\n        result.append(start)\n        start += step', [[[2,3,4], [2,5,8,11]], [[5,-2,3], [5,3,1]], [[1,4,0], []]]],
  ['count_down_by_step', 'start, step', 'count down from `start` to 0 using a positive `step`', 'compte à rebours de `start` à 0 avec un `step` positif', 'result = []\n    while start >= 0:\n        result.append(start)\n        start -= step', [[[10,3], [10,7,4,1]], [[4,2], [4,2,0]], [[1,5], [1]]]],
];
for (const [name, params, en, fr, body, cases] of sequenceTasks) add(name, params, en, fr, body, cases, 'Easy', 'counter update and loop boundary');

const accumulatorTasks = [
  ['sum_to_n','n','return the sum of the integers from 1 through `n`','retourne la somme des entiers de 1 à `n`','value = 1\n    total = 0\n    while value <= n:\n        total += value\n        value += 1',[[[5],15],[[1],1],[[0],0]]],
  ['factorial_while','n','return `n!` for a non-negative integer','retourne `n!` pour un entier non négatif','result = 1\n    while n > 1:\n        result *= n\n        n -= 1',[[[5],120],[[0],1],[[3],6]]],
  ['sum_squares','n','return the sum of the squares from 1 through `n`','retourne la somme des carrés de 1 à `n`','value = 1\n    total = 0\n    while value <= n:\n        total += value ** 2\n        value += 1',[[[3],14],[[1],1],[[0],0]]],
  ['sum_cubes','n','return the sum of the cubes from 1 through `n`','retourne la somme des cubes de 1 à `n`','value = 1\n    total = 0\n    while value <= n:\n        total += value ** 3\n        value += 1',[[[3],36],[[2],9],[[0],0]]],
  ['count_multiples','limit, divisor','count positive integers up to `limit` divisible by `divisor`','compte les entiers positifs jusqu’à `limit` divisibles par `divisor`','value = divisor\n    count = 0\n    while value <= limit:\n        count += 1\n        value += divisor',[[[10,3],3],[[12,4],3],[[2,5],0]]],
  ['sum_even_to_n','n','return the sum of even integers from 0 through `n`','retourne la somme des entiers pairs de 0 à `n`','value = 0\n    total = 0\n    while value <= n:\n        total += value\n        value += 2',[[[6],12],[[1],0],[[10],30]]],
  ['sum_odd_to_n','n','return the sum of odd integers from 1 through `n`','retourne la somme des entiers impairs de 1 à `n`','value = 1\n    total = 0\n    while value <= n:\n        total += value\n        value += 2',[[[7],16],[[1],1],[[0],0]]],
  ['product_range','start, stop','multiply all integers from `start` through `stop`','multiplie tous les entiers de `start` à `stop`','result = 1\n    while start <= stop:\n        result *= start\n        start += 1',[[[2,4],24],[[5,5],5],[[3,2],1]]],
  ['steps_to_reach','start, target, increment','count additions of `increment` needed to reach or pass `target`','compte les additions de `increment` nécessaires pour atteindre ou dépasser `target`','steps = 0\n    while start < target:\n        start += increment\n        steps += 1',[[[0,10,3],4],[[5,5,2],0],[[2,9,1],7]]],
  ['integer_power','base, exponent','calculate `base` raised to a non-negative `exponent` using repeated multiplication','calcule `base` à la puissance `exponent` non négative par multiplications répétées','result = 1\n    while exponent > 0:\n        result *= base\n        exponent -= 1',[[[2,5],32],[[7,0],1],[[-3,3],-27]]],
];
for (const [name, params, en, fr, body, cases] of accumulatorTasks) add(name, params, en, fr, body, cases, 'Easy', 'accumulator initialization and update');

const digitTasks = [
 ['digit_count','number','count the decimal digits in a non-negative integer','compte les chiffres décimaux d’un entier non négatif','if number == 0:\n        return 1\n    count = 0\n    while number > 0:\n        count += 1\n        number //= 10',[[[0],1],[[482],3],[[10000],5]]],
 ['digit_sum','number','return the sum of the decimal digits','retourne la somme des chiffres décimaux','number = abs(number)\n    total = 0\n    while number > 0:\n        total += number % 10\n        number //= 10',[[[482],14],[[-91],10],[[0],0]]],
 ['digit_product','number','return the product of the decimal digits, with 0 returning 0','retourne le produit des chiffres décimaux, avec 0 retournant 0','number = abs(number)\n    if number == 0:\n        return 0\n    result = 1\n    while number > 0:\n        result *= number % 10\n        number //= 10',[[[234],24],[[105],0],[[7],7]]],
 ['reverse_integer','number','reverse the decimal digits of a non-negative integer','inverse les chiffres décimaux d’un entier non négatif','result = 0\n    while number > 0:\n        result = result * 10 + number % 10\n        number //= 10',[[[1234],4321],[[120],21],[[0],0]]],
 ['count_zero_digits','number','count how many zero digits appear in a non-negative integer','compte le nombre de chiffres zéro dans un entier non négatif','if number == 0:\n        return 1\n    count = 0\n    while number > 0:\n        if number % 10 == 0:\n            count += 1\n        number //= 10',[[[1002],2],[[7],0],[[0],1]]],
 ['count_specific_digit','number, digit','count occurrences of `digit` in a non-negative integer','compte les occurrences de `digit` dans un entier non négatif','if number == 0:\n        return 1 if digit == 0 else 0\n    count = 0\n    while number > 0:\n        if number % 10 == digit:\n            count += 1\n        number //= 10',[[[14424,4],3],[[123,8],0],[[0,0],1]]],
 ['largest_digit','number','return the largest decimal digit','retourne le plus grand chiffre décimal','largest = 0\n    while number > 0:\n        digit = number % 10\n        if digit > largest:\n            largest = digit\n        number //= 10',[[[5824],8],[[0],0],[[111],1]]],
 ['smallest_digit','number','return the smallest decimal digit','retourne le plus petit chiffre décimal','if number == 0:\n        return 0\n    smallest = 9\n    while number > 0:\n        digit = number % 10\n        if digit < smallest:\n            smallest = digit\n        number //= 10',[[[5824],2],[[907],0],[[6],6]]],
 ['digital_root','number','repeatedly sum digits until one digit remains','additionne les chiffres à répétition jusqu’à obtenir un seul chiffre','number = abs(number)\n    while number >= 10:\n        total = 0\n        while number > 0:\n            total += number % 10\n            number //= 10\n        number = total',[[[9875],2],[[9],9],[[0],0]]],
 ['decimal_to_binary','number','return the binary digits of a non-negative integer as a string','retourne les chiffres binaires d’un entier non négatif sous forme de chaîne','if number == 0:\n        return "0"\n    result = ""\n    while number > 0:\n        result = str(number % 2) + result\n        number //= 2',[[[10],"1010"],[[1],"1"],[[0],"0"]]],
];
for (const [name, params, en, fr, body, cases] of digitTasks) add(name, params, en, fr, body, cases, specs.length < 30 ? 'Easy' : 'Intermediate', 'digit extraction with modulo and floor division');

const stringTasks = [
 ['reverse_text','text','return the string in reverse order','retourne la chaîne dans l’ordre inverse','index = len(text) - 1\n    result = ""\n    while index >= 0:\n        result += text[index]\n        index -= 1',[[['python'],'nohtyp'],[['a'],'a'],[[''],'']]],
 ['count_vowels_while','text','count vowels, ignoring letter case','compte les voyelles sans tenir compte de la casse','index = 0\n    count = 0\n    while index < len(text):\n        if text[index].lower() in "aeiou":\n            count += 1\n        index += 1',[[['Hello'],2],[['rhythm'],0],[['AEIOU'],5]]],
 ['count_consonants_while','text','count alphabetic consonants, ignoring case','compte les consonnes alphabétiques sans tenir compte de la casse','index = 0\n    count = 0\n    while index < len(text):\n        char = text[index].lower()\n        if char.isalpha() and char not in "aeiou":\n            count += 1\n        index += 1',[[['Hello!'],3],[['AEIOU'],0],[['sky 2'],3]]],
 ['remove_vowels_while','text','return the text without vowels','retourne le texte sans voyelles','index = 0\n    result = ""\n    while index < len(text):\n        if text[index].lower() not in "aeiou":\n            result += text[index]\n        index += 1',[[['hello'],'hll'],[['AEIOUxyz'],'xyz'],[[''],'']]],
 ['remove_spaces_while','text','return the text without space characters','retourne le texte sans caractères espace','index = 0\n    result = ""\n    while index < len(text):\n        if text[index] != " ":\n            result += text[index]\n        index += 1',[[['a b c'],'abc'],[[' no spaces '],'nospaces'],[[''],'']]],
 ['count_character_while','text, target','count exact occurrences of `target` in `text`','compte les occurrences exactes de `target` dans `text`','index = 0\n    count = 0\n    while index < len(text):\n        if text[index] == target:\n            count += 1\n        index += 1',[[['banana','a'],3],[['Mississippi','s'],4],[['abc','z'],0]]],
 ['first_character_index','text, target','return the first index of `target`, or -1 when absent','retourne le premier indice de `target`, ou -1 s’il est absent','index = 0\n    while index < len(text):\n        if text[index] == target:\n            return index\n        index += 1\n    return -1',[[['banana','n'],2],[['abc','z'],-1],[['aaa','a'],0]]],
 ['last_character_index','text, target','return the last index of `target`, or -1 when absent','retourne le dernier indice de `target`, ou -1 s’il est absent','index = len(text) - 1\n    while index >= 0:\n        if text[index] == target:\n            return index\n        index -= 1\n    return -1',[[['banana','a'],5],[['abc','z'],-1],[['aaa','a'],2]]],
 ['is_palindrome_while','text','return True when the string reads the same backward','retourne True quand la chaîne se lit pareil à l’envers','left = 0\n    right = len(text) - 1\n    while left < right:\n        if text[left] != text[right]:\n            return False\n        left += 1\n        right -= 1\n    return True',[[['level'],true],[['python'],false],[[''],true]]],
 ['every_other_character','text','return characters at indexes 0, 2, 4, and so on','retourne les caractères aux indices 0, 2, 4, etc.','index = 0\n    result = ""\n    while index < len(text):\n        result += text[index]\n        index += 2',[[['abcdef'],'ace'],[['python'],'pto'],[[''],'']]],
];
for (const [name, params, en, fr, body, cases] of stringTasks) add(name, params, en, fr, body, cases, 'Easy', 'index-controlled string traversal');

const listTasks = [
 ['sum_list_while','numbers','return the sum of all list values','retourne la somme de toutes les valeurs de la liste','index = 0\n    total = 0\n    while index < len(numbers):\n        total += numbers[index]\n        index += 1',[[[[1,2,3]],6],[[[-2,5]],3],[[[]],0]]],
 ['product_list_while','numbers','return the product of all list values','retourne le produit de toutes les valeurs de la liste','index = 0\n    result = 1\n    while index < len(numbers):\n        result *= numbers[index]\n        index += 1',[[[[2,3,4]],24],[[[-2,5]],-10],[[[]],1]]],
 ['minimum_while','numbers','return the smallest value in a non-empty list','retourne la plus petite valeur d’une liste non vide','index = 1\n    result = numbers[0]\n    while index < len(numbers):\n        if numbers[index] < result:\n            result = numbers[index]\n        index += 1',[[[[4,1,7]],1],[[[-3,-8,-1]],-8],[[[5]],5]]],
 ['maximum_while','numbers','return the largest value in a non-empty list','retourne la plus grande valeur d’une liste non vide','index = 1\n    result = numbers[0]\n    while index < len(numbers):\n        if numbers[index] > result:\n            result = numbers[index]\n        index += 1',[[[[4,1,7]],7],[[[-3,-8,-1]],-1],[[[5]],5]]],
 ['count_positive_while','numbers','count values greater than zero','compte les valeurs supérieures à zéro','index = 0\n    count = 0\n    while index < len(numbers):\n        if numbers[index] > 0:\n            count += 1\n        index += 1',[[[[-1,0,2,4]],2],[[[-3]],0],[[[1,2]],2]]],
 ['negative_values_while','numbers','return a new list containing only negative values','retourne une nouvelle liste contenant uniquement les valeurs négatives','index = 0\n    result = []\n    while index < len(numbers):\n        if numbers[index] < 0:\n            result.append(numbers[index])\n        index += 1',[[[[-1,0,2,-4]],[-1,-4]],[[[1,2]],[]],[[[-3]],[-3]]]],
 ['square_values_while','numbers','return a list containing each value squared','retourne une liste contenant chaque valeur au carré','index = 0\n    result = []\n    while index < len(numbers):\n        result.append(numbers[index] ** 2)\n        index += 1',[[[[1,2,3]],[1,4,9]],[[[-2,0]],[4,0]],[[[]],[]]]],
 ['reverse_list_while','items','return a reversed copy of the list','retourne une copie inversée de la liste','index = len(items) - 1\n    result = []\n    while index >= 0:\n        result.append(items[index])\n        index -= 1',[[[[1,2,3]],[3,2,1]],[[['a']],['a']],[[[]],[]]]],
 ['running_totals_while','numbers','return cumulative totals after each item','retourne les totaux cumulés après chaque élément','index = 0\n    total = 0\n    result = []\n    while index < len(numbers):\n        total += numbers[index]\n        result.append(total)\n        index += 1',[[[[1,2,3]],[1,3,6]],[[[5,-2]],[5,3]],[[[]],[]]]],
 ['unique_in_order_while','items','remove duplicates while preserving first-seen order','supprime les doublons en conservant l’ordre de première apparition','index = 0\n    result = []\n    while index < len(items):\n        if items[index] not in result:\n            result.append(items[index])\n        index += 1',[[[[1,2,1,3]],[1,2,3]],[[['a','a']],['a']],[[[]],[]]]],
];
for (const [name, params, en, fr, body, cases] of listTasks) add(name, params, en, fr, body, cases, specs.length < 35 ? 'Easy' : 'Intermediate', 'index-controlled list traversal');

const advancedTasks = [
 ['first_target_index','items, target','return the first index containing `target`, or -1','retourne le premier indice contenant `target`, ou -1','index = 0\n    while index < len(items) and items[index] != target:\n        index += 1\n    return index if index < len(items) else -1',[[[[3,8,8],8],1],[[[1,2],9],-1],[[[],1],-1]]],
 ['first_negative_index','numbers','return the index of the first negative value, or -1','retourne l’indice de la première valeur négative, ou -1','index = 0\n    while index < len(numbers) and numbers[index] >= 0:\n        index += 1\n    return index if index < len(numbers) else -1',[[[[2,0,-3,4]],2],[[[1,2]],-1],[[[-1]],0]]],
 ['prefix_before_marker','items, marker','return items before the first marker','retourne les éléments avant le premier marqueur','index = 0\n    result = []\n    while index < len(items) and items[index] != marker:\n        result.append(items[index])\n        index += 1',[[[[1,2,0,3],0],[1,2]],[[['a','b'],'x'],['a','b']],[[[9],9],[]]]],
 ['take_while_positive','numbers','return the leading values while they remain positive','retourne les premières valeurs tant qu’elles restent positives','index = 0\n    result = []\n    while index < len(numbers) and numbers[index] > 0:\n        result.append(numbers[index])\n        index += 1',[[[[2,3,0,4]],[2,3]],[[[-1,2]],[]],[[[1,2]],[1,2]]]],
 ['sum_until_limit','numbers, limit','add values from the start without letting the total exceed `limit`','additionne les valeurs du début sans laisser le total dépasser `limit`','index = 0\n    total = 0\n    while index < len(numbers) and total + numbers[index] <= limit:\n        total += numbers[index]\n        index += 1',[[[[2,3,5],6],5],[[[4,1],3],0],[[[1,2],10],3]]],
 ['drop_leading_zeros','numbers','return a copy without leading zeros','retourne une copie sans les zéros initiaux','index = 0\n    while index < len(numbers) and numbers[index] == 0:\n        index += 1\n    return numbers[index:]',[[[[0,0,3,0]],[3,0]],[[[0,0]],[]],[[[2,0]],[2,0]]]],
 ['common_prefix','left, right','return the common starting text of two strings','retourne le début commun de deux chaînes','index = 0\n    while index < len(left) and index < len(right) and left[index] == right[index]:\n        index += 1\n    return left[:index]',[[['flower','flow'],'flow'],[['cat','dog'],''],[['same','same'],'same']]],
 ['count_substring','text, pattern','count overlapping occurrences of `pattern`','compte les occurrences chevauchantes de `pattern`','if pattern == "":\n        return 0\n    index = 0\n    count = 0\n    while index <= len(text) - len(pattern):\n        if text[index:index + len(pattern)] == pattern:\n            count += 1\n        index += 1',[[['aaaa','aa'],3],[['banana','ana'],2],[['abc','z'],0]]],
 ['manual_startswith','text, prefix','check whether `text` starts with `prefix` without startswith()','vérifie si `text` commence par `prefix` sans startswith()','if len(prefix) > len(text):\n        return False\n    index = 0\n    while index < len(prefix):\n        if text[index] != prefix[index]:\n            return False\n        index += 1\n    return True',[[['python','py'],true],[['cat','car'],false],[['a',''],true]]],
 ['manual_split','text, delimiter','split a string on a one-character delimiter without split()','divise une chaîne sur un délimiteur d’un caractère sans split()','parts = []\n    current = ""\n    index = 0\n    while index < len(text):\n        if text[index] == delimiter:\n            parts.append(current)\n            current = ""\n        else:\n            current += text[index]\n        index += 1\n    parts.append(current)\n    return parts',[[['a,b,c',','],['a','b','c']],[['one',';'],['one']],[['a::b',':'],['a','','b']]]],
 ['flatten_nested','groups','flatten a list of lists using nested while loops','aplatit une liste de listes avec des boucles while imbriquées','result = []\n    outer = 0\n    while outer < len(groups):\n        inner = 0\n        while inner < len(groups[outer]):\n            result.append(groups[outer][inner])\n            inner += 1\n        outer += 1',[[[[[1,2],[3]]],[1,2,3]],[[[[],[4]]],[4]],[[[]],[]]]],
 ['matrix_total','matrix','sum every number in a matrix using nested while loops','additionne tous les nombres d’une matrice avec des boucles while imbriquées','total = 0\n    row = 0\n    while row < len(matrix):\n        col = 0\n        while col < len(matrix[row]):\n            total += matrix[row][col]\n            col += 1\n        row += 1',[[[[[1,2],[3,4]]],10],[[[[],[5]]],5],[[[]],0]]],
 ['matrix_row_totals','matrix','return the sum of each matrix row','retourne la somme de chaque ligne d’une matrice','result = []\n    row = 0\n    while row < len(matrix):\n        col = 0\n        total = 0\n        while col < len(matrix[row]):\n            total += matrix[row][col]\n            col += 1\n        result.append(total)\n        row += 1',[[[[[1,2],[3,4]]],[3,7]],[[[[],[5]]],[0,5]],[[[]],[]]]],
 ['transpose_matrix','matrix','transpose a rectangular matrix','transpose une matrice rectangulaire','if not matrix:\n        return []\n    result = []\n    col = 0\n    while col < len(matrix[0]):\n        new_row = []\n        row = 0\n        while row < len(matrix):\n            new_row.append(matrix[row][col])\n            row += 1\n        result.append(new_row)\n        col += 1',[[[[[1,2],[3,4]]],[[1,3],[2,4]]],[[[[1,2,3]]],[[1],[2],[3]]],[[[]],[]]]],
 ['merge_alternating','left, right','alternate items from two lists and append any remainder','alterne les éléments de deux listes puis ajoute le reste','result = []\n    index = 0\n    while index < len(left) or index < len(right):\n        if index < len(left): result.append(left[index])\n        if index < len(right): result.append(right[index])\n        index += 1',[[[[1,2],['a','b']],[1,'a',2,'b']],[[[1,2,3],['x']],[1,'x',2,3]],[[[],[4]],[4]]]],
 ['chunk_list','items, size','split a list into consecutive chunks of `size`','divise une liste en groupes consécutifs de taille `size`','result = []\n    index = 0\n    while index < len(items):\n        result.append(items[index:index + size])\n        index += size',[[[[1,2,3,4,5],2],[[1,2],[3,4],[5]]],[[['a','b'],3],[['a','b']]],[[[],2],[]]]],
 ['rotate_left_while','items, steps','rotate a list left by `steps` positions','fait pivoter une liste vers la gauche de `steps` positions','if not items:\n        return []\n    result = items[:]\n    steps %= len(result)\n    while steps > 0:\n        result.append(result.pop(0))\n        steps -= 1',[[[[1,2,3,4],1],[2,3,4,1]],[[['a','b','c'],4],['b','c','a']],[[[],2],[]]]],
 ['sliding_sums','numbers, width','return sums of every consecutive window of `width`','retourne les sommes de chaque fenêtre consécutive de largeur `width`','result = []\n    start = 0\n    while start + width <= len(numbers):\n        index = start\n        total = 0\n        while index < start + width:\n            total += numbers[index]\n            index += 1\n        result.append(total)\n        start += 1',[[[[1,2,3,4],2],[3,5,7]],[[[5,1,2],3],[8]],[[[1],2],[]]]],
 ['frequency_table','items','return a dictionary counting each item','retourne un dictionnaire comptant chaque élément','counts = {}\n    index = 0\n    while index < len(items):\n        item = items[index]\n        counts[item] = counts.get(item, 0) + 1\n        index += 1',[[[[1,2,1]],{1:2,2:1}],[[['a','a']],{a:2}],[[[]],{}]]],
 ['longest_word_while','words','return the first longest word','retourne le premier mot le plus long','if not words: return ""\n    longest = words[0]\n    index = 1\n    while index < len(words):\n        if len(words[index]) > len(longest): longest = words[index]\n        index += 1\n    return longest',[[[['cat','python','code']],'python'],[[['same','size']],'same'],[[[]],'']]],
 ['gcd_while','a, b','find the greatest common divisor using Euclid’s algorithm','trouve le plus grand diviseur commun avec l’algorithme d’Euclide','a, b = abs(a), abs(b)\n    while b != 0:\n        a, b = b, a % b\n    return a',[[[48,18],6],[[7,5],1],[[0,9],9]]],
 ['lcm_while','a, b','find the least common multiple by testing multiples','trouve le plus petit multiple commun en testant les multiples','if a == 0 or b == 0: return 0\n    candidate = max(abs(a), abs(b))\n    while candidate % a != 0 or candidate % b != 0:\n        candidate += 1\n    return candidate',[[[4,6],12],[[5,7],35],[[0,3],0]]],
 ['is_prime_while','number','return True when `number` is prime','retourne True quand `number` est premier','if number < 2: return False\n    divisor = 2\n    while divisor * divisor <= number:\n        if number % divisor == 0: return False\n        divisor += 1\n    return True',[[[29],true],[[21],false],[[1],false]]],
 ['divisors_while','number','return all positive divisors in ascending order','retourne tous les diviseurs positifs dans l’ordre croissant','result = []\n    divisor = 1\n    while divisor <= number:\n        if number % divisor == 0: result.append(divisor)\n        divisor += 1',[[[12],[1,2,3,4,6,12]],[[1],[1]],[[7],[1,7]]]],
 ['prime_factors_while','number','return prime factors with repetitions','retourne les facteurs premiers avec répétitions','factors = []\n    divisor = 2\n    while divisor * divisor <= number:\n        while number % divisor == 0:\n            factors.append(divisor)\n            number //= divisor\n        divisor += 1\n    if number > 1: factors.append(number)\n    return factors',[[[60],[2,2,3,5]],[[13],[13]],[[1],[]]]],
 ['fibonacci_while','count','return the first `count` Fibonacci numbers','retourne les `count` premiers nombres de Fibonacci','result = []\n    a, b = 0, 1\n    while len(result) < count:\n        result.append(a)\n        a, b = b, a + b',[[[6],[0,1,1,2,3,5]],[[1],[0]],[[0],[]]]],
 ['collatz_steps','number','count steps needed for the Collatz sequence to reach 1','compte les étapes nécessaires pour que la suite de Collatz atteigne 1','steps = 0\n    while number != 1:\n        number = number // 2 if number % 2 == 0 else number * 3 + 1\n        steps += 1\n    return steps',[[[6],8],[[1],0],[[3],7]]],
 ['is_perfect_number','number','check whether a number equals the sum of its proper divisors','vérifie si un nombre égale la somme de ses diviseurs propres','if number < 2: return False\n    divisor = 1\n    total = 0\n    while divisor < number:\n        if number % divisor == 0: total += divisor\n        divisor += 1\n    return total == number',[[[6],true],[[28],true],[[12],false]]],
 ['is_armstrong_while','number','check whether a number equals the sum of its digits raised to its digit count','vérifie si un nombre égale la somme de ses chiffres élevés au nombre de chiffres','original = number\n    power = len(str(number))\n    total = 0\n    while number > 0:\n        total += (number % 10) ** power\n        number //= 10\n    return total == original',[[[153],true],[[9474],true],[[123],false]]],
 ['nth_prime_while','n','return the `n`th prime number','retourne le `n`ième nombre premier','candidate = 1\n    found = 0\n    while found < n:\n        candidate += 1\n        divisor = 2\n        prime = True\n        while divisor * divisor <= candidate:\n            if candidate % divisor == 0:\n                prime = False\n                break\n            divisor += 1\n        if prime: found += 1\n    return candidate',[[[1],2],[[5],11],[[10],29]]],
 ['bubble_sort_while','numbers','return an ascending bubble-sorted copy','retourne une copie triée en ordre croissant par tri à bulles','result = numbers[:]\n    end = len(result) - 1\n    while end > 0:\n        index = 0\n        while index < end:\n            if result[index] > result[index + 1]:\n                result[index], result[index + 1] = result[index + 1], result[index]\n            index += 1\n        end -= 1',[[[[3,1,2]],[1,2,3]],[[[-1,4,0]],[-1,0,4]],[[[]],[]]]],
 ['insertion_sort_while','numbers','return an ascending insertion-sorted copy','retourne une copie triée en ordre croissant par tri par insertion','result = numbers[:]\n    index = 1\n    while index < len(result):\n        value = result[index]\n        pos = index - 1\n        while pos >= 0 and result[pos] > value:\n            result[pos + 1] = result[pos]\n            pos -= 1\n        result[pos + 1] = value\n        index += 1',[[[[4,2,3,1]],[1,2,3,4]],[[[1]], [1]],[[[]],[]]]],
 ['binary_search_while','numbers, target','return the index of `target` in a sorted list, or -1','retourne l’indice de `target` dans une liste triée, ou -1','left = 0\n    right = len(numbers) - 1\n    while left <= right:\n        middle = (left + right) // 2\n        if numbers[middle] == target: return middle\n        if numbers[middle] < target: left = middle + 1\n        else: right = middle - 1\n    return -1',[[[[1,3,5,7],5],2],[[[2,4],3],-1],[[[9],9],0]]],
 ['merge_sorted_while','left, right','merge two sorted lists into one sorted list','fusionne deux listes triées en une seule liste triée','result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]: result.append(left[i]); i += 1\n        else: result.append(right[j]); j += 1\n    while i < len(left): result.append(left[i]); i += 1\n    while j < len(right): result.append(right[j]); j += 1',[[[[1,3],[2,4]],[1,2,3,4]],[[[],[1]],[1]],[[[2],[2]],[2,2]]]],
 ['longest_increasing_run','numbers','return the length of the longest contiguous strictly increasing run','retourne la longueur de la plus longue suite contiguë strictement croissante','if not numbers: return 0\n    best = current = 1\n    index = 1\n    while index < len(numbers):\n        current = current + 1 if numbers[index] > numbers[index - 1] else 1\n        if current > best: best = current\n        index += 1\n    return best',[[[[1,2,3,1,2]],3],[[[5,4]],1],[[[]],0]]],
 ['run_length_encode','text','compress consecutive characters as character-count pairs','compresse les caractères consécutifs en paires caractère-compte','if not text: return ""\n    result = ""\n    index = 0\n    while index < len(text):\n        end = index + 1\n        while end < len(text) and text[end] == text[index]: end += 1\n        result += text[index] + str(end - index)\n        index = end',[[['aaabbc'],'a3b2c1'],[['x'],'x1'],[[''],'']]],
 ['balanced_parentheses','text','check whether parentheses are balanced','vérifie si les parenthèses sont équilibrées','balance = 0\n    index = 0\n    while index < len(text):\n        if text[index] == "(": balance += 1\n        elif text[index] == ")":\n            balance -= 1\n            if balance < 0: return False\n        index += 1\n    return balance == 0',[[['(a(b))'],true],[['(()'],false],[[')('],false]]],
 ['remove_adjacent_duplicates','text','repeatedly remove adjacent equal characters using a stack','supprime les caractères égaux adjacents à l’aide d’une pile','stack = []\n    index = 0\n    while index < len(text):\n        if stack and stack[-1] == text[index]: stack.pop()\n        else: stack.append(text[index])\n        index += 1\n    return "".join(stack)',[[['abbaca'],'ca'],[['azxxzy'],'ay'],[['abc'],'abc']]],
 ['convert_base','number, base','convert a non-negative integer to base 2 through 16','convertit un entier non négatif en base 2 à 16','digits = "0123456789ABCDEF"\n    if number == 0: return "0"\n    result = ""\n    while number > 0:\n        result = digits[number % base] + result\n        number //= base',[[[31,16],'1F'],[[10,2],'1010'],[[0,8],'0']]],
 ['modular_power','base, exponent, modulus','calculate modular exponentiation efficiently','calcule efficacement une exponentiation modulaire','result = 1 % modulus\n    base %= modulus\n    while exponent > 0:\n        if exponent % 2 == 1: result = result * base % modulus\n        base = base * base % modulus\n        exponent //= 2',[[[2,10,1000],24],[[3,4,5],1],[[7,0,9],1]]],
 ['sqrt_approximation','number, tolerance','approximate a positive square root with Newton iteration','approxime une racine carrée positive avec l’itération de Newton','if number == 0: return 0.0\n    guess = number / 2\n    while abs(guess * guess - number) > tolerance:\n        guess = (guess + number / guess) / 2\n    return guess',[[[9,1e-8],3],[[2,1e-8],2**0.5],[[0,1e-8],0]]],
 ['happy_number','number','check whether repeated sums of squared digits reach 1','vérifie si les sommes répétées des carrés des chiffres atteignent 1','seen = set()\n    while number != 1 and number not in seen:\n        seen.add(number)\n        total = 0\n        while number > 0:\n            total += (number % 10) ** 2\n            number //= 10\n        number = total\n    return number == 1',[[[19],true],[[2],false],[[1],true]]],
 ['look_and_say','seed, rounds','apply the look-and-say transformation `rounds` times','applique la transformation « lire et dire » `rounds` fois','value = seed\n    while rounds > 0:\n        result = ""\n        index = 0\n        while index < len(value):\n            end = index + 1\n            while end < len(value) and value[end] == value[index]: end += 1\n            result += str(end - index) + value[index]\n            index = end\n        value = result\n        rounds -= 1\n    return value',[[['1',4],'111221'],[['21',1],'1211'],[['3',0],'3']]],
 ['longest_unique_substring','text','return the length of the longest substring without repeated characters','retourne la longueur de la plus longue sous-chaîne sans caractères répétés','last = {}\n    left = 0\n    right = 0\n    best = 0\n    while right < len(text):\n        char = text[right]\n        if char in last and last[char] >= left: left = last[char] + 1\n        last[char] = right\n        best = max(best, right - left + 1)\n        right += 1\n    return best',[[['abcabcbb'],3],[['bbbbb'],1],[[''],0]]],
 ['lower_bound_while','numbers, target','return the first index whose sorted value is at least `target`','retourne le premier indice dont la valeur triée est au moins `target`','left = 0\n    right = len(numbers)\n    while left < right:\n        middle = (left + right) // 2\n        if numbers[middle] < target: left = middle + 1\n        else: right = middle\n    return left',[[[[1,3,3,7],3],1],[[[1,4],2],1],[[[],5],0]]],
 ['upper_bound_while','numbers, target','return the first index whose sorted value is greater than `target`','retourne le premier indice dont la valeur triée est supérieure à `target`','left = 0\n    right = len(numbers)\n    while left < right:\n        middle = (left + right) // 2\n        if numbers[middle] <= target: left = middle + 1\n        else: right = middle\n    return left',[[[[1,3,3,7],3],3],[[[1,4],4],2],[[[],5],0]]],
 ['second_largest_distinct','numbers','return the second-largest distinct value, or None','retourne la deuxième plus grande valeur distincte, ou None','largest = None\n    second = None\n    index = 0\n    while index < len(numbers):\n        value = numbers[index]\n        if largest is None or value > largest:\n            if value != largest: second = largest\n            largest = value\n        elif value != largest and (second is None or value > second): second = value\n        index += 1\n    return second',[[[[3,1,3,2]],2],[[[5,5]],null],[[[-1,-3,-2]],-2]]],
 ['caesar_shift_while','text, shift','shift ASCII letters while preserving case and other characters','décale les lettres ASCII en conservant la casse et les autres caractères','result = ""\n    index = 0\n    while index < len(text):\n        char = text[index]\n        if "a" <= char <= "z": result += chr((ord(char) - 97 + shift) % 26 + 97)\n        elif "A" <= char <= "Z": result += chr((ord(char) - 65 + shift) % 26 + 65)\n        else: result += char\n        index += 1',[[['Abc!',2],'Cde!'],[['xyz',3],'abc'],[['Hi',0],'Hi']]],
 ['matrix_column_totals','matrix','return the sum of each column in a rectangular matrix','retourne la somme de chaque colonne d’une matrice rectangulaire','if not matrix: return []\n    result = []\n    col = 0\n    while col < len(matrix[0]):\n        total = 0\n        row = 0\n        while row < len(matrix):\n            total += matrix[row][col]\n            row += 1\n        result.append(total)\n        col += 1',[[[[[1,2],[3,4]]],[4,6]],[[[[5,1,2]]],[5,1,2]],[[[]],[]]]],
 ['run_length_decode','encoded','decode letter-count pairs where each count is one decimal digit','décode les paires lettre-compte où chaque compte est un chiffre décimal','result = ""\n    index = 0\n    while index + 1 < len(encoded):\n        char = encoded[index]\n        count = int(encoded[index + 1])\n        while count > 0:\n            result += char\n            count -= 1\n        index += 2',[[['a3b2'],'aaabb'],[['x1'],'x'],[[''],'']]],
];
for (const [name, params, en, fr, body, cases] of advancedTasks) add(name, params, en, fr, body, cases, specs.length < 70 ? 'Intermediate' : 'Difficult', 'termination condition, state update, and invariant');

if (specs.length !== 100) throw new Error(`Expected 100 while-loop exercises, generated ${specs.length}`);

const startId = 2381;
const returnGroups = {
  result: ['count_up','count_down','even_numbers','odd_numbers','multiples_up_to','squares_to_n','cubes_to_n','powers_of_two','arithmetic_sequence','count_down_by_step','factorial_while','product_range','integer_power','digit_product','reverse_integer','decimal_to_binary','reverse_text','remove_vowels_while','remove_spaces_while','every_other_character','product_list_while','minimum_while','maximum_while','negative_values_while','square_values_while','reverse_list_while','running_totals_while','unique_in_order_while','prefix_before_marker','take_while_positive','flatten_nested','matrix_row_totals','transpose_matrix','merge_alternating','chunk_list','rotate_left_while','sliding_sums','divisors_while','fibonacci_while','bubble_sort_while','insertion_sort_while','merge_sorted_while','run_length_encode','convert_base'],
  total: ['sum_to_n','sum_squares','sum_cubes','sum_even_to_n','sum_odd_to_n','digit_sum','sum_list_while','matrix_total','sum_until_limit'],
  count: ['count_multiples','digit_count','count_zero_digits','count_specific_digit','count_vowels_while','count_consonants_while','count_character_while','count_positive_while','count_substring'],
  steps: ['steps_to_reach','collatz_steps'],
  largest: ['largest_digit'], smallest: ['smallest_digit'], number: ['digital_root'], counts: ['frequency_table'],
  guess: ['sqrt_approximation'], value: ['look_and_say'],
};
const returnExpression = name => Object.entries(returnGroups).find(([, names]) => names.includes(name))?.[0] ?? 'result';
const exercises = specs.map((spec, index) => {
  const id = startId + index;
  const signature = `def ${spec.name}(${spec.params})`;
  const calls = spec.cases.slice(0, 2).map(([args, expected]) => `${spec.name}(${args.map(py).join(', ')}) -> ${py(expected)}`);
  const bodyEndsWithReturn = /^\s*return\b/.test(spec.body.split('\n').at(-1) || '');
  const canonical = bodyEndsWithReturn ? `${signature}:\n    ${spec.body}` : `${signature}:\n    ${spec.body}\n    return ${returnExpression(spec.name)}`;
  return {
    id,
    title: `Problem ${id}`,
    description: `Write a Python function called \`${spec.name}\` that must ${spec.en}. Use a while loop.\nDifficulty: ${spec.level}.\nExamples:\n  ${calls.join('\n  ')}`,
    initialCode: `${signature}:\n    pass`,
    solution: `# Using function approach\n${canonical}\n\n${spec.cases.slice(0,2).map(([args, expected]) => `print(${spec.name}(${args.map(py).join(', ')}))  # Expected: ${py(expected)}`).join('\n')}\n\n# Script approach\nresult = ${spec.name}(${spec.cases[0][0].map(py).join(', ')})\nprint(result)\n\n# Direct approach\nprint(${spec.name}(${spec.cases[1][0].map(py).join(', ')}))`,
    hint: `Identify the loop state, write the condition that keeps repetition valid, and update that state on every path. Focus: ${spec.focus}.`,
    breakdown: `1. Initialize the state needed before the loop.\n2. Write a while condition that stops at the correct boundary.\n3. Perform the required operation during each iteration.\n4. Update the loop state so the condition eventually becomes False.\n5. Return the completed result.`,
    category: `While Loop ${spec.level}`,
  };
});

const graders = Object.fromEntries(specs.map((spec, index) => [startId + index, {
  functionNames: [spec.name],
  requiredNodePatterns: [{ nodeType: 'While', minCount: 1 }],
  compare: spec.name === 'sqrt_approximation' ? 'float' : undefined,
  tests: spec.cases.map(([args, expected]) => ({ args, expected })),
}]));
for (const grader of Object.values(graders)) if (!grader.compare) delete grader.compare;

const french = Object.fromEntries(specs.map((spec, index) => [startId + index, {
  description: `Écrivez une fonction Python appelée \`${spec.name}\` qui doit ${spec.fr}. Utilisez une boucle while.\nDifficulté : ${spec.level === 'Easy' ? 'Facile' : spec.level === 'Intermediate' ? 'Intermédiaire' : 'Difficile'}.`,
  hint: 'Identifiez l’état de la boucle, écrivez la condition d’arrêt et mettez l’état à jour à chaque chemin afin de garantir une progression sûre.',
  breakdown: `1. Initialisez l’état nécessaire avant la boucle.\n2. Écrivez une condition while qui s’arrête à la bonne limite.\n3. Effectuez l’opération demandée à chaque itération.\n4. Mettez à jour l’état afin que la condition devienne finalement False.\n5. Retournez le résultat terminé.`,
}]));

fs.writeFileSync(path.join(root, 'whileLoopPracticeExercises.ts'), `import type { Exercise } from './types';\n\nexport const WHILE_LOOP_PRACTICE_EXERCISES: Exercise[] = ${JSON.stringify(exercises, null, 2)};\n`);
fs.writeFileSync(path.join(root, 'whileLoopPracticeGraders.ts'), `import type { AutoGrader } from './graders';\n\nexport const WHILE_LOOP_PRACTICE_GRADERS: Record<number, AutoGrader> = ${JSON.stringify(graders, null, 2)};\n`);
fs.writeFileSync(path.join(root, 'services/whileLoopPracticeFr.ts'), `export const WHILE_LOOP_PRACTICE_FR: Record<number, { description: string; hint: string; breakdown: string }> = ${JSON.stringify(french, null, 2)};\n`);
console.log(`Generated ${specs.length} while-loop exercises (${startId}-${startId + specs.length - 1}).`);
