const fs = require('fs');
const os = require('os');
const path = require('path');
const ts = require('typescript');
const vm = require('vm');
const { spawnSync } = require('child_process');

const root = path.resolve(__dirname, '..');
const cache = new Map();

function resolveLocalModule(specifier) {
  const candidates = [specifier, `${specifier}.ts`, path.join(specifier, 'index.ts')];
  return candidates.find(candidate => fs.existsSync(path.join(root, candidate))) || null;
}

function loadTsExports(fileName) {
  if (cache.has(fileName)) return cache.get(fileName).exports;
  const source = fs.readFileSync(path.join(root, fileName), 'utf8');
  const compiled = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
    fileName,
  }).outputText;
  const module = { exports: {} };
  cache.set(fileName, module);
  vm.runInNewContext(compiled, {
    module,
    exports: module.exports,
    require: (specifier) => {
      const joined = path.normalize(path.join(path.dirname(fileName), specifier));
      const resolved = resolveLocalModule(joined);
      return resolved ? loadTsExports(resolved) : {};
    },
  }, { filename: fileName });
  return module.exports;
}

function renderedSections(code) {
  const sections = [];
  let current = null;
  for (const line of code.split('\n')) {
    if (/^# (?:Example \d+:|Nested function approach|Callable class approach)/.test(line)) {
      if (current) sections.push(current.join('\n').trim());
      current = [];
    } else if (current) current.push(line);
  }
  if (current) sections.push(current.join('\n').trim());
  return sections.filter(Boolean);
}

const { EXERCISES } = loadTsExports('exercises.ts');
const { AUTO_GRADERS } = loadTsExports('graders.ts');
const { buildSolutionVariations, solutionBodyKey } = loadTsExports('services/solutionVariations.ts');
const existingInvalid = loadTsExports('services/solutionBehaviorManifest.ts').INVALID_SOLUTION_BODY_KEYS;
const candidates = [];

for (const exercise of EXERCISES) {
  const rendered = buildSolutionVariations(exercise.solution, exercise.id, AUTO_GRADERS[exercise.id]);
  for (const body of renderedSections(rendered)) {
    candidates.push({
      id: exercise.id,
      candidateId: solutionBodyKey(body),
      solution: body,
    });
  }
}

const temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'python-solution-audit-'));
const candidatesFile = path.join(temporaryDirectory, 'candidates.json');
const resultsFile = path.join(temporaryDirectory, 'results.json');
fs.writeFileSync(candidatesFile, JSON.stringify(candidates));
const validation = spawnSync(process.execPath, [
  path.join(root, 'scripts/validate_graders.js'),
  `--candidate-file=${candidatesFile}`,
  `--results-file=${resultsFile}`,
  `--max-failures=${candidates.length}`,
], { cwd: root, encoding: 'utf8', maxBuffer: 30 * 1024 * 1024, timeout: 600000 });

if (validation.error) throw validation.error;
if (validation.status !== 0) throw new Error(validation.stderr || validation.stdout);
const results = JSON.parse(fs.readFileSync(resultsFile, 'utf8'));
const invalid = Object.fromEntries(Object.entries(existingInvalid).map(([id, keys]) => [id, [...keys]]));
let newlyExcluded = 0;
for (const result of results) {
  if (!result.passed && !(invalid[result.id] ?? []).includes(result.candidateId)) {
    (invalid[result.id] ??= []).push(result.candidateId);
    newlyExcluded += 1;
  }
}
for (const keys of Object.values(invalid)) keys.sort();

const output = [
  '// Generated by scripts/generate_solution_behavior_manifest.js.',
  '// Keys listed here compile but fail the exercise\'s behavioral grader.',
  `export const INVALID_SOLUTION_BODY_KEYS: Readonly<Record<number, readonly string[]>> = ${JSON.stringify(invalid, null, 2)};`,
  '',
].join('\n');
fs.writeFileSync(path.join(root, 'services/solutionBehaviorManifest.ts'), output);
fs.rmSync(temporaryDirectory, { recursive: true, force: true });
console.log(`Validated ${candidates.length} displayed candidates; newly excluded ${newlyExcluded}.`);
