#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const START_ID = 6058;
const specs = [];

const py = value => {
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (value === null) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(py).join(', ')}]`;
  if (typeof value === 'object') return `{${Object.entries(value).map(([key, item]) => `${py(key)}: ${py(item)}`).join(', ')}}`;
  return String(value);
};
const cases = (inputs, evaluate) => inputs.map(args => ({ args, expected: evaluate(...args) }));
const add = spec => specs.push({ ...spec, body: spec.body.trim() });
const addPack = (concept, level, count, factory) => {
  for (let index = 0; index < count; index += 1) add({ concept, level, ...factory(Math.floor(index / 5), index % 5 + 1) });
};

const whileEasy = (family, c) => {
  const defs = [
    [`count_digit_${c}_easy_while`, 'number', `count occurrences of digit ${c} in a non-negative integer`, `compte les occurrences du chiffre ${c} dans un entier non négatif`, `if number == 0:\n        return 0\n    count = 0\n    while number > 0:\n        if number % 10 == ${c}:\n            count += 1\n        number //= 10\n    return count`, cases([[1123451], [0], [c * 111]], number => String(Math.abs(number)).split('').filter(x => x === String(c)).length)],
    [`sum_before_${c}_easy_while`, 'values', `sum list values before the first ${c}`, `additionne les valeurs avant le premier ${c}`, `index = 0\n    total = 0\n    while index < len(values) and values[index] != ${c}:\n        total += values[index]\n        index += 1\n    return total`, cases([[[1, 2, c, 9]], [[c, 5]], [[2, 3]]], values => { const i = values.indexOf(c); return values.slice(0, i < 0 ? values.length : i).reduce((a,b)=>a+b,0); })],
    [`text_before_${c}_easy_while`, 'text', `return text before the first digit ${c}`, `retourne le texte avant le premier chiffre ${c}`, `index = 0\n    while index < len(text) and text[index] != ${py(String(c))}:\n        index += 1\n    return text[:index]`, cases([[`ab${c}cd`], [`${c}start`], ['plain']], text => text.split(String(c))[0])],
    [`countdown_step_${c}_easy_while`, 'start', `count down from \`start\` by ${c + 1} while values stay positive`, `compte à rebours depuis \`start\` par pas de ${c + 1} tant que les valeurs restent positives`, `result = []\n    while start > 0:\n        result.append(start)\n        start -= ${c + 1}\n    return result`, cases([[10], [1], [0]], start => { const out=[]; while(start>0){out.push(start);start-=c+1;} return out; })],
    [`repeat_items_${c}_easy_while`, 'items', `repeat each list item ${c} times using while loops`, `répète chaque élément ${c} fois avec des boucles while`, `result = []\n    index = 0\n    while index < len(items):\n        repeated = 0\n        while repeated < ${c}:\n            result.append(items[index])\n            repeated += 1\n        index += 1\n    return result`, cases([[['a','b']], [[1]], [[]]], items => items.flatMap(x => Array(c).fill(x)))],
    [`count_divisible_${c}_easy_while`, 'values', `count list values divisible by ${c + 2}`, `compte les valeurs divisibles par ${c + 2}`, `index = 0\n    count = 0\n    while index < len(values):\n        if values[index] % ${c + 2} == 0:\n            count += 1\n        index += 1\n    return count`, cases([[[1,2,3,4,6,9]], [[]], [[c+2]]], values => values.filter(x=>x%(c+2)===0).length)],
    [`first_greater_${c}_easy_while`, 'values', `return the first index whose value is greater than ${c * 2}, or -1`, `retourne le premier indice dont la valeur dépasse ${c * 2}, ou -1`, `index = 0\n    while index < len(values):\n        if values[index] > ${c * 2}:\n            return index\n        index += 1\n    return -1`, cases([[[1,9,2]], [[c*2]], [[]]], values => values.findIndex(x=>x>c*2))],
    [`offset_values_${c}_easy_while`, 'values', `add ${c} to every list value using a while loop`, `ajoute ${c} à chaque valeur avec une boucle while`, `result = []\n    index = 0\n    while index < len(values):\n        result.append(values[index] + ${c})\n        index += 1\n    return result`, cases([[[1,2]], [[-1]], [[]]], values=>values.map(x=>x+c))],
    [`parity_characters_${c}_easy_while`, 'text', `return characters at indexes with parity ${c % 2}`, `retourne les caractères aux indices de parité ${c % 2}`, `result = ""\n    index = ${c % 2}\n    while index < len(text):\n        result += text[index]\n        index += 2\n    return result`, cases([['abcdef'], ['x'], ['']], text=>[...text].filter((_,i)=>i%2===c%2).join(''))],
    [`changes_plus_${c}_easy_while`, 'values', `count adjacent value changes and add ${c}`, `compte les changements entre valeurs voisines et ajoute ${c}`, `count = ${c}\n    index = 1\n    while index < len(values):\n        if values[index] != values[index - 1]:\n            count += 1\n        index += 1\n    return count`, cases([[[1,1,2,2,3]], [[5]], [[]]], values=>values.slice(1).reduce((n,x,i)=>n+(x!==values[i]?1:0),c))],
  ];
  const [name,params,en,fr,body,testCases]=defs[family]; return {name,params,en,fr,body,cases:testCases,nodes:[{nodeType:'While',minCount:1}],focus:'loop state, termination, and guaranteed progress'};
};

const whileIntermediate = (family,c) => {
  const defs=[
    [`rotate_left_${c}_while`,'values',`rotate a list left by ${c} positions`,`fait pivoter une liste de ${c} positions vers la gauche`,`result = values.copy()\n    steps = 0\n    while result and steps < ${c}:\n        result.append(result.pop(0))\n        steps += 1\n    return result`,cases([[[1,2,3,4]],[[9]], [[]]],v=>v.length?[...v.slice(c%v.length),...v.slice(0,c%v.length)]:[])],
    [`merge_marker_${c}_while`,'left, right',`merge two sorted lists and append marker ${c}`,`fusionne deux listes triées et ajoute le marqueur ${c}`,`i = j = 0\n    result = []\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    result.extend(left[i:]); result.extend(right[j:]); result.append(${c})\n    return result`,cases([[[1,3],[2,4]], [[],[2]], [[1],[]]],(a,b)=>[...a,...b].sort((x,y)=>x-y).concat(c))],
    [`longest_run_${c}_while`,'values',`find the longest consecutive run of value ${c}`,`trouve la plus longue série consécutive de la valeur ${c}`,`index = 0\n    current = best = 0\n    while index < len(values):\n        current = current + 1 if values[index] == ${c} else 0\n        best = max(best, current)\n        index += 1\n    return best`,cases([[[c,c,0,c]], [[1,2]], [[]]],v=>{let best=0,n=0;for(const x of v){n=x===c?n+1:0;best=Math.max(best,n);}return best;})],
    [`chunk_size_${c}_while`,'values',`split a list into chunks of size ${c + 1}`,`divise une liste en groupes de taille ${c + 1}`,`result = []\n    index = 0\n    while index < len(values):\n        result.append(values[index:index + ${c + 1}])\n        index += ${c + 1}\n    return result`,cases([[[1,2,3,4,5,6]], [[]], [[9]]],v=>{const o=[];for(let i=0;i<v.length;i+=c+1)o.push(v.slice(i,i+c+1));return o;})],
    [`find_pattern_from_${c}_while`,'text, pattern',`find \`pattern\` starting at index ${c}, or return -1`,`trouve \`pattern\` à partir de l’indice ${c}, ou retourne -1`,`index = ${c}\n    while index <= len(text) - len(pattern):\n        if text[index:index + len(pattern)] == pattern:\n            return index\n        index += 1\n    return -1`,cases([['abracadabra','a'],['hello','ll'],['short','xyz']],(t,p)=>t.indexOf(p,c))],
    [`to_base_${c}_while`,'number',`convert a non-negative integer to base ${c + 2} text`,`convertit un entier non négatif en texte de base ${c + 2}`,`if number == 0:\n        return "0"\n    digits = ""\n    while number > 0:\n        digits = str(number % ${c + 2}) + digits\n        number //= ${c + 2}\n    return digits`,cases([[10],[0],[c+2]],n=>n.toString(c+2))],
    [`alternating_sum_${c}_while`,'values',`calculate an alternating sum beginning with multiplier ${c % 2 ? 1 : -1}`,`calcule une somme alternée avec le multiplicateur initial ${c % 2 ? 1 : -1}`,`index = 0\n    sign = ${c % 2 ? 1 : -1}\n    total = 0\n    while index < len(values):\n        total += sign * values[index]\n        sign *= -1\n        index += 1\n    return total`,cases([[[1,2,3]], [[]], [[5,-1]]],v=>v.reduce((n,x,i)=>n+x*(i%2?(c%2?-1:1):(c%2?1:-1)),0))],
    [`drop_every_${c}_while`,'values',`remove every ${c + 1}th item using a while loop`,`retire chaque ${c + 1}e élément avec une boucle while`,`result = []\n    index = 0\n    while index < len(values):\n        if (index + 1) % ${c + 1} != 0:\n            result.append(values[index])\n        index += 1\n    return result`,cases([[[1,2,3,4,5,6]], [[]], [[9]]],v=>v.filter((_,i)=>(i+1)%(c+1)!==0))],
    [`totals_until_${c}_while`,'values',`return running totals only while they do not exceed ${c * 10}`,`retourne les totaux cumulés tant qu’ils ne dépassent pas ${c * 10}`,`index = 0\n    total = 0\n    result = []\n    while index < len(values) and total + values[index] <= ${c * 10}:\n        total += values[index]\n        result.append(total)\n        index += 1\n    return result`,cases([[[3,4,50]], [[c*10]], [[]]],v=>{let t=0,o=[];for(const x of v){if(t+x>c*10)break;t+=x;o.push(t);}return o;})],
    [`adjacent_sums_${c}_while`,'values',`return adjacent pair sums with ${c} added to each`,`retourne les sommes des paires voisines avec ${c} ajouté`,`result = []\n    index = 1\n    while index < len(values):\n        result.append(values[index - 1] + values[index] + ${c})\n        index += 1\n    return result`,cases([[[1,2,3]], [[9]], [[]]],v=>v.slice(1).map((x,i)=>v[i]+x+c))],
  ]; const [name,params,en,fr,body,testCases]=defs[family];return{name,params,en,fr,body,cases:testCases,nodes:[{nodeType:'While',minCount:1}],focus:'multi-step loop invariants and boundary cases'};
};

const whileExpert=(family,c)=>{
 const defs=[
  [`binary_find_${c}_while`,'values, target',`binary-search a sorted list and add ${c} to a found index`,`effectue une recherche binaire et ajoute ${c} à l’indice trouvé`,`left = 0\n    right = len(values) - 1\n    while left <= right:\n        middle = (left + right) // 2\n        if values[middle] == target:\n            return middle + ${c}\n        if values[middle] < target: left = middle + 1\n        else: right = middle - 1\n    return -1`,cases([[[1,3,5,7],5],[[1],2],[[],1]],(v,t)=>{const i=v.indexOf(t);return i<0?-1:i+c;})],
  [`gcd_plus_${c}_while`,'left, right',`calculate the greatest common divisor and add ${c}`,`calcule le plus grand diviseur commun et ajoute ${c}`,`left = abs(left); right = abs(right)\n    while right:\n        left, right = right, left % right\n    return left + ${c}`,cases([[48,18],[7,0],[21,14]],(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b)[a,b]=[b,a%b];return a+c;})],
  [`encode_runs_${c}_while`,'values',`run-length encode a list and add ${c} to each run count`,`encode les séries d’une liste et ajoute ${c} à chaque longueur`,`result = []\n    index = 0\n    while index < len(values):\n        end = index + 1\n        while end < len(values) and values[end] == values[index]: end += 1\n        result.append([values[index], end - index + ${c}])\n        index = end\n    return result`,cases([[[1,1,2]], [[]], [['a','a','a']]],v=>{const o=[];for(let i=0;i<v.length;){let j=i+1;while(j<v.length&&v[j]===v[i])j++;o.push([v[i],j-i+c]);i=j;}return o;})],
  [`decode_runs_${c}_while`,'pairs',`decode value-count pairs and append marker ${c}`,`décode les paires valeur-nombre et ajoute le marqueur ${c}`,`result = []\n    index = 0\n    while index < len(pairs):\n        value, count = pairs[index]\n        repeated = 0\n        while repeated < count:\n            result.append(value); repeated += 1\n        index += 1\n    result.append(${c})\n    return result`,cases([[[['a',2],['b',1]]], [[]], [[[9,1]]]],p=>p.flatMap(([x,n])=>Array(n).fill(x)).concat(c))],
  [`flatten_marker_${c}_while`,'matrix',`flatten nested rows with while loops and append ${c}`,`aplatit les lignes imbriquées avec des boucles while et ajoute ${c}`,`result = []\n    row = 0\n    while row < len(matrix):\n        column = 0\n        while column < len(matrix[row]):\n            result.append(matrix[row][column]); column += 1\n        row += 1\n    result.append(${c})\n    return result`,cases([[[[1,2],[3]]], [[]], [[[]]]],m=>m.flat().concat(c))],
  [`row_max_plus_${c}_while`,'matrix',`find each non-empty row maximum manually and add ${c}`,`trouve manuellement le maximum de chaque ligne non vide et ajoute ${c}`,`result = []\n    row = 0\n    while row < len(matrix):\n        if matrix[row]:\n            best = matrix[row][0]; column = 1\n            while column < len(matrix[row]):\n                if matrix[row][column] > best: best = matrix[row][column]\n                column += 1\n            result.append(best + ${c})\n        row += 1\n    return result`,cases([[[[1,4],[3,2]]], [[[]]], [[]]],m=>m.filter(r=>r.length).map(r=>Math.max(...r)+c))],
  [`depth_limit_${c}_while`,'text',`verify balanced parentheses never exceed depth ${c}`,`vérifie que les parenthèses équilibrées ne dépassent jamais la profondeur ${c}`,`index = 0\n    depth = 0\n    while index < len(text):\n        if text[index] == "(": depth += 1\n        elif text[index] == ")":\n            depth -= 1\n            if depth < 0: return False\n        if depth > ${c}: return False\n        index += 1\n    return depth == 0`,cases([['()'],['(())'],['(()']],t=>{let d=0;for(const x of t){if(x==='(')d++;if(x===')')d--;if(d<0||d>c)return false;}return d===0;})],
  [`cycle_position_${c}_while`,'start, step, size',`advance ${c * 3} cyclic steps and return the final position`,`avance de ${c * 3} étapes cycliques et retourne la position finale`,`moves = 0\n    while moves < ${c * 3}:\n        start = (start + step) % size\n        moves += 1\n    return start`,cases([[0,2,5],[3,1,4],[1,3,7]],(s,step,size)=>(s+step*c*3)%size)],
  [`integer_sqrt_plus_${c}_while`,'number',`find the floor square root by odd-number subtraction and add ${c}`,`trouve la racine carrée entière par soustraction des nombres impairs et ajoute ${c}`,`root = 0\n    odd = 1\n    while number >= odd:\n        number -= odd\n        odd += 2\n        root += 1\n    return root + ${c}`,cases([[0],[15],[25]],n=>Math.floor(Math.sqrt(n))+c)],
  [`partition_pivot_${c}_while`,'values',`partition values below ${c}, equal to ${c}, and above ${c}`,`répartit les valeurs inférieures, égales et supérieures à ${c}`,`lower = []; equal = []; higher = []\n    index = 0\n    while index < len(values):\n        value = values[index]\n        if value < ${c}: lower.append(value)\n        elif value == ${c}: equal.append(value)\n        else: higher.append(value)\n        index += 1\n    return [lower, equal, higher]`,cases([[[0,c,c+2]], [[]], [[c,c]]],v=>[v.filter(x=>x<c),v.filter(x=>x===c),v.filter(x=>x>c)])],
 ];const [name,params,en,fr,body,testCases]=defs[family];return{name,params,en,fr,body,cases:testCases,nodes:[{nodeType:'While',minCount:1}],focus:'algorithm invariants, nested state, and termination proofs'};
};

addPack('While Loop','Easy',50,whileEasy);
addPack('While Loop','Intermediate',50,whileIntermediate);
addPack('While Loop','Expert',50,whileExpert);

const dictionaryFactory=(family,c)=>{
 const key=`k${c}`; const defs=[
  [`dict_get_${c}`,'mapping',`return key ${py(key)} with default ${c * 10}`,`retourne la clé ${py(key)} avec ${c * 10} par défaut`,`return mapping.get(${py(key)}, ${c*10})`,cases([[{[key]:c}],[{}],[{x:9}]],m=>Object.hasOwn(m,key)?m[key]:c*10)],
  [`dict_add_${c}`,'mapping',`return a copy with ${py(key)} set to ${c}`,`retourne une copie avec ${py(key)} associé à ${c}`,`result = mapping.copy()\n    result[${py(key)}] = ${c}\n    return result`,cases([[{a:1}],[{}],[{[key]:9}]],m=>({...m,[key]:c}))],
  [`dict_remove_${c}`,'mapping',`return a copy without key ${py(key)}`,`retourne une copie sans la clé ${py(key)}`,`result = mapping.copy()\n    result.pop(${py(key)}, None)\n    return result`,cases([[{[key]:c,a:1}],[{}],[{x:2}]],m=>Object.fromEntries(Object.entries(m).filter(([k])=>k!==key)))],
  [`dict_size_plus_${c}`,'mapping',`return the dictionary size plus ${c}`,`retourne la taille du dictionnaire plus ${c}`,`return len(mapping) + ${c}`,cases([[{a:1,b:2}],[{}],[{x:1}]],m=>Object.keys(m).length+c)],
  [`dict_value_sum_${c}`,'mapping',`sum numeric dictionary values and add ${c}`,`additionne les valeurs numériques et ajoute ${c}`,`return sum(mapping.values()) + ${c}`,cases([[{a:1,b:2}],[{}],[{x:-2}]],m=>Object.values(m).reduce((a,b)=>a+b,0)+c)],
  [`dict_sorted_keys_${c}`,'mapping',`return sorted keys followed by ${py(key)}`,`retourne les clés triées suivies de ${py(key)}`,`return sorted(mapping.keys()) + [${py(key)}]`,cases([[{b:2,a:1}],[{}],[{x:1}]],m=>Object.keys(m).sort().concat(key))],
  [`dict_sorted_values_${c}`,'mapping',`return sorted values with ${c} appended`,`retourne les valeurs triées avec ${c} ajouté`,`return sorted(mapping.values()) + [${c}]`,cases([[{a:3,b:1}],[{}],[{x:-1}]],m=>Object.values(m).sort((a,b)=>a-b).concat(c))],
  [`dict_invert_${c}`,'mapping',`invert unique values into text keys and add ${c} to each original key text`,`inverse les valeurs uniques en clés textuelles et ajoute ${c} au texte de chaque clé`,`return {str(value): str(key) + ${py(String(c))} for key, value in mapping.items()}`,cases([[{a:1,b:2}],[{}],[{x:9}]],m=>Object.fromEntries(Object.entries(m).map(([k,v])=>[String(v),k+String(c)])))],
  [`dict_filter_${c}`,'mapping',`keep entries whose value is at least ${c}`,`conserve les entrées dont la valeur vaut au moins ${c}`,`return {key: value for key, value in mapping.items() if value >= ${c}}`,cases([[{a:0,b:5}],[{}],[{x:c}]],m=>Object.fromEntries(Object.entries(m).filter(([,v])=>v>=c)))],
  [`dict_offset_${c}`,'mapping',`add ${c} to every dictionary value`,`ajoute ${c} à chaque valeur du dictionnaire`,`return {key: value + ${c} for key, value in mapping.items()}`,cases([[{a:1,b:2}],[{}],[{x:-1}]],m=>Object.fromEntries(Object.entries(m).map(([k,v])=>[k,v+c])))],
  [`dict_merge_${c}`,'left, right',`merge two dictionaries and store marker ${c}`,`fusionne deux dictionnaires et stocke le marqueur ${c}`,`result = left.copy()\n    result.update(right)\n    result["marker"] = ${c}\n    return result`,cases([[{a:1},{b:2}],[{x:1},{x:9}],[{},{}]],(a,b)=>({...a,...b,marker:c}))],
  [`dict_frequency_${c}`,'items',`count item frequencies and add ${c} to every count`,`compte les fréquences et ajoute ${c} à chaque compteur`,`result = {}\n    for item in items:\n        result[item] = result.get(item, ${c}) + 1\n    return result`,cases([[['a','a','b']],[[]],[['x']]],items=>{const o={};for(const x of items)o[x]=(o[x]??c)+1;return o;})],
  [`dict_word_lengths_${c}`,'words',`map each word to its length plus ${c}`,`associe chaque mot à sa longueur plus ${c}`,`return {word: len(word) + ${c} for word in words}`,cases([[['a','code']],[[]],[['xy']]],w=>Object.fromEntries(w.map(x=>[x,x.length+c])))],
  [`dict_has_${c}`,'mapping',`return whether key ${py(key)} exists`,`retourne si la clé ${py(key)} existe`,`return ${py(key)} in mapping`,cases([[{[key]:1}],[{}],[{x:1}]],m=>Object.hasOwn(m,key))],
  [`dict_missing_${c}`,'mapping, keys',`return requested keys missing from the dictionary and append ${py(key)}`,`retourne les clés demandées absentes et ajoute ${py(key)}`,`return [item for item in keys if item not in mapping] + [${py(key)}]`,cases([[{a:1},['a','b']],[{},[]],[{x:1},['y']]],(m,ks)=>ks.filter(k=>!Object.hasOwn(m,k)).concat(key))],
  [`dict_prefix_${c}`,'mapping',`keep dictionary keys beginning with ${py(String(c))}`,`conserve les clés commençant par ${py(String(c))}`,`return {key: value for key, value in mapping.items() if str(key).startswith(${py(String(c))})}`,cases([[{[`${c}a`]:1,b:2}],[{}],[{[`${c}x`]:9}]],m=>Object.fromEntries(Object.entries(m).filter(([k])=>k.startsWith(String(c)))))],
  [`dict_group_parity_${c}`,'values',`group values as even or odd and add ${c} to each value`,`regroupe les valeurs en paires ou impaires et ajoute ${c} à chacune`,`result = {"even": [], "odd": []}\n    for value in values:\n        result["even" if value % 2 == 0 else "odd"].append(value + ${c})\n    return result`,cases([[[1,2,3]], [[]], [[4]]],v=>({even:v.filter(x=>x%2===0).map(x=>x+c),odd:v.filter(x=>x%2).map(x=>x+c)}))],
  [`dict_from_pairs_${c}`,'keys, values',`build a dictionary from matching key-value positions and store marker ${c}`,`construit un dictionnaire à partir des positions et stocke le marqueur ${c}`,`result = {}\n    for key, value in zip(keys, values): result[key] = value\n    result["marker"] = ${c}\n    return result`,cases([[['a','b'],[1,2]],[[],[]],[['x'],[9]]],(ks,vs)=>({...Object.fromEntries(ks.map((k,i)=>[k,vs[i]])),marker:c}))],
  [`dict_best_key_${c}`,'mapping',`return the key with the largest value, or ${py(key)} when empty`,`retourne la clé de la plus grande valeur, ou ${py(key)} si vide`,`return max(mapping, key=mapping.get) if mapping else ${py(key)}`,cases([[{a:1,b:5}],[{}],[{x:-1}]],m=>Object.keys(m).length?Object.keys(m).reduce((a,b)=>m[b]>m[a]?b:a):key)],
  [`dict_nested_${c}`,'mapping, outer',`read nested key ${py(key)} under \`outer\`, defaulting to ${c}`,`lit la clé imbriquée ${py(key)} sous \`outer\`, avec ${c} par défaut`,`return mapping.get(outer, {}).get(${py(key)}, ${c})`,cases([[{a:{[key]:9}},'a'],[{},'x'],[{a:{}},'a']],(m,o)=>m[o]?.[key]??c)],
 ];const [name,params,en,fr,body,testCases]=defs[family];return{name,params,en,fr,body,cases:testCases,focus:'key lookup, mutation versus copying, and the exact result shape'};
};
addPack('Dictionary','Easy',100,dictionaryFactory);

const comprehensionFactory=(level)=>(family,c)=>{
 const easy=[
  [`comp_add_${c}`,'values',`add ${c} to every value with a list comprehension`,`ajoute ${c} à chaque valeur avec une compréhension de liste`,`return [value + ${c} for value in values]`,cases([[[1,2]],[[]],[[-1]]],v=>v.map(x=>x+c)),'ListComp'],
  [`comp_even_${c}`,'values',`keep values whose remainder modulo ${c+1} is zero`,`conserve les valeurs dont le reste modulo ${c+1} vaut zéro`,`return [value for value in values if value % ${c+1} == 0]`,cases([[[1,2,3,4,6]],[[]],[[c+1]]],v=>v.filter(x=>x%(c+1)===0)),'ListComp'],
  [`comp_text_${c}`,'words',`append digit ${c} to every word`,`ajoute le chiffre ${c} à chaque mot`,`return [word + ${py(String(c))} for word in words]`,cases([[['a','b']],[[]],[['x']]],w=>w.map(x=>x+c)),'ListComp'],
  [`comp_lengths_${c}`,'words',`return word lengths plus ${c}`,`retourne les longueurs des mots plus ${c}`,`return [len(word) + ${c} for word in words]`,cases([[['a','code']],[[]],[['xy']]],w=>w.map(x=>x.length+c)),'ListComp'],
  [`comp_dict_${c}`,'values',`map text keys to squares plus ${c}`,`associe des clés textuelles aux carrés plus ${c}`,`return {str(value): value ** 2 + ${c} for value in values}`,cases([[[1,2]],[[]],[[-1]]],v=>Object.fromEntries(v.map(x=>[String(x),x*x+c]))),'DictComp'],
  [`comp_set_${c}`,'values',`return sorted unique absolute values plus ${c}`,`retourne les valeurs absolues uniques triées plus ${c}`,`return sorted({abs(value) + ${c} for value in values})`,cases([[[-1,1,2]],[[]],[[0]]],v=>[...new Set(v.map(x=>Math.abs(x)+c))].sort((a,b)=>a-b)),'SetComp'],
  [`comp_indexes_${c}`,'text',`return indexes plus ${c} for characters equal to digit ${c}`,`retourne les indices plus ${c} des caractères égaux au chiffre ${c}`,`return [index + ${c} for index, char in enumerate(text) if char == ${py(String(c))}]`,cases([[`a${c}b${c}`],[''],['abc']],t=>[...t].flatMap((x,i)=>x===String(c)?[i+c]:[])),'ListComp'],
  [`comp_flat_${c}`,'matrix',`flatten a matrix and multiply values by ${c}`,`aplatit une matrice et multiplie les valeurs par ${c}`,`return [value * ${c} for row in matrix for value in row]`,cases([[[[1,2],[3]]],[[]],[[[]]]],m=>m.flat().map(x=>x*c)),'ListComp'],
  [`comp_flags_${c}`,'values',`return flags showing which values are at least ${c}`,`retourne des indicateurs montrant quelles valeurs valent au moins ${c}`,`return [value >= ${c} for value in values]`,cases([[[0,c,c+1]],[[]],[[9]]],v=>v.map(x=>x>=c)),'ListComp'],
  [`comp_pairs_${c}`,'values',`pair each value with that value plus ${c}`,`associe chaque valeur à cette valeur plus ${c}`,`return [[value, value + ${c}] for value in values]`,cases([[[1,2]],[[]],[[-1]]],v=>v.map(x=>[x,x+c])),'ListComp'],
 ];
 const intermediate=[
  [`comp_nested_filter_${c}`,'matrix',`flatten only values greater than ${c} with a nested comprehension`,`aplatit seulement les valeurs supérieures à ${c} avec une compréhension imbriquée`,`return [value for row in matrix for value in row if value > ${c}]`,cases([[[[1,5],[0,9]]],[[]],[[[]]]],m=>m.flat().filter(x=>x>c)),'ListComp'],
  [`comp_coordinate_${c}`,'matrix',`return coordinates of cells equal to ${c}`,`retourne les coordonnées des cellules égales à ${c}`,`return [[row, column] for row, values in enumerate(matrix) for column, value in enumerate(values) if value == ${c}]`,cases([[[[c,0],[0,c]]],[[]],[[[1]]]],m=>m.flatMap((r,i)=>r.flatMap((x,j)=>x===c?[[i,j]]:[]))),'ListComp'],
  [`comp_group_${c}`,'values',`build a dictionary grouping values by remainder modulo ${c+2}`,`construit un dictionnaire regroupant les valeurs par reste modulo ${c+2}`,`return {str(remainder): [value for value in values if value % ${c+2} == remainder] for remainder in range(${c+2})}`,cases([[[1,2,3,4]],[[]],[[0]]],v=>Object.fromEntries(Array.from({length:c+2},(_,r)=>[String(r),v.filter(x=>((x%(c+2))+(c+2))%(c+2)===r)]))),'DictComp'],
  [`comp_transpose_${c}`,'matrix',`transpose a rectangular matrix and add ${c} to every cell`,`transpose une matrice rectangulaire et ajoute ${c} à chaque cellule`,`return [[row[column] + ${c} for row in matrix] for column in range(len(matrix[0]))] if matrix else []`,cases([[[[1,2],[3,4]]],[[]],[[[5]]]],m=>m.length?m[0].map((_,j)=>m.map(r=>r[j]+c)):[]),'ListComp'],
  [`comp_word_map_${c}`,'words',`map lowercase words of length at least ${c} to uppercase text`,`associe les mots minuscules d’au moins ${c} caractères à leur texte majuscule`,`return {word.lower(): word.upper() for word in words if len(word) >= ${c}}`,cases([[['A','code']],[[]],[['Python']]],w=>Object.fromEntries(w.filter(x=>x.length>=c).map(x=>[x.toLowerCase(),x.toUpperCase()]))),'DictComp'],
  [`comp_products_${c}`,'left, right',`return unique sorted products above ${c} from two lists`,`retourne les produits uniques triés supérieurs à ${c} de deux listes`,`return sorted({a * b for a in left for b in right if a * b > ${c}})`,cases([[[1,2],[3,4]],[[],[1]],[[c+1],[1]]],(a,b)=>[...new Set(a.flatMap(x=>b.map(y=>x*y)).filter(x=>x>c))].sort((x,y)=>x-y)),'SetComp'],
  [`comp_running_windows_${c}`,'values',`return sums of windows of size ${c+1}`,`retourne les sommes des fenêtres de taille ${c+1}`,`return [sum(values[index:index + ${c+1}]) for index in range(len(values) - ${c})]`,cases([[[1,2,3,4,5,6]],[[]],[[9]]],v=>Array.from({length:Math.max(0,v.length-c)},(_,i)=>v.slice(i,i+c+1).reduce((a,b)=>a+b,0))),'ListComp'],
  [`comp_invert_groups_${c}`,'mapping',`invert a dictionary into value text mapped to keys suffixed by ${c}`,`inverse un dictionnaire en texte de valeur associé aux clés suffixées par ${c}`,`return {str(value): str(key) + ${py(String(c))} for key, value in mapping.items()}`,cases([[{a:1,b:2}],[{}],[{x:9}]],m=>Object.fromEntries(Object.entries(m).map(([k,v])=>[String(v),k+c]))),'DictComp'],
  [`comp_diagonal_${c}`,'matrix',`return main diagonal values plus ${c}`,`retourne les valeurs de la diagonale principale plus ${c}`,`return [matrix[index][index] + ${c} for index in range(min(len(matrix), len(matrix[0]) if matrix else 0))]`,cases([[[[1,2],[3,4]]],[[]],[[[5]]]],m=>Array.from({length:m.length?Math.min(m.length,m[0].length):0},(_,i)=>m[i][i]+c)),'ListComp'],
  [`comp_conditional_${c}`,'values',`square values above ${c} and negate all others`,`met au carré les valeurs supérieures à ${c} et nie les autres`,`return [value ** 2 if value > ${c} else -value for value in values]`,cases([[[0,c,c+1]],[[]],[[-2]]],v=>v.map(x=>x>c?x*x:-x)),'ListComp'],
 ]; const defs=level==='Easy'?easy:intermediate;const [name,params,en,fr,body,testCases,nodeType]=defs[family];return{name,params,en,fr,body,cases:testCases,nodes:[{nodeType,minCount:1}],focus:'expression order, nested clauses, filters, and output type'};
};
addPack('Comprehension','Easy',50,comprehensionFactory('Easy'));
addPack('Comprehension','Intermediate',50,comprehensionFactory('Intermediate'));

const closureFactory=(family,c)=>{
 const defs=[
  [`closure_add_${c}`,'',`return a closure that adds ${c} to its argument`,`retourne une fermeture qui ajoute ${c} à son argument`,`def inner(value):\n        return value + ${c}\n    return inner`,[{args:[],callReturnedWith:[5],expected:5+c},{args:[],callReturnedWith:[-1],expected:c-1},{args:[],callReturnedWith:[0],expected:c}]],
  [`closure_multiply_${c}`,'',`return a closure that multiplies its argument by ${c}`,`retourne une fermeture qui multiplie son argument par ${c}`,`def inner(value):\n        return value * ${c}\n    return inner`,[{args:[],callReturnedWith:[5],expected:5*c},{args:[],callReturnedWith:[-1],expected:-c},{args:[],callReturnedWith:[0],expected:0}]],
  [`closure_prefix_${c}`,'',`return a closure that prefixes text with ${py(`${c}:`)}`,`retourne une fermeture qui préfixe le texte avec ${py(`${c}:`)}`,`prefix = ${py(`${c}:`)}\n    def inner(text):\n        return prefix + text\n    return inner`,[{args:[],callReturnedWith:['code'],expected:`${c}:code`},{args:[],callReturnedWith:[''],expected:`${c}:`},{args:[],callReturnedWith:['x'],expected:`${c}:x`}]],
  [`closure_suffix_${c}`,'',`return a closure that suffixes text with ${py(`:${c}`)}`,`retourne une fermeture qui suffixe le texte avec ${py(`:${c}`)}`,`suffix = ${py(`:${c}`)}\n    def inner(text):\n        return text + suffix\n    return inner`,[{args:[],callReturnedWith:['code'],expected:`code:${c}`},{args:[],callReturnedWith:[''],expected:`:${c}`},{args:[],callReturnedWith:['x'],expected:`x:${c}`}]],
  [`closure_power_${c}`,'',`return a closure that raises a value to power ${c+1}`,`retourne une fermeture qui élève une valeur à la puissance ${c+1}`,`power = ${c+1}\n    def inner(value):\n        return value ** power\n    return inner`,[{args:[],callReturnedWith:[2],expected:2**(c+1)},{args:[],callReturnedWith:[1],expected:1},{args:[],callReturnedWith:[0],expected:0}]],
  [`closure_minimum_${c}`,'',`return a closure that clamps values to a minimum of ${c}`,`retourne une fermeture qui limite les valeurs à un minimum de ${c}`,`minimum = ${c}\n    def inner(value):\n        return max(value, minimum)\n    return inner`,[{args:[],callReturnedWith:[0],expected:c},{args:[],callReturnedWith:[c+2],expected:c+2},{args:[],callReturnedWith:[c],expected:c}]],
  [`closure_member_${c}`,'',`return a closure testing membership in the captured set {${c}, ${c+1}}`,`retourne une fermeture testant l’appartenance à l’ensemble capturé {${c}, ${c+1}}`,`allowed = {${c}, ${c+1}}\n    def inner(value):\n        return value in allowed\n    return inner`,[{args:[],callReturnedWith:[c],expected:true},{args:[],callReturnedWith:[c+2],expected:false},{args:[],callReturnedWith:[c+1],expected:true}]],
  [`closure_above_${c}`,'',`return a closure testing whether a value exceeds ${c}`,`retourne une fermeture testant si une valeur dépasse ${c}`,`threshold = ${c}\n    def inner(value):\n        return value > threshold\n    return inner`,[{args:[],callReturnedWith:[c+1],expected:true},{args:[],callReturnedWith:[c],expected:false},{args:[],callReturnedWith:[0],expected:false}]],
  [`closure_label_${c}`,'',`return a closure formatting a name with label ${py(`L${c}`)}`,`retourne une fermeture formatant un nom avec l’étiquette ${py(`L${c}`)}`,`label = ${py(`L${c}`)}\n    def inner(name):\n        return label + "=" + name\n    return inner`,[{args:[],callReturnedWith:['Ana'],expected:`L${c}=Ana`},{args:[],callReturnedWith:[''],expected:`L${c}=`},{args:[],callReturnedWith:['X'],expected:`L${c}=X`}]],
  [`closure_offset_length_${c}`,'',`return a closure adding ${c} to an item's length`,`retourne une fermeture ajoutant ${c} à la longueur d’un élément`,`offset = ${c}\n    def inner(item):\n        return len(item) + offset\n    return inner`,[{args:[],callReturnedWith:[[1,2]],expected:c+2},{args:[],callReturnedWith:['abc'],expected:c+3},{args:[],callReturnedWith:[[]],expected:c}]],
 ];const [name,params,en,fr,body,testCases]=defs[family];return{name,params,en,fr,body,cases:testCases,nodes:[{nodeType:'FunctionDef',minCount:2}],focus:'captured state, enclosing scope, and the returned inner function'};
};
addPack('Closure','Easy',50,closureFactory);

const lambdaFactory=level=>(family,c)=>{
 const easy=[
  [`lambda_add_${c}`,'value',`add ${c} with a lambda`,`ajoute ${c} avec une lambda`,`operation = lambda item: item + ${c}\n    return operation(value)`,cases([[5],[-1],[0]],x=>x+c)],
  [`lambda_multiply_${c}`,'value',`multiply by ${c} with a lambda`,`multiplie par ${c} avec une lambda`,`operation = lambda item: item * ${c}\n    return operation(value)`,cases([[5],[-1],[0]],x=>x*c)],
  [`lambda_square_${c}`,'value',`square a value and add ${c} with a lambda`,`met une valeur au carré et ajoute ${c} avec une lambda`,`operation = lambda item: item ** 2 + ${c}\n    return operation(value)`,cases([[3],[-2],[0]],x=>x*x+c)],
  [`lambda_distance_${c}`,'value',`measure absolute distance from ${c} with a lambda`,`mesure la distance absolue depuis ${c} avec une lambda`,`operation = lambda item: abs(item - ${c})\n    return operation(value)`,cases([[10],[-1],[c]],x=>Math.abs(x-c))],
  [`lambda_divisible_${c}`,'value',`test divisibility by ${c+1} with a lambda`,`teste la divisibilité par ${c+1} avec une lambda`,`operation = lambda item: item % ${c+1} == 0\n    return operation(value)`,cases([[c+1],[c+2],[0]],x=>x%(c+1)===0)],
  [`lambda_suffix_${c}`,'text',`append ${py(String(c))} to text with a lambda`,`ajoute ${py(String(c))} au texte avec une lambda`,`operation = lambda item: item + ${py(String(c))}\n    return operation(text)`,cases([['code'],[''],['x']],x=>x+c)],
  [`lambda_first_${c}`,'text',`return the first character or digit ${c} with a lambda`,`retourne le premier caractère ou le chiffre ${c} avec une lambda`,`operation = lambda item: item[0] if item else ${py(String(c))}\n    return operation(text)`,cases([['abc'],[''],['x']],x=>x?x[0]:String(c))],
  [`lambda_length_${c}`,'items',`add ${c} to item length with a lambda`,`ajoute ${c} à la longueur avec une lambda`,`operation = lambda item: len(item) + ${c}\n    return operation(items)`,cases([[[1,2]], [[]], ['abc']],x=>x.length+c)],
  [`lambda_pair_${c}`,'value',`return a two-item list containing a value and value plus ${c}`,`retourne une liste de deux éléments contenant une valeur et la valeur plus ${c}`,`operation = lambda item: [item, item + ${c}]\n    return operation(value)`,cases([[1],[-1],[0]],x=>[x,x+c])],
  [`lambda_default_${c}`,'mapping',`read key ${py(`k${c}`)} with default ${c} using a lambda`,`lit la clé ${py(`k${c}`)} avec ${c} par défaut en utilisant une lambda`,`operation = lambda item: item.get(${py(`k${c}`)}, ${c})\n    return operation(mapping)`,cases([[{[`k${c}`]:9}],[{}],[{x:1}]],m=>m[`k${c}`]??c)],
  [`lambda_max_${c}`,'left, right',`return the larger value plus ${c} with a lambda`,`retourne la plus grande valeur plus ${c} avec une lambda`,`operation = lambda a, b: max(a, b) + ${c}\n    return operation(left, right)`,cases([[1,5],[-1,-2],[3,3]],(a,b)=>Math.max(a,b)+c)],
  [`lambda_min_${c}`,'left, right',`return the smaller value minus ${c} with a lambda`,`retourne la plus petite valeur moins ${c} avec une lambda`,`operation = lambda a, b: min(a, b) - ${c}\n    return operation(left, right)`,cases([[1,5],[-1,-2],[3,3]],(a,b)=>Math.min(a,b)-c)],
  [`lambda_above_${c}`,'value',`test whether a value exceeds ${c} with a lambda`,`teste si une valeur dépasse ${c} avec une lambda`,`operation = lambda item: item > ${c}\n    return operation(value)`,cases([[c+1],[c],[0]],x=>x>c)],
  [`lambda_sign_${c}`,'value',`return ${py(`positive${c}`)} or ${py(`other${c}`)} with a lambda`,`retourne ${py(`positive${c}`)} ou ${py(`other${c}`)} avec une lambda`,`operation = lambda item: ${py(`positive${c}`)} if item > 0 else ${py(`other${c}`)}\n    return operation(value)`,cases([[1],[0],[-1]],x=>x>0?`positive${c}`:`other${c}`)],
  [`lambda_upper_${c}`,'text',`uppercase text and append ${c} with a lambda`,`met le texte en majuscules et ajoute ${c} avec une lambda`,`operation = lambda item: item.upper() + ${py(String(c))}\n    return operation(text)`,cases([['code'],[''],['Py']],x=>x.toUpperCase()+c)],
  [`lambda_last_${c}`,'items',`return the last item or ${c} with a lambda`,`retourne le dernier élément ou ${c} avec une lambda`,`operation = lambda item: item[-1] if item else ${c}\n    return operation(items)`,cases([[[1,2]], [[]], [[9]]],x=>x.length?x.at(-1):c)],
  [`lambda_sum_${c}`,'values',`sum values and add ${c} with a lambda`,`additionne les valeurs et ajoute ${c} avec une lambda`,`operation = lambda items: sum(items) + ${c}\n    return operation(values)`,cases([[[1,2,3]], [[]], [[-1]]],x=>x.reduce((a,b)=>a+b,0)+c)],
  [`lambda_reverse_${c}`,'text',`reverse text and append ${c} with a lambda`,`inverse le texte et ajoute ${c} avec une lambda`,`operation = lambda item: item[::-1] + ${py(String(c))}\n    return operation(text)`,cases([['abc'],[''],['x']],x=>[...x].reverse().join('')+c)],
  [`lambda_clamp_${c}`,'value',`clamp a value to at least ${c} with a lambda`,`limite une valeur à au moins ${c} avec une lambda`,`operation = lambda item: max(item, ${c})\n    return operation(value)`,cases([[0],[c],[c+2]],x=>Math.max(x,c))],
  [`lambda_repeat_${c}`,'text',`repeat text ${c} times with a lambda`,`répète le texte ${c} fois avec une lambda`,`operation = lambda item: item * ${c}\n    return operation(text)`,cases([['ab'],[''],['x']],x=>x.repeat(c))],
 ];
 const intermediate=[
  [`lambda_sort_length_${c}`,'words',`sort words by length then text and append marker ${c}`,`trie les mots par longueur puis texte et ajoute le marqueur ${c}`,`result = sorted(words, key=lambda word: (len(word), word))\n    return result + [${py(String(c))}]`,cases([[['bbb','a','cc']],[[]],[['x']]],w=>[...w].sort((a,b)=>a.length-b.length||a.localeCompare(b)).concat(String(c)))],
  [`lambda_map_offset_${c}`,'values',`map values to squares plus ${c} using lambda and map`,`transforme les valeurs en carrés plus ${c} avec lambda et map`,`return list(map(lambda value: value ** 2 + ${c}, values))`,cases([[[1,2]],[[]],[[-2]]],v=>v.map(x=>x*x+c))],
  [`lambda_filter_${c}`,'values',`filter values greater than ${c} using lambda and filter`,`filtre les valeurs supérieures à ${c} avec lambda et filter`,`return list(filter(lambda value: value > ${c}, values))`,cases([[[0,c,c+1]],[[]],[[9]]],v=>v.filter(x=>x>c))],
  [`lambda_sort_dict_${c}`,'records',`sort dictionaries by score descending then name and append marker ${c}`,`trie les dictionnaires par score décroissant puis nom et ajoute le marqueur ${c}`,`result = sorted(records, key=lambda item: (-item["score"], item["name"]))\n    return result + [{"marker": ${c}}]`,cases([[[{name:'B',score:1},{name:'A',score:2}]],[[]],[[{name:'X',score:0}]]],r=>[...r].sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).concat({marker:c}))],
  [`lambda_pairs_${c}`,'values',`sort values by distance from ${c}, then by value`,`trie les valeurs par distance depuis ${c}, puis par valeur`,`return sorted(values, key=lambda value: (abs(value - ${c}), value))`,cases([[[0,3,9]],[[]],[[c]]],v=>[...v].sort((a,b)=>Math.abs(a-c)-Math.abs(b-c)||a-b))],
  [`lambda_dict_values_${c}`,'mapping',`sort dictionary keys by value plus ${c}, then key`,`trie les clés du dictionnaire par valeur plus ${c}, puis par clé`,`return sorted(mapping, key=lambda key: (mapping[key] + ${c}, key))`,cases([[{b:1,a:2}],[{}],[{x:0}]],m=>Object.keys(m).sort((a,b)=>(m[a]+c)-(m[b]+c)||a.localeCompare(b)))],
  [`lambda_nested_${c}`,'matrix',`sort rows by sum plus ${c}, then row length`,`trie les lignes par somme plus ${c}, puis longueur`,`return sorted(matrix, key=lambda row: (sum(row) + ${c}, len(row)))`,cases([[[[3],[1,1],[0]]],[[]],[[[]]]],m=>[...m].sort((a,b)=>(a.reduce((x,y)=>x+y,0)+c)-(b.reduce((x,y)=>x+y,0)+c)||a.length-b.length))],
  [`lambda_transform_words_${c}`,'words',`map words to lowercase text suffixed by ${c} using lambda`,`transforme les mots en minuscules suffixées par ${c} avec lambda`,`return list(map(lambda word: word.lower() + ${py(String(c))}, words))`,cases([[['A','Py']],[[]],[['X']]],w=>w.map(x=>x.toLowerCase()+c))],
  [`lambda_filter_length_${c}`,'words',`filter words with length at least ${c} using lambda`,`filtre les mots d’au moins ${c} caractères avec lambda`,`return list(filter(lambda word: len(word) >= ${c}, words))`,cases([[['a','code','python']],[[]],[['x'.repeat(c)]]],w=>w.filter(x=>x.length>=c))],
  [`lambda_sort_last_${c}`,'words',`sort words by last character or digit ${c} when empty`,`trie les mots par dernier caractère ou chiffre ${c} s’ils sont vides`,`return sorted(words, key=lambda word: word[-1] if word else ${py(String(c))})`,cases([[['cat','bee',''],['unused']].slice(0,1),[[]],[['a','b']]],w=>[...w].sort((a,b)=>(a.at(-1)??String(c)).localeCompare(b.at(-1)??String(c))))],
 ]; const defs=level==='Easy'?easy:intermediate;const [name,params,en,fr,body,testCases]=defs[family];return{name,params,en,fr,body,cases:testCases,nodes:[{nodeType:'Lambda',minCount:1}],focus:'lambda parameters, expression result, and higher-order call order'};
};
addPack('Lambda','Easy',100,lambdaFactory('Easy'));
addPack('Lambda','Intermediate',50,lambdaFactory('Intermediate'));

const expected={
 'While Loop Easy':50,'While Loop Intermediate':50,'While Loop Expert':50,'Dictionary Easy':100,
 'Comprehension Easy':50,'Comprehension Intermediate':50,'Closure Easy':50,'Lambda Easy':100,'Lambda Intermediate':50,
};
if(specs.length!==550)throw new Error(`Expected 550 specs, found ${specs.length}`);
for(const [label,count] of Object.entries(expected)){const [concept,...levelParts]=label.split(' ');const level=levelParts.at(-1);const actual=specs.filter(s=>`${s.concept} ${s.level}`===label).length;if(actual!==count)throw new Error(`${label}: ${actual}`);}
if(new Set(specs.map(s=>s.name)).size!==specs.length)throw new Error('Duplicate function names');

const labelsFr={'While Loop':'boucle while',Dictionary:'dictionnaire',Comprehension:'compréhension',Closure:'fermeture',Lambda:'lambda'};
const levelFr={Easy:'Facile',Intermediate:'Intermédiaire',Expert:'Expert'};
const focusFr={
 'While Loop':'l’état de la boucle, sa condition d’arrêt, sa progression garantie et les cas limites',
 Dictionary:'la recherche des clés, la modification par rapport à la copie et la forme exacte du résultat',
 Comprehension:'l’ordre des expressions, les clauses imbriquées, les filtres et le type du résultat',
 Closure:'l’état capturé, la portée englobante et la fonction interne retournée',
 Lambda:'les paramètres lambda, le résultat de l’expression et l’ordre des appels de fonctions d’ordre supérieur',
};
const exercises=[];const graders={};const french={};
const invoke=(spec,test)=>`${spec.name}(${test.args.map(py).join(', ')})${test.callReturnedWith?`(${test.callReturnedWith.map(py).join(', ')})`:''}`;
specs.forEach((spec,index)=>{
 const id=START_ID+index;const canonical=`def ${spec.name}(${spec.params}):\n    ${spec.body}`;const nested=canonical.split('\n').slice(1).map(line=>`    ${line}`).join('\n');const classBody=canonical.split('\n').map(line=>`    ${line}`).join('\n');
 const solution=`# Example 1: canonical function approach\n${canonical}\n\nprint(${invoke(spec,spec.cases[0])})  # Expected: ${py(spec.cases[0].expected)}\nprint(${invoke(spec,spec.cases[1])})  # Expected: ${py(spec.cases[1].expected)}\n\n# Example 2: nested helper approach\ndef solve_problem_${id}(${spec.params}):\n    def calculate():\n${nested}\n    return calculate()\n\nprint(${invoke({...spec,name:`solve_problem_${id}`},spec.cases[0])})\n\n# Example 3: static method approach\nclass Problem${id}Solution:\n    @staticmethod\n${classBody}\n\nprint(Problem${id}Solution.${invoke(spec,spec.cases[1])})\n\n# Example 4: assigned result approach\nresult = ${invoke(spec,spec.cases[0])}\nprint(result)\n\n# Example 5: direct call\nprint(${invoke(spec,spec.cases[2])})`;
 exercises.push({id,title:`Problem ${id}`,description:`Write a Python function called \`${spec.name}\` that must ${spec.en}. Practice ${spec.concept.toLowerCase()} syntax.\nDifficulty: ${spec.level}.\nExamples:\n  ${invoke(spec,spec.cases[0])} -> ${py(spec.cases[0].expected)}\n  ${invoke(spec,spec.cases[1])} -> ${py(spec.cases[1].expected)}`,initialCode:`def ${spec.name}(${spec.params}):\n    pass`,solution,hint:`Focus on ${spec.focus}. Use the requested structure and test a boundary case.`,breakdown:`1. Identify the parameters and return type.\n2. Build the requested ${spec.concept.toLowerCase()} structure.\n3. Trace intermediate values in order.\n4. Handle empty and boundary inputs.\n5. Return the result without hard-coding examples.`,category:`${spec.concept} ${spec.level}`});
 const grader={functionNames:[spec.name],tests:spec.cases};if(spec.nodes)grader.requiredNodePatterns=spec.nodes;if(spec.calls)grader.requiredCallPatterns=spec.calls.map(functionName=>({functionName,minArgs:0}));graders[id]=grader;
 french[id]={description:`Écrivez une fonction Python appelée \`${spec.name}\` qui ${spec.fr}. Entraînez-vous avec la syntaxe de ${labelsFr[spec.concept]}.\nDifficulté : ${levelFr[spec.level]}.\nExemples :\n  ${invoke(spec,spec.cases[0])} -> ${py(spec.cases[0].expected)}\n  ${invoke(spec,spec.cases[1])} -> ${py(spec.cases[1].expected)}`,hint:`Concentrez-vous sur ${focusFr[spec.concept]}. Utilisez la structure demandée et testez un cas limite.`,breakdown:`1. Identifiez les paramètres et le type de retour.\n2. Construisez la structure de ${labelsFr[spec.concept]} demandée.\n3. Suivez les valeurs intermédiaires dans l’ordre.\n4. Gérez les entrées vides et limites.\n5. Retournez le résultat sans coder les exemples en dur.`};
});
fs.writeFileSync(path.join(root,'conceptLevelExpansionExercises.ts'),`import type { Exercise } from './types';\n\nexport const CONCEPT_LEVEL_EXPANSION_EXERCISES: Exercise[] = ${JSON.stringify(exercises,null,2)};\n`);
fs.writeFileSync(path.join(root,'conceptLevelExpansionGraders.ts'),`import type { AutoGrader } from './graders';\n\nexport const CONCEPT_LEVEL_EXPANSION_GRADERS: Record<number, AutoGrader> = ${JSON.stringify(graders,null,2)};\n`);
fs.writeFileSync(path.join(root,'services/conceptLevelExpansionFr.ts'),`export const CONCEPT_LEVEL_EXPANSION_FR: Record<number, { description: string; hint: string; breakdown: string }> = ${JSON.stringify(french,null,2)};\n`);
console.log(`Generated ${specs.length} concept-level exercises (${START_ID}-${START_ID+specs.length-1}).`);
