const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const ts = require('typescript');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const cache = new Map();

function loadTsExports(fileName) {
  if (cache.has(fileName)) return cache.get(fileName).exports;
  const source = fs.readFileSync(path.join(root, fileName), 'utf8');
  const compiled = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
    fileName,
  }).outputText;
  const module = { exports: {} };
  cache.set(fileName, module);
  vm.runInNewContext(compiled, {
    module,
    exports: module.exports,
    require: (specifier) => {
      if (specifier === './atomicBeginnerExercises') return loadTsExports('atomicBeginnerExercises.ts');
      if (specifier === './atomicBeginnerGraders') return loadTsExports('atomicBeginnerGraders.ts');
      return {};
    },
  }, { filename: fileName });
  return module.exports;
}

const heading = /^#\s*(Using|Script|Direct|Built|Manual|Alternative|Try|Another|Equivalent|Convert|Modify|Consider|Nested|Advanced|Callable|Example|Reference)\b/i;
const records = [];

for (const exercise of loadTsExports('exercises.ts').EXERCISES) {
  const prefix = [];
  const sections = [];
  let current = null;
  for (const line of String(exercise.solution).split('\n')) {
    if (heading.test(line.trim())) {
      if (current) sections.push(current);
      current = [];
    } else if (current) current.push(line);
    else prefix.push(line);
  }
  if (current) sections.push(current);
  if (!sections.length) sections.push(String(exercise.solution).split('\n'));
  sections.forEach((lines, index) => records.push({
    id: exercise.id,
    index,
    code: [...prefix, ...lines].join('\n').trim(),
  }));
}

const checker = [
  'import json, sys',
  'for line in sys.stdin:',
  '    item = json.loads(line)',
  '    try:',
  '        compile(item["code"], "<solution>", "exec")',
  '    except Exception:',
  '        print(f"{item[\'id\']}:{item[\'index\']}")',
].join('\n');
const result = spawnSync('python3', ['-c', checker], {
  input: records.map(record => JSON.stringify(record)).join('\n'),
  encoding: 'utf8',
  maxBuffer: 20 * 1024 * 1024,
});
if (result.status !== 0) throw new Error(result.stderr || `Python exited ${result.status}`);

const invalid = {};
for (const line of result.stdout.trim().split('\n').filter(Boolean)) {
  const [id, index] = line.split(':').map(Number);
  (invalid[id] ??= []).push(index);
}
const output = [
  '// Generated by scripts/generate_solution_section_manifest.js.',
  '// Section indexes listed here do not compile as standalone Python.',
  `export const INVALID_SOLUTION_SECTION_INDEXES: Readonly<Record<number, readonly number[]>> = ${JSON.stringify(invalid, null, 2)};`,
  '',
].join('\n');
fs.writeFileSync(path.join(root, 'services/solutionSectionManifest.ts'), output);
console.log(`Recorded ${Object.values(invalid).flat().length} invalid sections across ${Object.keys(invalid).length} exercises.`);
