#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const START_ID = 6608;
const PACK_SIZE = 50;
const specs = [];

const py = value => {
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (value === null || value === undefined) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(py).join(', ')}]`;
  if (typeof value === 'object') return `{${Object.entries(value).map(([key, item]) => `${py(key)}: ${py(item)}`).join(', ')}}`;
  return String(value);
};

const cases = (inputs, evaluate) => inputs.map(args => ({ args, expected: evaluate(...args) }));
const numericSort = values => [...values].sort((a, b) => a - b);
const equal = (left, right) => JSON.stringify(left) === JSON.stringify(right);
const countMap = values => values.reduce((result, value) => ({ ...result, [String(value)]: (result[String(value)] || 0) + 1 }), {});
const groupThousands = value => String(value).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const pyTruthy = value => {
  if (value === null || value === false) return false;
  if (typeof value === 'number') return value !== 0;
  if (typeof value === 'string' || Array.isArray(value)) return value.length > 0;
  if (value && typeof value === 'object') return Object.keys(value).length > 0;
  return Boolean(value);
};
const stableJson = value => {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`;
  return JSON.stringify(value);
};

const addPack = (concept, focus, definitions, options = {}) => {
  for (let index = 0; index < PACK_SIZE; index += 1) {
    const family = Math.floor(index / 5);
    const variant = index % 5 + 1;
    const spec = definitions[family](variant);
    const level = index < 20 ? 'Easy' : index < 40 ? 'Intermediate' : 'Difficult';
    specs.push({ concept, focus, level, ...options, ...spec, body: spec.body.trim() });
  }
};

addPack('None & Truthiness', 'None identity, truth-value testing, fallbacks, and preserving valid falsy values', [
  c => ({ name: `default_if_none_${c}`, params: 'value', en: `return ${c} only when value is None`, fr: `retourne ${c} uniquement lorsque value vaut None`, body: `return ${c} if value is None else value`, cases: cases([[null], [0], ['']], value => value === null ? c : value), operators: ['Is'] }),
  c => ({ name: `none_count_plus_${c}`, params: 'values', en: `count None values and add ${c}`, fr: `compte les valeurs None et ajoute ${c}`, body: `return sum(value is None for value in values) + ${c}`, cases: cases([[[null, 0, null]], [[]], [[false, null]]], values => values.filter(value => value === null).length + c), operators: ['Is'] }),
  c => ({ name: `truthy_count_plus_${c}`, params: 'values', en: `count truthy values and add ${c}`, fr: `compte les valeurs vraies et ajoute ${c}`, body: `return sum(bool(value) for value in values) + ${c}`, cases: cases([[[0, 1, '', 'x']], [[]], [[false, [], 3]]], values => values.filter(pyTruthy).length + c), calls: ['bool'] }),
  c => ({ name: `first_truthy_or_${c}`, params: 'values', en: `return the first truthy value or ${c}`, fr: `retourne la première valeur vraie ou ${c}`, body: `return next((value for value in values if value), ${c})`, cases: cases([[[0, '', 7, 8]], [[0, false, '']], [['x', 2]]], values => values.find(pyTruthy) ?? c), calls: ['next'] }),
  c => ({ name: `replace_none_${c}`, params: 'values', en: `replace each None item with ${c} while preserving other falsy values`, fr: `remplace chaque élément None par ${c} en conservant les autres valeurs fausses`, body: `return [${c} if value is None else value for value in values]`, cases: cases([[[null, 0, '', 2]], [[]], [[false, null]]], values => values.map(value => value === null ? c : value)), operators: ['Is'] }),
  c => ({ name: `truthy_with_marker_${c}`, params: 'values', en: `keep truthy values and append marker ${c}`, fr: `conserve les valeurs vraies et ajoute le marqueur ${c}`, body: `return [value for value in values if value] + [${c}]`, cases: cases([[[0, 1, '', 2]], [[]], [[false, 'ok']]], values => values.filter(pyTruthy).concat(c)) }),
  c => ({ name: `both_present_${c}`, params: 'left, right', en: `test that both values are not None for check ${c}`, fr: `vérifie que les deux valeurs ne valent pas None pour le contrôle ${c}`, body: `return left is not None and right is not None`, cases: cases([[0, ''], [null, 1], [2, null]], (left, right) => left !== null && right !== null), operators: ['IsNot'], boolOps: ['And'] }),
  c => ({ name: `coalesce_${c}`, params: 'primary, secondary', en: `return the first non-None value, or ${c}`, fr: `retourne la première valeur différente de None, ou ${c}`, body: `if primary is not None:\n        return primary\n    if secondary is not None:\n        return secondary\n    return ${c}`, cases: cases([[null, 8], [0, 9], [null, null]], (primary, secondary) => primary !== null ? primary : secondary !== null ? secondary : c), operators: ['IsNot'] }),
  c => ({ name: `none_indexes_from_${c}`, params: 'values', en: `return indexes of None values, offset by ${c}`, fr: `retourne les indices des valeurs None, décalés de ${c}`, body: `return [index + ${c} for index, value in enumerate(values) if value is None]`, cases: cases([[[null, 0, null]], [[]], [[1, null]]], values => values.flatMap((value, index) => value === null ? [index + c] : [])), operators: ['Is'] }),
  c => ({ name: `truthy_keys_${c}`, params: 'mapping', en: `return sorted keys with truthy values plus marker key ${JSON.stringify(`marker_${c}`)}`, fr: `retourne les clés triées aux valeurs vraies avec la clé marqueur ${JSON.stringify(`marker_${c}`)}`, body: `result = [key for key, value in mapping.items() if value]\n    result.append(${py(`marker_${c}`)})\n    return sorted(result)`, cases: cases([[{ a: 1, b: 0 }], [{}], [{ x: '', y: true }]], mapping => [...Object.keys(mapping).filter(key => pyTruthy(mapping[key])), `marker_${c}`].sort()) }),
]);

addPack('Equality & Identity', 'value equality, object identity, type-aware comparison, and normalization before comparison', [
  c => ({ name: `is_none_check_${c}`, params: 'value', en: `use identity to test whether value is None for check ${c}`, fr: `utilise l’identité pour tester si value vaut None pour le contrôle ${c}`, body: 'return value is None', cases: cases([[null], [0], ['']], value => value === null), operators: ['Is'] }),
  c => ({ name: `is_not_none_check_${c}`, params: 'value', en: `use identity to test whether value is not None for check ${c}`, fr: `utilise l’identité pour tester si value ne vaut pas None pour le contrôle ${c}`, body: 'return value is not None', cases: cases([[null], [0], [false]], value => value !== null), operators: ['IsNot'] }),
  c => ({ name: `equal_after_offset_${c}`, params: 'left, right', en: `test whether left plus ${c} equals right`, fr: `teste si left plus ${c} est égal à right`, body: `return left + ${c} == right`, cases: cases([[2, 2 + c], [0, c], [3, 9]], (left, right) => left + c === right), operators: ['Eq'] }),
  c => ({ name: `same_type_and_value_${c}`, params: 'left, right', en: `test equal value and identical type for comparison ${c}`, fr: `teste une valeur égale et un type identique pour la comparaison ${c}`, body: 'return type(left) is type(right) and left == right', cases: cases([[1, 1], [1, true], ['1', '1']], (left, right) => typeof left === typeof right && equal(left, right)), calls: ['type'], operators: ['Is', 'Eq'], boolOps: ['And'] }),
  c => ({ name: `normalized_text_equal_${c}`, params: 'left, right', en: `compare text after trimming whitespace and ignoring case for check ${c}`, fr: `compare le texte après suppression des espaces et sans tenir compte de la casse pour le contrôle ${c}`, body: 'return left.strip().casefold() == right.strip().casefold()', cases: cases([[' Python ', 'python'], ['A', 'b'], ['', ' ']], (left, right) => left.trim().toLowerCase() === right.trim().toLowerCase()), operators: ['Eq'] }),
  c => ({ name: `same_sorted_values_${c}`, params: 'left, right', en: `test whether two lists contain equal sorted values for check ${c}`, fr: `teste si deux listes contiennent les mêmes valeurs triées pour le contrôle ${c}`, body: 'return sorted(left) == sorted(right)', cases: cases([[[2, 1, 2], [1, 2, 2]], [[1], [1, 1]], [[], []]], (left, right) => equal(numericSort(left), numericSort(right))), calls: ['sorted'], operators: ['Eq'] }),
  c => ({ name: `count_equal_plus_${c}`, params: 'values, target', en: `count values equal to target and add ${c}`, fr: `compte les valeurs égales à target et ajoute ${c}`, body: `return sum(value == target for value in values) + ${c}`, cases: cases([[[1, 2, 1], 1], [[], 3], [['a', 'b'], 'x']], (values, target) => values.filter(value => equal(value, target)).length + c), operators: ['Eq'] }),
  c => ({ name: `all_equal_${c}`, params: 'values, target', en: `test whether every value equals target for check ${c}`, fr: `teste si chaque valeur est égale à target pour le contrôle ${c}`, body: 'return all(value == target for value in values)', cases: cases([[[2, 2], 2], [[2, 3], 2], [[], 1]], (values, target) => values.every(value => equal(value, target))), calls: ['all'], operators: ['Eq'] }),
  c => ({ name: `exact_boolean_${c}`, params: 'value', en: `test whether value is exactly ${c % 2 ? 'True' : 'False'}, not merely truthy, for identity case ${c}`, fr: `teste si value vaut exactement ${c % 2 ? 'True' : 'False'}, et pas seulement une valeur vraie, pour le cas d’identité ${c}`, body: `return value is ${c % 2 ? 'True' : 'False'}`, cases: cases([[c % 2 === 1], [c % 2 === 0], [1]], value => value === (c % 2 === 1) && typeof value === 'boolean'), operators: ['Is'] }),
  c => ({ name: `mapping_value_equal_${c}`, params: 'mapping, key, expected', en: `compare a mapping value with expected, using ${c} when key is missing`, fr: `compare une valeur du dictionnaire à expected en utilisant ${c} si la clé manque`, body: `return mapping.get(key, ${c}) == expected`, cases: cases([[{ a: 2 }, 'a', 2], [{}, 'x', c], [{ a: 1 }, 'a', 9]], (mapping, key, expected) => equal(Object.hasOwn(mapping, key) ? mapping[key] : c, expected)), calls: ['get'], operators: ['Eq'] }),
]);

addPack('String Formatting', 'f-string fields, format specifications, alignment, precision, signs, and readable output', [
  c => ({ name: `format_greeting_${c}`, params: 'name', en: `return an f-string greeting tagged with ${c}`, fr: `retourne une salutation f-string marquée par ${c}`, body: `return f"Hello, {name}! [${c}]"`, cases: cases([['Ada'], [''], ['Noll']], name => `Hello, ${name}! [${c}]`) }),
  c => ({ name: `format_fixed_${c}`, params: 'number', en: `format number with exactly ${c} decimal places`, fr: `formate number avec exactement ${c} décimales`, body: `return f"{number:.${c}f}"`, cases: cases([[3.1415926], [2], [-1.26]], number => number.toFixed(c)) }),
  c => ({ name: `format_zero_pad_${c}`, params: 'number', en: `format an integer with zero padding to width ${c + 3}`, fr: `formate un entier avec des zéros sur une largeur de ${c + 3}`, body: `return f"{number:0${c + 3}d}"`, cases: cases([[7], [42], [0]], number => String(number).padStart(c + 3, '0')) }),
  c => ({ name: `format_right_align_${c}`, params: 'text', en: `right-align text in a field of width ${c + 6}`, fr: `aligne le texte à droite dans un champ de largeur ${c + 6}`, body: `return f"{text:>${c + 6}}"`, cases: cases([['cat'], [''], ['python']], text => text.padStart(c + 6, ' ')) }),
  c => ({ name: `format_percent_${c}`, params: 'ratio', en: `format ratio as a percentage with ${c} decimal places`, fr: `formate ratio en pourcentage avec ${c} décimales`, body: `return f"{ratio:.${c}%}"`, cases: cases([[0.25], [1], [0.035]], ratio => `${(ratio * 100).toFixed(c)}%`) }),
  c => ({ name: `format_signed_${c}`, params: 'number', en: `show a number with an explicit sign and ${c} decimals`, fr: `affiche un nombre avec un signe explicite et ${c} décimales`, body: `return f"{number:+.${c}f}"`, cases: cases([[3.5], [-2], [0]], number => `${number >= 0 ? '+' : ''}${number.toFixed(c)}`) }),
  c => ({ name: `format_grouped_${c}`, params: 'number', en: `format an integer with thousands separators and marker ${c}`, fr: `formate un entier avec des séparateurs de milliers et le marqueur ${c}`, body: `return f"{number:,}|${c}"`, cases: cases([[1234567], [1000], [42]], number => `${groupThousands(number)}|${c}`) }),
  c => ({ name: `format_record_${c}`, params: 'name, score', en: `format a labeled name and score row with score width ${c + 2}`, fr: `formate une ligne nom-score avec une largeur de score de ${c + 2}`, body: `return f"{name}: {score:>${c + 2}}"`, cases: cases([['Ada', 9], ['Bob', 100], ['', 0]], (name, score) => `${name}: ${String(score).padStart(c + 2, ' ')}`) }),
  c => ({ name: `format_coordinates_${c}`, params: 'x, y', en: `format coordinates with ${c} decimal places`, fr: `formate des coordonnées avec ${c} décimales`, body: `return f"({x:.${c}f}, {y:.${c}f})"`, cases: cases([[1.2, 3.4], [0, -2.5], [9.876, 1.234]], (x, y) => `(${x.toFixed(c)}, ${y.toFixed(c)})`) }),
  c => ({ name: `format_centered_${c}`, params: 'text', en: `center text using dots in width ${c * 2 + 7}`, fr: `centre le texte avec des points sur une largeur de ${c * 2 + 7}`, body: `return f"{text:.^${c * 2 + 7}}"`, cases: cases([['AI'], ['x'], ['python']], text => { const width = c * 2 + 7; const remaining = Math.max(0, width - text.length); return '.'.repeat(Math.floor(remaining / 2)) + text + '.'.repeat(Math.ceil(remaining / 2)); }) }),
]);

addPack('Numbers & Precision', 'division behavior, rounding boundaries, tolerances, Decimal arithmetic, and numeric result types', [
  c => ({ name: `rounded_sum_${c}`, params: 'left, right', en: `add two numbers and round to ${c} decimal places`, fr: `additionne deux nombres et arrondit à ${c} décimales`, body: `return round(left + right, ${c})`, cases: cases([[1.2345, 2.3456], [0.1, 0.2], [-1.25, 0.5]], (left, right) => Number((left + right).toFixed(c))), calls: ['round'] }),
  c => ({ name: `safe_percentage_${c}`, params: 'part, whole', en: `return a percentage rounded to ${c} decimals, or 0 when whole is zero`, fr: `retourne un pourcentage arrondi à ${c} décimales, ou 0 si whole vaut zéro`, body: `if whole == 0:\n        return 0\n    return round(part / whole * 100, ${c})`, cases: cases([[1, 4], [2, 3], [5, 0]], (part, whole) => whole === 0 ? 0 : Number((part / whole * 100).toFixed(c))), calls: ['round'] }),
  c => ({ name: `quotient_remainder_${c}`, params: 'number', en: `return quotient and remainder after division by ${c + 1}`, fr: `retourne le quotient et le reste après division par ${c + 1}`, body: `quotient, remainder = divmod(number, ${c + 1})\n    return [quotient, remainder]`, cases: cases([[17], [0], [42]], number => [Math.floor(number / (c + 1)), number % (c + 1)]), calls: ['divmod'] }),
  c => ({ name: `clamp_number_${c}`, params: 'value', en: `clamp value to the inclusive range ${-c} through ${c}`, fr: `limite value à l’intervalle inclusif de ${-c} à ${c}`, body: `return max(${-c}, min(value, ${c}))`, cases: cases([[-20], [0], [20]], value => Math.max(-c, Math.min(value, c))), calls: ['max', 'min'] }),
  c => ({ name: `rounded_average_${c}`, params: 'values', en: `return the average rounded to ${c} decimals, or 0 for an empty list`, fr: `retourne la moyenne arrondie à ${c} décimales, ou 0 pour une liste vide`, body: `if not values:\n        return 0\n    return round(sum(values) / len(values), ${c})`, cases: cases([[[1, 2, 3]], [[1, 2]], [[]]], values => values.length ? Number((values.reduce((a, b) => a + b, 0) / values.length).toFixed(c)) : 0), calls: ['round'] }),
  c => ({ name: `nearly_equal_${c}`, params: 'left, right', en: `test whether numbers differ by at most 10 to the power -${c}`, fr: `teste si les nombres diffèrent d’au plus 10 puissance -${c}`, body: `return abs(left - right) <= 10 ** -${c}`, cases: cases([[1, 1 + 10 ** (-c) / 2], [1, 1 + 10 ** (-c) * 2], [0, 0]], (left, right) => Math.abs(left - right) <= 10 ** -c), calls: ['abs'] }),
  c => ({ name: `decimal_sum_${c}`, params: 'left, right', en: `add decimal text exactly and return ${c} fixed decimal places`, fr: `additionne exactement deux textes décimaux et retourne ${c} décimales fixes`, imports: 'from decimal import Decimal', body: `total = Decimal(left) + Decimal(right)\n    return f"{total:.${c}f}"`, cases: cases([['0.1', '0.2'], ['1.25', '2.5'], ['-1', '0.5']], (left, right) => (Number(left) + Number(right)).toFixed(c)), calls: ['Decimal'] }),
  c => ({ name: `compound_once_${c}`, params: 'principal, rate', en: `apply one percentage growth step and round to ${c} decimals`, fr: `applique une étape de croissance en pourcentage et arrondit à ${c} décimales`, body: `return round(principal * (1 + rate / 100), ${c})`, cases: cases([[100, 5], [80, 12.5], [50, -10]], (principal, rate) => Number((principal * (1 + rate / 100)).toFixed(c))), calls: ['round'] }),
  c => ({ name: `split_money_${c}`, params: 'total, people', en: `split money equally and round each share to ${c} decimals`, fr: `partage une somme également et arrondit chaque part à ${c} décimales`, body: `if people <= 0:\n        return 0\n    return round(total / people, ${c})`, cases: cases([[10, 3], [20, 4], [5, 0]], (total, people) => people <= 0 ? 0 : Number((total / people).toFixed(c))), calls: ['round'] }),
  c => ({ name: `weighted_average_${c}`, params: 'values, weights', en: `return the weighted average rounded to ${c} decimals`, fr: `retourne la moyenne pondérée arrondie à ${c} décimales`, body: `total_weight = sum(weights)\n    if total_weight == 0:\n        return 0\n    return round(sum(value * weight for value, weight in zip(values, weights)) / total_weight, ${c})`, cases: cases([[[10, 20], [1, 3]], [[5], [2]], [[1, 2], [0, 0]]], (values, weights) => { const total = weights.reduce((a, b) => a + b, 0); return total === 0 ? 0 : Number((values.reduce((sum, value, index) => sum + value * weights[index], 0) / total).toFixed(c)); }), calls: ['round', 'zip'] }),
]);

addPack('Mutability & Copying', 'aliases versus copies, in-place mutation, shallow copies, deep copies, and preserving caller-owned data', [
  c => ({ name: `copy_append_${c}`, params: 'values', en: `return a copied list with ${c} appended without changing the input`, fr: `retourne une copie de la liste avec ${c} ajouté sans modifier l’entrée`, body: `result = values.copy()\n    result.append(${c})\n    return result`, cases: cases([[[1, 2]], [[]], [[c]]], values => [...values, c]), calls: ['copy', 'append'] }),
  c => ({ name: `copy_replace_first_${c}`, params: 'values', en: `replace the first item with ${c} in a copied list`, fr: `remplace le premier élément par ${c} dans une copie de la liste`, body: `result = values.copy()\n    if result:\n        result[0] = ${c}\n    return result`, cases: cases([[[1, 2]], [[]], [[9]]], values => values.length ? [c, ...values.slice(1)] : []), calls: ['copy'] }),
  c => ({ name: `copy_dict_marker_${c}`, params: 'mapping', en: `copy a dictionary and set marker to ${c}`, fr: `copie un dictionnaire et fixe marker à ${c}`, body: `result = mapping.copy()\n    result["marker"] = ${c}\n    return result`, cases: cases([[{ a: 1 }], [{}], [{ marker: 9 }]], mapping => ({ ...mapping, marker: c })), calls: ['copy'] }),
  c => ({ name: `copy_remove_${c}`, params: 'values', en: `remove the first occurrence of ${c} from a copied list`, fr: `retire la première occurrence de ${c} d’une copie de la liste`, body: `result = values.copy()\n    if ${c} in result:\n        result.remove(${c})\n    return result`, cases: cases([[[c, 2, c]], [[1, 2]], [[]]], values => { const result = [...values]; const index = result.indexOf(c); if (index >= 0) result.splice(index, 1); return result; }), calls: ['copy', 'remove'] }),
  c => ({ name: `copy_extend_${c}`, params: 'values, extra', en: `extend a copied list and append marker ${c}`, fr: `étend une copie de la liste et ajoute le marqueur ${c}`, body: `result = values.copy()\n    result.extend(extra)\n    result.append(${c})\n    return result`, cases: cases([[[1], [2, 3]], [[], []], [[9], []]], (values, extra) => [...values, ...extra, c]), calls: ['copy', 'extend'] }),
  c => ({ name: `nested_row_copy_${c}`, params: 'matrix', en: `copy every nested row and append ${c} to the first copied row`, fr: `copie chaque ligne imbriquée et ajoute ${c} à la première ligne copiée`, body: `result = [row.copy() for row in matrix]\n    if result:\n        result[0].append(${c})\n    return result`, cases: cases([[[[1], [2]]], [[]], [[[9]]]], matrix => matrix.length ? [[...matrix[0], c], ...matrix.slice(1).map(row => [...row])] : []), calls: ['copy'] }),
  c => ({ name: `merged_mapping_copy_${c}`, params: 'left, right', en: `merge two mappings into a new dictionary and add marker ${c}`, fr: `fusionne deux dictionnaires dans un nouveau et ajoute le marqueur ${c}`, body: `result = left.copy()\n    result.update(right)\n    result["marker"] = ${c}\n    return result`, cases: cases([[{ a: 1 }, { b: 2 }], [{ a: 1 }, { a: 9 }], [{}, {}]], (left, right) => ({ ...left, ...right, marker: c })), calls: ['copy', 'update'] }),
  c => ({ name: `sorted_copy_plus_${c}`, params: 'values', en: `sort a copied list in place and append ${c}`, fr: `trie une copie de la liste sur place et ajoute ${c}`, body: `result = values.copy()\n    result.sort()\n    result.append(${c})\n    return result`, cases: cases([[[3, 1, 2]], [[]], [[-1, 4]]], values => numericSort(values).concat(c)), calls: ['copy', 'sort'] }),
  c => ({ name: `deepcopy_nested_${c}`, params: 'data', en: `deep-copy nested data and store ${c} under marker`, fr: `effectue une copie profonde des données et stocke ${c} sous marker`, imports: 'from copy import deepcopy', body: `result = deepcopy(data)\n    result["marker"] = {"value": ${c}}\n    return result`, cases: cases([[{ items: [1, 2] }], [{}], [{ marker: { value: 9 } }]], data => ({ ...JSON.parse(JSON.stringify(data)), marker: { value: c } })), calls: ['deepcopy'] }),
  c => ({ name: `alias_append_${c}`, params: 'values', en: `demonstrate aliasing by appending ${c} through an alias and returning both names`, fr: `démontre un alias en ajoutant ${c} par l’alias et retourne les deux noms`, body: `alias = values\n    alias.append(${c})\n    return [values, alias]`, cases: cases([[[1]], [[]], [[9, 8]]], values => { const changed = [...values, c]; return [changed, changed]; }), calls: ['append'] }),
]);

addPack('Stacks & Queues', 'LIFO and FIFO ordering, push/pop operations, deque operations, and safe empty-container behavior', [
  c => ({ name: `stack_push_${c}`, params: 'stack', en: `push ${c} onto a copied stack`, fr: `empile ${c} sur une copie de la pile`, body: `result = stack.copy()\n    result.append(${c})\n    return result`, cases: cases([[[1, 2]], [[]], [[9]]], stack => [...stack, c]), calls: ['append'] }),
  c => ({ name: `stack_pop_or_${c}`, params: 'stack', en: `pop and return the top item, or ${c} when empty`, fr: `dépile et retourne l’élément supérieur, ou ${c} si la pile est vide`, body: `result = stack.copy()\n    return result.pop() if result else ${c}`, cases: cases([[[1, 2]], [[]], [[9]]], stack => stack.length ? stack.at(-1) : c), calls: ['pop'] }),
  c => ({ name: `reverse_with_stack_${c}`, params: 'items', en: `reverse items with stack pop operations and append marker ${c}`, fr: `inverse les éléments avec des dépilements et ajoute le marqueur ${c}`, body: `stack = items.copy()\n    result = []\n    while stack:\n        result.append(stack.pop())\n    result.append(${c})\n    return result`, cases: cases([[[1, 2, 3]], [[]], [['a', 'b']]], items => [...items].reverse().concat(c)), calls: ['pop'], nodes: [{ nodeType: 'While', minCount: 1 }] }),
  c => ({ name: `balanced_parentheses_${c}`, params: 'text', en: `test balanced parentheses while ignoring non-parenthesis text for check ${c}`, fr: `teste l’équilibre des parenthèses en ignorant les autres caractères pour le contrôle ${c}`, body: `stack = []\n    for char in text:\n        if char == "(":\n            stack.append(char)\n        elif char == ")":\n            if not stack:\n                return False\n            stack.pop()\n    return not stack`, cases: cases([['(a(b))'], ['(()'], [')(']], text => { let depth = 0; for (const char of text) { if (char === '(') depth++; if (char === ')' && --depth < 0) return false; } return depth === 0; }), calls: ['pop'] }),
  c => ({ name: `queue_enqueue_${c}`, params: 'values', en: `enqueue ${c} in a deque and return the queue as a list`, fr: `ajoute ${c} dans une deque et retourne la file comme liste`, imports: 'from collections import deque', body: `queue = deque(values)\n    queue.append(${c})\n    return list(queue)`, cases: cases([[[1, 2]], [[]], [[9]]], values => [...values, c]), calls: ['deque', 'append'] }),
  c => ({ name: `queue_dequeue_or_${c}`, params: 'values', en: `dequeue the first value, or ${c} when empty`, fr: `retire la première valeur de la file, ou ${c} si elle est vide`, imports: 'from collections import deque', body: `queue = deque(values)\n    return queue.popleft() if queue else ${c}`, cases: cases([[[1, 2]], [[]], [[9]]], values => values.length ? values[0] : c), calls: ['deque', 'popleft'] }),
  c => ({ name: `queue_rotate_${c}`, params: 'values', en: `rotate a deque right by ${c} positions`, fr: `fait tourner une deque de ${c} positions vers la droite`, imports: 'from collections import deque', body: `queue = deque(values)\n    queue.rotate(${c})\n    return list(queue)`, cases: cases([[[1, 2, 3, 4]], [[]], [[9]]], values => { if (!values.length) return []; const shift = c % values.length; return values.slice(-shift).concat(values.slice(0, -shift)); }), calls: ['deque', 'rotate'] }),
  c => ({ name: `serve_queue_${c}`, params: 'values', en: `serve at most ${c} FIFO items and return them`, fr: `sert au maximum ${c} éléments FIFO et les retourne`, imports: 'from collections import deque', body: `queue = deque(values)\n    served = []\n    while queue and len(served) < ${c}:\n        served.append(queue.popleft())\n    return served`, cases: cases([[[1, 2, 3, 4, 5, 6]], [[9]], [[]]], values => values.slice(0, c)), calls: ['deque', 'popleft'] }),
  c => ({ name: `interleave_queues_${c}`, params: 'left, right', en: `interleave two queues and append marker ${c}`, fr: `entrelace deux files et ajoute le marqueur ${c}`, imports: 'from collections import deque', body: `first = deque(left)\n    second = deque(right)\n    result = []\n    while first or second:\n        if first:\n            result.append(first.popleft())\n        if second:\n            result.append(second.popleft())\n    result.append(${c})\n    return result`, cases: cases([[[1, 3], [2, 4]], [[1], [2, 3]], [[], []]], (left, right) => { const result = []; for (let i = 0; i < Math.max(left.length, right.length); i++) { if (i < left.length) result.push(left[i]); if (i < right.length) result.push(right[i]); } return result.concat(c); }), calls: ['deque', 'popleft'] }),
  c => ({ name: `queue_last_after_${c}`, params: 'values', en: `enqueue ${c}, dequeue one item when possible, and return the final queue`, fr: `ajoute ${c}, retire un élément si possible et retourne la file finale`, imports: 'from collections import deque', body: `queue = deque(values)\n    queue.append(${c})\n    if queue:\n        queue.popleft()\n    return list(queue)`, cases: cases([[[1, 2]], [[]], [[9]]], values => [...values, c].slice(1)), calls: ['deque', 'popleft'] }),
]);

addPack('Collections Module', 'specialized containers, Counter frequencies, defaultdict grouping, deque workflows, and named records', [
  c => ({ name: `counter_with_marker_${c}`, params: 'values', en: `return item frequencies with marker count ${c}`, fr: `retourne les fréquences avec un compteur marker égal à ${c}`, imports: 'from collections import Counter', body: `counts = Counter(values)\n    counts["marker"] = ${c}\n    return dict(counts)`, cases: cases([[['a', 'b', 'a']], [[]], [['x']]], values => ({ ...countMap(values), marker: c })), calls: ['Counter'] }),
  c => ({ name: `most_common_sorted_${c}`, params: 'values', en: `return up to ${c} most frequent values using deterministic tie sorting`, fr: `retourne au maximum ${c} valeurs les plus fréquentes avec un tri déterministe des égalités`, imports: 'from collections import Counter', body: `counts = Counter(values)\n    return sorted(counts, key=lambda value: (-counts[value], value))[:${c}]`, cases: cases([[[1, 2, 1, 3, 2, 1]], [[]], [[3, 2, 3, 2]]], values => Object.keys(countMap(values)).map(Number).sort((a, b) => countMap(values)[b] - countMap(values)[a] || a - b).slice(0, c)), calls: ['Counter', 'sorted'] }),
  c => ({ name: `counter_missing_${c}`, params: 'values, target', en: `return target frequency plus ${c} using Counter`, fr: `retourne la fréquence de target plus ${c} avec Counter`, imports: 'from collections import Counter', body: `counts = Counter(values)\n    return counts[target] + ${c}`, cases: cases([[[1, 2, 1], 1], [[], 9], [['a'], 'x']], (values, target) => values.filter(value => equal(value, target)).length + c), calls: ['Counter'] }),
  c => ({ name: `counter_merge_${c}`, params: 'left, right', en: `merge two counters and add ${c} to marker`, fr: `fusionne deux Counter et ajoute ${c} à marker`, imports: 'from collections import Counter', body: `counts = Counter(left) + Counter(right)\n    counts["marker"] += ${c}\n    return dict(counts)`, cases: cases([[['a'], ['a', 'b']], [[], []], [['x'], []]], (left, right) => ({ ...countMap([...left, ...right]), marker: c })), calls: ['Counter'] }),
  c => ({ name: `group_by_length_${c}`, params: 'words', en: `group words by length using defaultdict and add marker group ${c}`, fr: `regroupe les mots par longueur avec defaultdict et ajoute le groupe marqueur ${c}`, imports: 'from collections import defaultdict', body: `groups = defaultdict(list)\n    for word in words:\n        groups[str(len(word))].append(word)\n    groups["marker"].append(${c})\n    return dict(groups)`, cases: cases([[['a', 'to', 'b']], [[]], [['python']]], words => { const result = {}; for (const word of words) (result[String(word.length)] ||= []).push(word); result.marker = [c]; return result; }), calls: ['defaultdict'] }),
  c => ({ name: `sum_by_key_${c}`, params: 'pairs', en: `sum pair values by key with defaultdict and add marker ${c}`, fr: `additionne les valeurs par clé avec defaultdict et ajoute le marqueur ${c}`, imports: 'from collections import defaultdict', body: `totals = defaultdict(int)\n    for key, value in pairs:\n        totals[key] += value\n    totals["marker"] += ${c}\n    return dict(totals)`, cases: cases([[[['a', 1], ['a', 2], ['b', 4]]], [[]], [[['x', -1]]]], pairs => { const result = {}; for (const [key, value] of pairs) result[key] = (result[key] || 0) + value; result.marker = (result.marker || 0) + c; return result; }), calls: ['defaultdict'] }),
  c => ({ name: `deque_window_${c}`, params: 'values', en: `keep only the last ${c} values with a bounded deque`, fr: `conserve uniquement les ${c} dernières valeurs avec une deque limitée`, imports: 'from collections import deque', body: `window = deque(values, maxlen=${c})\n    return list(window)`, cases: cases([[[1, 2, 3, 4, 5, 6]], [[]], [[9]]], values => values.slice(-c)), calls: ['deque'] }),
  c => ({ name: `deque_both_ends_${c}`, params: 'values', en: `add ${c} to both ends of a deque`, fr: `ajoute ${c} aux deux extrémités d’une deque`, imports: 'from collections import deque', body: `items = deque(values)\n    items.appendleft(${c})\n    items.append(${c})\n    return list(items)`, cases: cases([[[1, 2]], [[]], [[9]]], values => [c, ...values, c]), calls: ['deque', 'appendleft'] }),
  c => ({ name: `named_point_total_${c}`, params: 'x, y', en: `create a namedtuple point and return its coordinates plus ${c}`, fr: `crée un point namedtuple et retourne ses coordonnées plus ${c}`, imports: 'from collections import namedtuple', body: `Point = namedtuple("Point", ["x", "y"])\n    point = Point(x, y)\n    return point.x + point.y + ${c}`, cases: cases([[1, 2], [-1, 4], [0, 0]], (x, y) => x + y + c), calls: ['namedtuple'] }),
  c => ({ name: `named_record_dict_${c}`, params: 'name, score', en: `create a namedtuple record and return a dictionary with bonus ${c}`, fr: `crée un enregistrement namedtuple et retourne un dictionnaire avec un bonus de ${c}`, imports: 'from collections import namedtuple', body: `Record = namedtuple("Record", ["name", "score"])\n    record = Record(name, score + ${c})\n    return dict(record._asdict())`, cases: cases([['Ada', 10], ['', 0], ['Noll', -1]], (name, score) => ({ name, score: score + c })), calls: ['namedtuple'] }),
]);

addPack('Paths & Directories', 'portable path parsing, names, suffixes, parents, joins, relative paths, and extension filtering', [
  c => ({ name: `path_name_${c}`, params: 'path_text', en: `return the final path name plus marker ${c}`, fr: `retourne le nom final du chemin avec le marqueur ${c}`, imports: 'from pathlib import PurePosixPath', body: `return PurePosixPath(path_text).name + "|${c}"`, cases: cases([['docs/readme.txt'], ['/tmp/data.csv'], ['file.py']], pathText => `${pathText.split('/').filter(Boolean).at(-1) || ''}|${c}`), calls: ['PurePosixPath'] }),
  c => ({ name: `path_stem_${c}`, params: 'path_text', en: `return the filename stem plus marker ${c}`, fr: `retourne le radical du nom de fichier avec le marqueur ${c}`, imports: 'from pathlib import PurePosixPath', body: `return PurePosixPath(path_text).stem + "|${c}"`, cases: cases([['docs/readme.txt'], ['archive.tar.gz'], ['file']], pathText => { const name = pathText.split('/').at(-1); const index = name.lastIndexOf('.'); return `${index > 0 ? name.slice(0, index) : name}|${c}`; }), calls: ['PurePosixPath'] }),
  c => ({ name: `path_suffix_${c}`, params: 'path_text', en: `return the lowercase suffix or marker .x${c} when absent`, fr: `retourne le suffixe en minuscules ou le marqueur .x${c} s’il manque`, imports: 'from pathlib import PurePosixPath', body: `suffix = PurePosixPath(path_text).suffix.lower()\n    return suffix or ".x${c}"`, cases: cases([['A/FILE.PY'], ['archive.tar.gz'], ['README']], pathText => { const name = pathText.split('/').at(-1); const index = name.lastIndexOf('.'); return index > 0 ? name.slice(index).toLowerCase() : `.x${c}`; }), calls: ['PurePosixPath'] }),
  c => ({ name: `path_parent_name_${c}`, params: 'path_text', en: `return the parent directory name plus marker ${c}`, fr: `retourne le nom du dossier parent avec le marqueur ${c}`, imports: 'from pathlib import PurePosixPath', body: `return PurePosixPath(path_text).parent.name + "|${c}"`, cases: cases([['docs/guides/readme.txt'], ['/tmp/data.csv'], ['folder/file']], pathText => { const parts = pathText.split('/').filter(Boolean); return `${parts.length > 1 ? parts.at(-2) : ''}|${c}`; }), calls: ['PurePosixPath'] }),
  c => ({ name: `path_parts_from_${c}`, params: 'path_text', en: `return path parts after skipping the first ${c} components`, fr: `retourne les parties du chemin après avoir ignoré les ${c} premières`, imports: 'from pathlib import PurePosixPath', body: `return list(PurePosixPath(path_text).parts[${c}:])`, cases: cases([['a/b/c/d/e/f'], ['one/two'], ['/root/sub/file']], pathText => { const parts = pathText.startsWith('/') ? ['/', ...pathText.split('/').filter(Boolean)] : pathText.split('/').filter(Boolean); return parts.slice(c); }), calls: ['PurePosixPath'] }),
  c => ({ name: `path_change_suffix_${c}`, params: 'path_text', en: `replace the path suffix with .v${c}`, fr: `remplace le suffixe du chemin par .v${c}`, imports: 'from pathlib import PurePosixPath', body: `return str(PurePosixPath(path_text).with_suffix(".v${c}"))`, cases: cases([['docs/readme.txt'], ['file'], ['a/archive.tar.gz']], pathText => { const slash = pathText.lastIndexOf('/'); const dir = slash >= 0 ? pathText.slice(0, slash + 1) : ''; const name = pathText.slice(slash + 1); const dot = name.lastIndexOf('.'); return `${dir}${dot > 0 ? name.slice(0, dot) : name}.v${c}`; }), calls: ['PurePosixPath', 'with_suffix'] }),
  c => ({ name: `path_join_${c}`, params: 'base, child', en: `join base, child, and directory level_${c}`, fr: `joint base, child et le dossier level_${c}`, imports: 'from pathlib import PurePosixPath', body: `return str(PurePosixPath(base) / child / "level_${c}")`, cases: cases([['root', 'docs'], ['/tmp', 'data'], ['a/b', 'c']], (base, child) => `${base.replace(/\/$/, '')}/${child}/level_${c}`), calls: ['PurePosixPath'] }),
  c => ({ name: `path_relative_${c}`, params: 'path_text, base', en: `return a path relative to base and append marker part m${c}`, fr: `retourne un chemin relatif à base et ajoute la partie marqueur m${c}`, imports: 'from pathlib import PurePosixPath', body: `relative = PurePosixPath(path_text).relative_to(PurePosixPath(base))\n    return str(relative / "m${c}")`, cases: cases([['root/docs/file.txt', 'root'], ['/a/b/c', '/a'], ['x/y', 'x']], (pathText, base) => `${pathText.slice(base.replace(/\/$/, '').length).replace(/^\//, '')}/m${c}`), calls: ['PurePosixPath', 'relative_to'] }),
  c => ({ name: `filter_suffix_${c}`, params: 'paths, suffix', en: `return sorted paths matching suffix case-insensitively and append marker_${c}`, fr: `retourne les chemins triés correspondant au suffixe sans tenir compte de la casse et ajoute marker_${c}`, imports: 'from pathlib import PurePosixPath', body: `result = [path for path in paths if PurePosixPath(path).suffix.lower() == suffix.lower()]\n    result.sort()\n    result.append("marker_${c}")\n    return result`, cases: cases([[['b.py', 'a.PY', 'c.txt'], '.py'], [[], '.txt'], [['x.csv'], '.json']], (paths, suffix) => paths.filter(item => { const name = item.split('/').at(-1); return name.slice(name.lastIndexOf('.')).toLowerCase() === suffix.toLowerCase(); }).sort().concat(`marker_${c}`)), calls: ['PurePosixPath'] }),
  c => ({ name: `path_suffixes_${c}`, params: 'path_text', en: `return all filename suffixes followed by marker .m${c}`, fr: `retourne tous les suffixes du fichier suivis du marqueur .m${c}`, imports: 'from pathlib import PurePosixPath', body: `return list(PurePosixPath(path_text).suffixes) + [".m${c}"]`, cases: cases([['archive.tar.gz'], ['file.txt'], ['README']], pathText => { const name = pathText.split('/').at(-1); const suffixes = [...name.matchAll(/\.[^.]+/g)].map(match => match[0]); return suffixes.concat(`.m${c}`); }), calls: ['PurePosixPath'] }),
]);

addPack('CSV & JSON', 'structured text parsing, serialization, field selection, type conversion, and deterministic JSON output', [
  c => ({ name: `csv_first_row_${c}`, params: 'text', en: `parse CSV text and append marker ${c} to the first row`, fr: `analyse le texte CSV et ajoute le marqueur ${c} à la première ligne`, imports: 'import csv\nfrom io import StringIO', body: `rows = list(csv.reader(StringIO(text)))\n    first = rows[0] if rows else []\n    return first + [str(${c})]`, cases: cases([['a,b\n1,2'], [''], ['x']], text => { const first = text ? text.split('\n')[0].split(',') : []; return first.concat(String(c)); }), calls: ['reader', 'StringIO'] }),
  c => ({ name: `csv_integer_row_${c}`, params: 'text', en: `parse one CSV row as integers and add ${c} to each`, fr: `analyse une ligne CSV en entiers et ajoute ${c} à chacun`, imports: 'import csv\nfrom io import StringIO', body: `row = next(csv.reader(StringIO(text)), [])\n    return [int(value) + ${c} for value in row]`, cases: cases([['1,2,3'], [''], ['-1,5']], text => text ? text.split(',').map(value => Number(value) + c) : []), calls: ['reader', 'StringIO'] }),
  c => ({ name: `csv_column_${c}`, params: 'text, column', en: `read a named CSV column and append marker ${c}`, fr: `lit une colonne CSV nommée et ajoute le marqueur ${c}`, imports: 'import csv\nfrom io import StringIO', body: `rows = csv.DictReader(StringIO(text))\n    return [row[column] for row in rows] + [str(${c})]`, cases: cases([['name,age\nAda,36\nBob,20', 'name'], ['x\n1', 'x'], ['a,b\n', 'b']], (text, column) => { const lines = text.trimEnd().split('\n'); const headers = lines[0].split(','); const index = headers.indexOf(column); return lines.slice(1).filter(Boolean).map(line => line.split(',')[index]).concat(String(c)); }), calls: ['DictReader', 'StringIO'] }),
  c => ({ name: `csv_row_count_${c}`, params: 'text', en: `count CSV data rows and add ${c}`, fr: `compte les lignes de données CSV et ajoute ${c}`, imports: 'import csv\nfrom io import StringIO', body: `rows = list(csv.reader(StringIO(text)))\n    return max(0, len(rows) - 1) + ${c}`, cases: cases([['a,b\n1,2\n3,4'], ['a'], ['']], text => Math.max(0, (text ? text.split('\n').filter(Boolean).length : 0) - 1) + c), calls: ['reader', 'StringIO'] }),
  c => ({ name: `csv_select_rows_${c}`, params: 'text, column, expected', en: `return CSV rows whose named column equals expected, plus marker row ${c}`, fr: `retourne les lignes CSV dont la colonne nommée vaut expected avec une ligne marqueur ${c}`, imports: 'import csv\nfrom io import StringIO', body: `rows = csv.DictReader(StringIO(text))\n    result = [dict(row) for row in rows if row[column] == expected]\n    result.append({"marker": str(${c})})\n    return result`, cases: cases([['name,role\nAda,dev\nBob,test', 'role', 'dev'], ['x\n1', 'x', '9'], ['a,b\n', 'a', 'x']], (text, column, expected) => { const lines = text.trimEnd().split('\n'); const headers = lines[0].split(','); const result = lines.slice(1).filter(Boolean).map(line => Object.fromEntries(headers.map((key, index) => [key, line.split(',')[index]]))).filter(row => row[column] === expected); return result.concat({ marker: String(c) }); }), calls: ['DictReader', 'StringIO'] }),
  c => ({ name: `json_value_or_${c}`, params: 'text, key', en: `read a JSON object value or return ${c} when missing`, fr: `lit une valeur d’objet JSON ou retourne ${c} si elle manque`, imports: 'import json', body: `data = json.loads(text)\n    return data.get(key, ${c})`, cases: cases([['{"a": 1}', 'a'], ['{}', 'x'], ['{"x": 0}', 'x']], (text, key) => Object.hasOwn(JSON.parse(text), key) ? JSON.parse(text)[key] : c), calls: ['loads'] }),
  c => ({ name: `json_sorted_keys_${c}`, params: 'text', en: `return sorted JSON object keys plus marker_${c}`, fr: `retourne les clés triées de l’objet JSON avec marker_${c}`, imports: 'import json', body: `data = json.loads(text)\n    return sorted(data.keys()) + ["marker_${c}"]`, cases: cases([['{"b": 2, "a": 1}'], ['{}'], ['{"x": 0}']], text => Object.keys(JSON.parse(text)).sort().concat(`marker_${c}`)), calls: ['loads', 'sorted'] }),
  c => ({ name: `json_compact_${c}`, params: 'value', en: `serialize value as compact sorted JSON inside marker ${c}`, fr: `sérialise value en JSON compact trié avec le marqueur ${c}`, imports: 'import json', body: `return json.dumps({"marker": ${c}, "value": value}, sort_keys=True, separators=(",", ":"))`, cases: cases([[{ b: 2, a: 1 }], [[1, 2]], [null]], value => stableJson({ marker: c, value })), calls: ['dumps'] }),
  c => ({ name: `json_nested_value_${c}`, params: 'text, outer, inner', en: `read a nested JSON value or return ${c}`, fr: `lit une valeur JSON imbriquée ou retourne ${c}`, imports: 'import json', body: `data = json.loads(text)\n    nested = data.get(outer, {})\n    return nested.get(inner, ${c}) if isinstance(nested, dict) else ${c}`, cases: cases([['{"a":{"b":2}}', 'a', 'b'], ['{}', 'x', 'y'], ['{"a":1}', 'a', 'b']], (text, outer, inner) => { const nested = JSON.parse(text)[outer]; return nested && typeof nested === 'object' && !Array.isArray(nested) && Object.hasOwn(nested, inner) ? nested[inner] : c; }), calls: ['loads'] }),
  c => ({ name: `json_update_${c}`, params: 'text, key, value', en: `update a JSON object, add marker ${c}, and return compact sorted JSON`, fr: `met à jour un objet JSON, ajoute le marqueur ${c} et retourne un JSON compact trié`, imports: 'import json', body: `data = json.loads(text)\n    data[key] = value\n    data["marker"] = ${c}\n    return json.dumps(data, sort_keys=True, separators=(",", ":"))`, cases: cases([['{"a":1}', 'b', 2], ['{}', 'x', 0], ['{"marker":9}', 'a', true]], (text, key, value) => { const data = { ...JSON.parse(text), [key]: value, marker: c }; return `{${Object.keys(data).sort().map(item => `${JSON.stringify(item)}:${JSON.stringify(data[item])}`).join(',')}}`; }), calls: ['loads', 'dumps'] }),
]);

addPack('Algorithms & Complexity', 'correct algorithm invariants, edge cases, deterministic outputs, and recognizing linear versus logarithmic work', [
  c => ({ name: `linear_search_${c}`, params: 'values, target', en: `find target by linear search and add ${c} to a found index`, fr: `trouve target par recherche linéaire et ajoute ${c} à l’indice trouvé`, body: `for index, value in enumerate(values):\n        if value == target:\n            return index + ${c}\n    return -1`, cases: cases([[[4, 7, 7], 7], [[1, 2], 9], [[], 1]], (values, target) => { const index = values.indexOf(target); return index < 0 ? -1 : index + c; }), nodes: [{ nodeType: 'For', minCount: 1 }] }),
  c => ({ name: `prefix_sums_${c}`, params: 'values', en: `build prefix sums beginning with ${c}`, fr: `construit les sommes préfixes en commençant par ${c}`, body: `total = ${c}\n    result = []\n    for value in values:\n        total += value\n        result.append(total)\n    return result`, cases: cases([[[1, 2, 3]], [[]], [[-1, 4]]], values => { let total = c; return values.map(value => total += value); }), nodes: [{ nodeType: 'For', minCount: 1 }] }),
  c => ({ name: `dedupe_ordered_${c}`, params: 'values', en: `remove duplicates while preserving order, then append ${c}`, fr: `supprime les doublons en conservant l’ordre puis ajoute ${c}`, body: `seen = set()\n    result = []\n    for value in values:\n        if value not in seen:\n            seen.add(value)\n            result.append(value)\n    result.append(${c})\n    return result`, cases: cases([[[1, 2, 1, 3]], [[]], [['a', 'a', 'b']]], values => [...new Set(values), c]), nodes: [{ nodeType: 'For', minCount: 1 }] }),
  c => ({ name: `merge_sorted_${c}`, params: 'left, right', en: `merge two sorted lists and append ${c}`, fr: `fusionne deux listes triées et ajoute ${c}`, body: `result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    result.append(${c})\n    return result`, cases: cases([[[1, 3], [2, 4]], [[], [1]], [[-2, 5], [-1, 6]]], (left, right) => numericSort([...left, ...right]).concat(c)), nodes: [{ nodeType: 'While', minCount: 1 }] }),
  c => ({ name: `binary_search_${c}`, params: 'values, target', en: `find target in a sorted list by binary search and add ${c} to its index`, fr: `trouve target dans une liste triée par recherche binaire et ajoute ${c} à son indice`, body: `low = 0\n    high = len(values) - 1\n    while low <= high:\n        middle = (low + high) // 2\n        if values[middle] == target:\n            return middle + ${c}\n        if values[middle] < target:\n            low = middle + 1\n        else:\n            high = middle - 1\n    return -1`, cases: cases([[[1, 3, 5, 7], 5], [[1, 2], 9], [[], 1]], (values, target) => { const index = values.indexOf(target); return index < 0 ? -1 : index + c; }), nodes: [{ nodeType: 'While', minCount: 1 }] }),
  c => ({ name: `selection_sort_${c}`, params: 'values', en: `selection-sort a copy and append ${c}`, fr: `trie une copie par sélection et ajoute ${c}`, body: `result = values.copy()\n    for start in range(len(result)):\n        smallest = start\n        for index in range(start + 1, len(result)):\n            if result[index] < result[smallest]:\n                smallest = index\n        result[start], result[smallest] = result[smallest], result[start]\n    result.append(${c})\n    return result`, cases: cases([[[3, 1, 2]], [[]], [[-1, 4, 0]]], values => numericSort(values).concat(c)), nodes: [{ nodeType: 'For', minCount: 2 }] }),
  c => ({ name: `bubble_sort_${c}`, params: 'values', en: `bubble-sort a copy and append ${c}`, fr: `trie une copie par bulles et ajoute ${c}`, body: `result = values.copy()\n    for end in range(len(result) - 1, 0, -1):\n        for index in range(end):\n            if result[index] > result[index + 1]:\n                result[index], result[index + 1] = result[index + 1], result[index]\n    result.append(${c})\n    return result`, cases: cases([[[3, 1, 2]], [[]], [[5, -1, 5]]], values => numericSort(values).concat(c)), nodes: [{ nodeType: 'For', minCount: 2 }] }),
  c => ({ name: `has_pair_sum_${c}`, params: 'values, target', en: `test in linear time whether a pair sums to target plus ${c}`, fr: `teste en temps linéaire si une paire a pour somme target plus ${c}`, body: `needed = set()\n    goal = target + ${c}\n    for value in values:\n        if value in needed:\n            return True\n        needed.add(goal - value)\n    return False`, cases: cases([[[2, 7, 11], 4], [[1, 2], 10], [[c, c], c]], (values, target) => { const goal = target + c; return values.some((value, index) => values.slice(index + 1).includes(goal - value)); }), nodes: [{ nodeType: 'For', minCount: 1 }] }),
  c => ({ name: `most_frequent_smallest_${c}`, params: 'values', en: `return the most frequent value, breaking ties by smallest value, or ${c} when empty`, fr: `retourne la valeur la plus fréquente, avec la plus petite en cas d’égalité, ou ${c} si vide`, body: `if not values:\n        return ${c}\n    counts = {}\n    for value in values:\n        counts[value] = counts.get(value, 0) + 1\n    return min(counts, key=lambda value: (-counts[value], value))`, cases: cases([[[2, 1, 2, 1]], [[]], [[3, 3, 2]]], values => { if (!values.length) return c; const counts = countMap(values); return numericSort([...new Set(values)]).sort((a, b) => counts[b] - counts[a] || a - b)[0]; }), nodes: [{ nodeType: 'For', minCount: 1 }] }),
  c => ({ name: `rotate_left_${c}`, params: 'values', en: `rotate a list left by ${c} positions in linear time`, fr: `fait tourner une liste de ${c} positions vers la gauche en temps linéaire`, body: `if not values:\n        return []\n    shift = ${c} % len(values)\n    return values[shift:] + values[:shift]`, cases: cases([[[1, 2, 3, 4, 5, 6]], [[]], [[9]]], values => values.length ? values.slice(c % values.length).concat(values.slice(0, c % values.length)) : []) }),
]);

const expectedConcepts = ['None & Truthiness', 'Equality & Identity', 'String Formatting', 'Numbers & Precision', 'Mutability & Copying', 'Stacks & Queues', 'Collections Module', 'Paths & Directories', 'CSV & JSON', 'Algorithms & Complexity'];
if (specs.length !== expectedConcepts.length * PACK_SIZE) throw new Error(`Expected 500 specs, found ${specs.length}`);
for (const concept of expectedConcepts) {
  const conceptSpecs = specs.filter(spec => spec.concept === concept);
  if (conceptSpecs.length !== PACK_SIZE) throw new Error(`${concept}: expected ${PACK_SIZE}, found ${conceptSpecs.length}`);
  for (const [level, count] of [['Easy', 20], ['Intermediate', 20], ['Difficult', 10]]) {
    const actual = conceptSpecs.filter(spec => spec.level === level).length;
    if (actual !== count) throw new Error(`${concept} ${level}: expected ${count}, found ${actual}`);
  }
}
if (new Set(specs.map(spec => spec.name)).size !== specs.length) throw new Error('Generated function names must be unique.');

const labelsFr = {
  'None & Truthiness': 'None et valeurs de vérité', 'Equality & Identity': 'égalité et identité',
  'String Formatting': 'formatage de chaînes', 'Numbers & Precision': 'nombres et précision',
  'Mutability & Copying': 'mutabilité et copies', 'Stacks & Queues': 'piles et files',
  'Collections Module': 'module collections', 'Paths & Directories': 'chemins et dossiers',
  'CSV & JSON': 'CSV et JSON', 'Algorithms & Complexity': 'algorithmes et complexité',
};
const levelsFr = { Easy: 'Facile', Intermediate: 'Intermédiaire', Difficult: 'Expert' };
const exercises = [];
const graders = {};
const french = {};
const invoke = (spec, test, name = spec.name) => `${name}(${test.args.map(py).join(', ')})`;

specs.forEach((spec, index) => {
  const id = START_ID + index;
  const imports = spec.imports ? `${spec.imports}\n\n` : '';
  const definition = `def ${spec.name}(${spec.params}):\n    ${spec.body}`;
  const nestedBody = definition.split('\n').slice(1).map(line => `    ${line}`).join('\n');
  const classBody = definition.split('\n').map(line => `    ${line}`).join('\n');
  const solution = `${imports}# Example 1: canonical function approach\n${definition}\n\nprint(${invoke(spec, spec.cases[0])})  # Expected: ${py(spec.cases[0].expected)}\nprint(${invoke(spec, spec.cases[1])})  # Expected: ${py(spec.cases[1].expected)}\n\n# Example 2: nested helper approach\ndef solve_problem_${id}(${spec.params}):\n    def calculate():\n${nestedBody}\n    return calculate()\n\nprint(${invoke(spec, spec.cases[0], `solve_problem_${id}`)})\n\n# Example 3: static method approach\nclass Problem${id}Solution:\n    @staticmethod\n${classBody}\n\nprint(Problem${id}Solution.${invoke(spec, spec.cases[1])})\n\n# Example 4: assigned result approach\nresult = ${invoke(spec, spec.cases[0])}\nprint(result)\n\n# Example 5: boundary case\nprint(${invoke(spec, spec.cases[2])})`;
  const description = `Write a Python function called \`${spec.name}\` that must ${spec.en}. Practice ${spec.concept.toLowerCase()}.\nDifficulty: ${spec.level === 'Difficult' ? 'Expert' : spec.level}.\nExamples:\n  ${invoke(spec, spec.cases[0])} -> ${py(spec.cases[0].expected)}\n  ${invoke(spec, spec.cases[1])} -> ${py(spec.cases[1].expected)}`;
  exercises.push({
    id, title: `Problem ${id}`, description, initialCode: `${imports}def ${spec.name}(${spec.params}):\n    pass`, solution,
    hint: `Focus on ${spec.focus}. Work from the input types and required behavior instead of copying an example output.`,
    breakdown: `1. Identify the input types and exact return type.\n2. Identify the ${spec.concept.toLowerCase()} rule required by the task.\n3. Trace the first example operation by operation.\n4. Test the empty, missing, or boundary case.\n5. Return a general result that works for the hidden inputs.`,
    category: `${spec.concept} ${spec.level}`,
  });
  const grader = { functionNames: [spec.name], tests: spec.cases };
  if (spec.nodes?.length) grader.requiredNodePatterns = spec.nodes;
  if (spec.calls?.length) grader.requiredCallPatterns = spec.calls.map(functionName => ({ functionName, minArgs: 0 }));
  if (spec.operators?.length) grader.requiredAstOperators = spec.operators;
  if (spec.boolOps?.length) grader.requiredBoolOps = spec.boolOps;
  graders[id] = grader;
  french[id] = {
    description: `Écrivez une fonction Python appelée \`${spec.name}\` qui ${spec.fr}. Entraînez-vous avec ${labelsFr[spec.concept]}.\nDifficulté : ${levelsFr[spec.level]}.\nExemples :\n  ${invoke(spec, spec.cases[0])} -> ${py(spec.cases[0].expected)}\n  ${invoke(spec, spec.cases[1])} -> ${py(spec.cases[1].expected)}`,
    hint: `Concentrez-vous sur ${labelsFr[spec.concept]}, les types d’entrée et le comportement demandé. Ne copiez pas une sortie d’exemple.`,
    breakdown: `1. Identifiez les types d’entrée et le type de retour exact.\n2. Repérez la règle de ${labelsFr[spec.concept]} demandée.\n3. Suivez le premier exemple opération par opération.\n4. Testez le cas vide, manquant ou limite.\n5. Retournez un résultat général valable pour les tests cachés.`,
  };
});

fs.writeFileSync(path.join(root, 'coreConceptExpansionExercises.ts'), `import type { Exercise } from './types';\n\nexport const CORE_CONCEPT_EXPANSION_EXERCISES: Exercise[] = ${JSON.stringify(exercises, null, 2)};\n`);
fs.writeFileSync(path.join(root, 'coreConceptExpansionGraders.ts'), `import type { AutoGrader } from './graders';\n\nexport const CORE_CONCEPT_EXPANSION_GRADERS: Record<number, AutoGrader> = ${JSON.stringify(graders, null, 2)};\n`);
fs.writeFileSync(path.join(root, 'services/coreConceptExpansionFr.ts'), `export const CORE_CONCEPT_EXPANSION_FR: Record<number, { description: string; hint: string; breakdown: string }> = ${JSON.stringify(french, null, 2)};\n`);

console.log(`Generated ${specs.length} core concept exercises (${START_ID}-${START_ID + specs.length - 1}).`);
